# agentxtrap: Deroffing man parser
# Autogenerated from man pages
complete -c agentxtrap -s c --description 'if the  -c option is present then the notific... [See Man Page]'
complete -c agentxtrap -s U --description 'if the  -U option is present then that value,... [See Man Page]'
complete -c agentxtrap -s x --description 'if the  -x option is present then contact the... [See Man Page]'
complete -c agentxtrap -s d -s D -s m -s M --description 'options are supported'

