# apply: Darwin man parser
# Autogenerated from man pages
complete -c apply -s '#' --description 'Normally arguments are taken singly; the opti... [See Man Page]'
complete -c apply -s a --description 'The use of the character'
complete -c apply -s d --description 'Display the commands that would have been exe... [See Man Page]'

