# apt: Deroffing man parser
# Autogenerated from man pages
complete -c apt -s s --description 'Specify the directory root under which proces... [See Man Page]'
complete -c apt -o nocompile --description 'Do not compile sources files to class files'
complete -c apt -o print --description 'Print out textual representation of specified... [See Man Page]'
complete -c apt -o 'A[' --description 'Options to pass to annotation processors -- t... [See Man Page]'
complete -c apt -o factorypath --description 'Specify where to find annotation processor fa... [See Man Page]'
complete -c apt -o factory --description 'Name of annotation processor factory to use; ... [See Man Page]'
complete -c apt -s d --description 'Specify where to place processor and javac ge... [See Man Page]'
complete -c apt -o cp --description 'or '
complete -c apt -o classpath --description 'Specify where to find user class files and an... [See Man Page]'

