# arch: Darwin man parser
# Autogenerated from man pages
complete -c arch -l 32 --description 'Add the native 32-bit architecture to the lis... [See Man Page]'
complete -c arch -l 64 --description 'Add the native 64-bit architecture to the lis... [See Man Page]'
complete -c arch -s c --description 'Clears the environment that will be passed to... [See Man Page]'
complete -c arch -s d --description 'Deletes the named environment variable from t... [See Man Page]'
complete -c arch -s e --description 'Assigns the given value to the named environm... [See Man Page]'
complete -c arch -s h --description 'Prints a usage message and exits'

