# at: Darwin man parser
# Autogenerated from man pages
complete -c at -s b --description 'Is an alias for'
complete -c at -s c --description 'Cat the jobs listed on the command line to st... [See Man Page]'
complete -c at -s d --description 'Is an alias for'
complete -c at -s f --description 'Read the job from'
complete -c at -s l --description 'With no arguments, list all jobs for the invo... [See Man Page]'
complete -c at -s m --description 'Send mail to the user when the job has comple... [See Man Page]'
complete -c at -s q --description 'Use the specified queue'
complete -c at -s r --description 'Remove the specified jobs'
complete -c at -s t --description 'Specify the job time using the \\*[Px] time fo... [See Man Page]'
complete -c at -s v --description For

