# atos: Darwin man parser
# Autogenerated from man pages
complete -c atos -s o --description 'The path to a binary image file in which to l... [See Man Page]'
complete -c atos -s p --description 'The process ID or the partial name of a curre... [See Man Page]'
complete -c atos -l arch --description 'The particular architecure of a binary image ... [See Man Page]'
complete -c atos -s l --description 'The load address of the binary image'
complete -c atos -s s --description 'The slide value of the binary image -- this i... [See Man Page]'
complete -c atos -l printHeader --description 'If a process was specified, the first line of... [See Man Page]'

