# atrm: Darwin man parser
# Autogenerated from man pages
complete -c atrm -s b --description 'Is an alias for'
complete -c atrm -s c --description 'Cat the jobs listed on the command line to st... [See Man Page]'
complete -c atrm -s d --description 'Is an alias for'
complete -c atrm -s f --description 'Read the job from'
complete -c atrm -s l --description 'With no arguments, list all jobs for the invo... [See Man Page]'
complete -c atrm -s m --description 'Send mail to the user when the job has comple... [See Man Page]'
complete -c atrm -s q --description 'Use the specified queue'
complete -c atrm -s r --description 'Remove the specified jobs'
complete -c atrm -s t --description 'Specify the job time using the \\*[Px] time fo... [See Man Page]'
complete -c atrm -s v --description For

