# auditreduce: Darwin man parser
# Autogenerated from man pages
complete -c auditreduce -s A --description 'Select all records'
complete -c auditreduce -s a --description 'Select records that occurred after or on the ... [See Man Page]'
complete -c auditreduce -s b --description 'Select records that occurred before the given... [See Man Page]'
complete -c auditreduce -s c --description 'Select records matching the given audit class... [See Man Page]'
complete -c auditreduce -s d --description 'Select records that occurred on a given date'
complete -c auditreduce -s e --description 'Select records with the given effective user ... [See Man Page]'
complete -c auditreduce -s f --description 'Select records with the given effective group... [See Man Page]'
complete -c auditreduce -s g --description 'Select records with the given real group ID o... [See Man Page]'
complete -c auditreduce -s j --description 'Select records having a subject token with ma... [See Man Page]'
complete -c auditreduce -s m --description 'Select records with the given event name or n... [See Man Page]'
complete -c auditreduce -s o
complete -c auditreduce -s r --description 'Select records with the given real user ID or... [See Man Page]'
complete -c auditreduce -s u --description 'Select records with the given audit ID'
complete -c auditreduce -s v --description 'Invert sense of matching, to select records t... [See Man Page]'

