# authopen: Darwin man parser
# Autogenerated from man pages
complete -c authopen -l stdoutpipe --description 'specifies that STDOUT_FILENO has been dup2()\'... [See Man Page]'
complete -c authopen -s w --description instructs
complete -c authopen -s a --description 'append to'
complete -c authopen -s c --description 'create the file if it doesn\'t exist'
complete -c authopen -s m --description 'specify the mode bits if a file is created'
complete -c authopen -s o --description 'numerically specify the flags that should be ... [See Man Page]'
complete -c authopen -s x --description 'require that the file being created not exist... [See Man Page]'

