# autoreconf: Deroffing man parser
# Autogenerated from man pages
complete -c autoreconf -s h -l help --description 'print this help, then exit'
complete -c autoreconf -s V -l version --description 'print version number, then exit'
complete -c autoreconf -s v -l verbose --description 'verbosely report processing'
complete -c autoreconf -s d -l debug --description 'don\'t remove temporary files'
complete -c autoreconf -s f -l force --description 'consider all files obsolete'
complete -c autoreconf -s i -l install --description 'copy missing auxiliary files'
complete -c autoreconf -l no-recursive --description 'don\'t rebuild sub-packages'
complete -c autoreconf -s s -l symlink --description 'with -i, install symbolic links instead of co... [See Man Page]'
complete -c autoreconf -s m -l make --description 'when applicable, re-run '
complete -c autoreconf -s W -l warnings --description 'report the warnings falling in CATEGORY [synt... [See Man Page]'
complete -c autoreconf -s B -l prepend-include --description 'prepend directory DIR to search path'
complete -c autoreconf -s I -l include --description 'append directory DIR to search path'

