# autoconf: Deroffing man parser
# Autogenerated from man pages
complete -c autoconf -s h -l help --description 'print this help, then exit'
complete -c autoconf -s V -l version --description 'print version number, then exit'
complete -c autoconf -s v -l verbose --description 'verbosely report processing'
complete -c autoconf -s d -l debug --description 'don\'t remove temporary files'
complete -c autoconf -s f -l force --description 'consider all files obsolete'
complete -c autoconf -s o -l output --description 'save output in FILE (stdout is the default)'
complete -c autoconf -s W -l warnings --description 'report the warnings falling in CATEGORY [synt... [See Man Page]'
complete -c autoconf -s B -l prepend-include --description 'prepend directory DIR to search path'
complete -c autoconf -s I -l include --description 'append directory DIR to search path '
complete -c autoconf -s t -l trace --description 'report the list of calls to MACRO'
complete -c autoconf -s i -l initialization --description 'also trace Autoconf\'s initialization process'

