# automator: Darwin man parser
# Autogenerated from man pages
complete -c automator -s D --description 'Set variable'
complete -c automator -s i --description 'Set '
complete -c automator -s v --description 'Run in verbose mode'

