# auvaltool: Darwin man parser
# Autogenerated from man pages
complete -c auvaltool -s h --description 'print help text'
complete -c auvaltool -s a --description 'lists all available AudioUnits of any type'
complete -c auvaltool -s s --description 'lists all available AudioUnits of type \'TYPE\''
complete -c auvaltool -s v --description 'opens the AudioUnit specified by the TYPE SUB... [See Man Page]'
complete -c auvaltool -l vt --description 'iterates through all of the AU\'s of specified... [See Man Page]'
complete -c auvaltool -l de --description 'execution is terminated when first error is e... [See Man Page]'
complete -c auvaltool -l dw --description 'execution is terminated when first warning is... [See Man Page]'
complete -c auvaltool -s c --description 'continue validating when an error occurs in b... [See Man Page]'
complete -c auvaltool -s q --description 'quiet - does no printing except for errors or... [See Man Page]'
complete -c auvaltool -l qp --description 'doesn\'t print parameter or Factory Presets in... [See Man Page]'
complete -c auvaltool -s o --description 'only runs a basic open and initialize test'
complete -c auvaltool -s r --description 'repeat the whole process of validation N time... [See Man Page]'
complete -c auvaltool -s w --description 'wait after finished - good for profiling memo... [See Man Page]'
complete -c auvaltool -l vers --description 'The version is printed to stdout'
complete -c auvaltool -l versh --description 'The version is printed to stdout in hexadecim... [See Man Page]'
complete -c auvaltool -s f --description 'Each line in the file should contain one comp... [See Man Page]'

