# bc: Deroffing man parser
# Autogenerated from man pages
complete -c bc -s h -l help --description 'Print the usage and exit'
complete -c bc -s i -l interactive --description 'Force interactive mode'
complete -c bc -s l -l mathlib --description 'Define the standard math library'
complete -c bc -s w -l warn --description 'Give warnings for extensions to POSIX bc'
complete -c bc -s s -l standard --description 'Process exactly the POSIX bc language'
complete -c bc -s q -l quiet --description 'Do not print the normal GNU bc welcome'
complete -c bc -s v -l version --description 'Print the version number and copyright and qu... [See Man Page]'

