# bmp2tiff: Deroffing man parser
# Autogenerated from man pages
complete -c bmp2tiff -s c --description 'Specify a compression scheme to use when writ... [See Man Page]'
complete -c bmp2tiff -s r --description 'Write data with a specified number of rows pe... [See Man Page]'

