# bsqlodbc: Deroffing man parser
# Autogenerated from man pages
complete -c bsqlodbc -s U --description 'Database server login name'
complete -c bsqlodbc -s P --description 'Database server password'
complete -c bsqlodbc -s S --description 'Database server to which to connect'
complete -c bsqlodbc -s D --description 'Database to use'
complete -c bsqlodbc -s i --description 'Name of script file, containing SQL'
complete -c bsqlodbc -s o --description 'Name of output file, holding result data'
complete -c bsqlodbc -s e --description 'Name of file for errors'
complete -c bsqlodbc -s t --description 'Specifies the field terminator'
complete -c bsqlodbc -s h --description 'Print column headers with the data to the sam... [See Man Page]'
complete -c bsqlodbc -s q --description 'Do not print column metadata, return status, ... [See Man Page]'
complete -c bsqlodbc -s v --description 'Verbose mode, for more information about the ... [See Man Page]'

