# bsqldb: Deroffing man parser
# Autogenerated from man pages
complete -c bsqldb -s U --description 'Database server login name'
complete -c bsqldb -s P --description 'Database server password'
complete -c bsqldb -s D --description 'Database to use'
complete -c bsqldb -s i --description 'Name of script file, containing SQL'
complete -c bsqldb -s o --description 'Name of output file, holding result data'
complete -c bsqldb -s e --description 'Name of file for errors'
complete -c bsqldb -s t --description 'Specifies the field terminator'
complete -c bsqldb -s h --description 'Print column headers with the data to the sam... [See Man Page]'
complete -c bsqldb -s H --description 'hostname Override name of client sent to serv... [See Man Page]'
complete -c bsqldb -s q --description 'Do not print column metadata, return status, ... [See Man Page]'
complete -c bsqldb -s S
complete -c bsqldb -s v --description 'Verbose mode, for more information about the ... [See Man Page]'

