# BuildStrings: Darwin man parser
# Autogenerated from man pages
complete -c BuildStrings -l header --description 'Generate a header file'
complete -c BuildStrings -l define --description 'Defines variable for use in #ifdef or #ifndef... [See Man Page]'
complete -c BuildStrings -l id --description 'The resource ID for the STR# resource'
complete -c BuildStrings -l attributes --description 'Resource attributes for the STR# resource def... [See Man Page]'
complete -c BuildStrings -l type --description 'Customizes three preprocessor variables (MinV... [See Man Page]'
complete -c BuildStrings -l in --description 'The input file, a set of newline-separated pa... [See Man Page]'
complete -c BuildStrings -l out --description 'The output file'

