# bzip2: Deroffing man parser
# Autogenerated from man pages
complete -c bzip2 -s c -l stdout --description 'Compress or decompress to standard output'
complete -c bzip2 -s d -l decompress --description 'Force decompression'
complete -c bzip2 -s z -l compress --description 'The complement to -d: forces compression, reg... [See Man Page]'
complete -c bzip2 -s t -l test --description 'Check integrity of the specified file(s), but... [See Man Page]'
complete -c bzip2 -s f -l force --description 'Force overwrite of output files'
complete -c bzip2 -s k -l keep --description 'Keep (don\'t delete) input files during compre... [See Man Page]'
complete -c bzip2 -s s -l small --description 'Reduce memory usage, for compression, decompr... [See Man Page]'
complete -c bzip2 -s q -l quiet --description 'Suppress non-essential warning messages'
complete -c bzip2 -s v -l verbose --description 'Verbose mode -- show the compression ratio fo... [See Man Page]'
complete -c bzip2 -s L -l license -s V -l version --description 'Display the software version, license terms a... [See Man Page]'
complete -c bzip2 -s 1 -l 'fast)' -s 9 -l 'best)' --description 'Set the block size to 100 k, 200 k '
complete -c bzip2 -l repetitive-fast -l repetitive-best --description 'These flags are redundant in versions 0'
complete -c bzip2 -o vvvv

