# c99: Darwin man parser
# Autogenerated from man pages
complete -c c99 -s c --description 'Suppress the link-edit phase of the compilati... [See Man Page]'
complete -c c99 -s D --description 'Define name as if by a C-language'
complete -c c99 -s E --description 'Copy C-language source files to the standard ... [See Man Page]'
complete -c c99 -s g --description 'Produce symbolic information in the object or... [See Man Page]'
complete -c c99 -s I --description 'Change the algorithm for searching for header... [See Man Page]'
complete -c c99 -s L --description 'Change the algorithm of searching for the lib... [See Man Page]'
complete -c c99 -s o --description 'Use the pathname'
complete -c c99 -s O --description If
complete -c c99 -s s --description 'Produce object and/or executable files from w... [See Man Page]'
complete -c c99 -s U --description 'Remove any initial definition of'
complete -c c99 -s W --description 'Set the pointer size for the compiled code to... [See Man Page]'
complete -c c99 -s l --description 'Search the library named'

