# cal: Darwin man parser
# Autogenerated from man pages
complete -c cal -s J --description 'Display Julian Calendar, if combined with the... [See Man Page]'
complete -c cal -s e --description 'Display date of easter (for western churches)... [See Man Page]'
complete -c cal -s j --description 'Display Julian days (days one-based, numbered... [See Man Page]'
complete -c cal -s m --description 'Display the specified'
complete -c cal -s o --description 'Display date of orthodox easter (Greek and Ru... [See Man Page]'
complete -c cal -s p --description 'Print the country codes and switching days fr... [See Man Page]'
complete -c cal -s s --description 'Assume the switch from Julian to Gregorian Ca... [See Man Page]'
complete -c cal -s w --description 'Print the number of the week below each week ... [See Man Page]'
complete -c cal -s y --description 'Display a calendar for the specified year'

