# calendar: Darwin man parser
# Autogenerated from man pages
complete -c calendar -s A --description 'Print lines from today and the next'
complete -c calendar -s a --description 'Process the ``calendar\'\' files of all users a... [See Man Page]'
complete -c calendar -s B --description 'Print lines from today and the previous'
complete -c calendar -s F --description 'Specify which day of the week is ``Friday\'\' (... [See Man Page]'
complete -c calendar -s f --description Use
complete -c calendar -s W --description 'Print lines from today and the next'

