# callgrind_control: Deroffing man parser
# Autogenerated from man pages
complete -c callgrind_control -s h -l help --description 'Show a short description, usage, and summary ... [See Man Page]'
complete -c callgrind_control -l version --description 'Show version of callgrind_control'
complete -c callgrind_control -s l -l long --description 'Show also the working directory, in addition ... [See Man Page]'
complete -c callgrind_control -s s -l stat --description 'Show statistics information about active Call... [See Man Page]'
complete -c callgrind_control -s b -l back --description 'Show stack/back traces of each thread in acti... [See Man Page]'
complete -c callgrind_control -s e --description 'Show the current per-thread, exclusive cost v... [See Man Page]'
complete -c callgrind_control -l 'dump[' --description 'Request the dumping of profile information'
complete -c callgrind_control -s z -l zero --description 'Zero all event counters'
complete -c callgrind_control -s k -l kill --description 'Force a Callgrind run to be terminated'
complete -c callgrind_control -l instr --description 'Switch instrumentation mode on or off'
complete -c callgrind_control -s w --description 'Specify the startup directory of an active Ca... [See Man Page]'
complete -c callgrind_control -l 'instr-atstart.'

