# cap_mkdb: Darwin man parser
# Autogenerated from man pages
complete -c cap_mkdb -s f --description 'Specify a different database basename'
complete -c cap_mkdb -s v --description 'Print out the number of capability records in... [See Man Page]'

