# captoinfo: Deroffing man parser
# Autogenerated from man pages
complete -c captoinfo -s v --description 'print out tracing information on standard err... [See Man Page]'
complete -c captoinfo -s V --description 'print out the version of the program in use o... [See Man Page]'
complete -c captoinfo -s 1 --description 'cause the fields to print out one to a line'
complete -c captoinfo -s w --description 'change the output to width characters'

