# cat: Darwin man parser
# Autogenerated from man pages
complete -c cat -s b --description 'Number the non-blank output lines, starting a... [See Man Page]'
complete -c cat -s e --description 'Display non-printing characters (see the'
complete -c cat -s n --description 'Number the output lines, starting at 1'
complete -c cat -s s --description 'Squeeze multiple adjacent empty lines, causin... [See Man Page]'
complete -c cat -s t --description 'Display non-printing characters (see the'
complete -c cat -s u --description 'Disable output buffering'
complete -c cat -s v --description 'Display non-printing characters so they are v... [See Man Page]'

