# ccmake: Deroffing man parser
# Autogenerated from man pages
complete -c ccmake -s C --description 'Pre-load a script to populate the cache'
complete -c ccmake -s D --description 'Create a cmake cache entry'
complete -c ccmake -s U --description 'Remove matching entries from CMake cache'
complete -c ccmake -s G --description 'Specify a makefile generator'
complete -c ccmake -o Wno-dev --description 'Suppress developer warnings'
complete -c ccmake -o Wdev --description 'Enable developer warnings'
complete -c ccmake -l copyright --description 'Print the CMake copyright and exit'
complete -c ccmake -l help -o help -o usage -s h -s H --description 'Print usage information and exit'
complete -c ccmake -l help-full --description 'Print full help and exit'
complete -c ccmake -l help-html --description 'Print full help in HTML format'
complete -c ccmake -l help-man --description 'Print full help as a UNIX man page and exit'
complete -c ccmake -l version -o version --description 'Show program name/version banner and exit'

