# checknr: Darwin man parser
# Autogenerated from man pages
complete -c checknr -s a --description 'Add additional pairs of macros to the list of... [See Man Page]'
complete -c checknr -s c --description 'Define commands which would otherwise be comp... [See Man Page]'
complete -c checknr -s f --description Request
complete -c checknr -s s --description Ignore

