# chflags: Darwin man parser
# Autogenerated from man pages
complete -c chflags -s f --description 'Do not display a diagnostic message if'
complete -c chflags -s H --description 'If the'
complete -c chflags -s h --description 'If the'
complete -c chflags -s L --description 'If the'
complete -c chflags -s P --description 'If the'
complete -c chflags -s R --description 'Change the file flags for the file hierarchie... [See Man Page]'
complete -c chflags -s v --description Cause

