# chgrp: Darwin man parser
# Autogenerated from man pages
complete -c chgrp -s f --description 'The force option ignores errors, except for u... [See Man Page]'
complete -c chgrp -s H --description 'If the'
complete -c chgrp -s h --description 'If the file is a symbolic link, the group ID ... [See Man Page]'
complete -c chgrp -s L --description 'If the'
complete -c chgrp -s P --description 'If the'
complete -c chgrp -s R --description 'Change the group ID for the file hierarchies ... [See Man Page]'
complete -c chgrp -s v --description Cause

