# chpass: Darwin man parser
# Autogenerated from man pages
complete -c chpass -s l --description 'If not specified,'
complete -c chpass -s u --description 'The user name to use when authenticating to t... [See Man Page]'
complete -c chpass -s s --description 'Attempt to change the user\'s shell to'

