# cmakemodules: Deroffing man parser
# Autogenerated from man pages
complete -c cmakemodules -l ------------------
complete -c cmakemodules -l ------------------------------------------------- --description 'This convenience include finds if wxWindows i... [See Man Page]'

