# codesign_allocate: Deroffing man parser
# Autogenerated from man pages
complete -c codesign_allocate -s i --description 'specifies the input file as  oldfile'
complete -c codesign_allocate -s o --description 'specifies the output file as  newfile'
complete -c codesign_allocate -s a --description 'specifies for the architecture  arch that the... [See Man Page]'

