# col: Darwin man parser
# Autogenerated from man pages
complete -c col -s b --description 'Do not output any backspaces, printing only t... [See Man Page]'
complete -c col -s f --description 'Forward half line feeds are permitted (``fine... [See Man Page]'
complete -c col -s h --description 'Do not output multiple spaces instead of tabs... [See Man Page]'
complete -c col -s l --description 'Buffer at least'
complete -c col -s p --description 'Force unknown control sequences to be passed ... [See Man Page]'
complete -c col -s x --description 'Output multiple spaces instead of tabs'

