# colcrt: Darwin man parser
# Autogenerated from man pages
complete -c colcrt -l Fl --description 'Suppress all underlining'
complete -c colcrt -s 2 --description 'Cause all half-lines to be printed, effective... [See Man Page]'

