# column: Darwin man parser
# Autogenerated from man pages
complete -c column -s c --description 'Output is formatted for a display'
complete -c column -s s --description 'Specify a set of characters to be used to del... [See Man Page]'
complete -c column -s t --description 'Determine the number of columns the input con... [See Man Page]'
complete -c column -s x --description 'Fill columns before filling rows'

