# comm: Darwin man parser
# Autogenerated from man pages
complete -c comm -s 1 --description 'Suppress printing of column 1'
complete -c comm -s 2 --description 'Suppress printing of column 2'
complete -c comm -s 3 --description 'Suppress printing of column 3'
complete -c comm -s i --description 'Case insensitive comparison of lines'

