# compileHelp: Darwin man parser
# Autogenerated from man pages
complete -c compileHelp -l f --description 'Force the output file to be created, even wit... [See Man Page]'
complete -c compileHelp -l m --description 'Merge the contents of \\fIHELPFILE\\fR'
complete -c compileHelp -l o --description 'Write output to \\fIFILE\\fR'
complete -c compileHelp -l help --description 'Print usage message'

