# compress: Darwin man parser
# Autogenerated from man pages
complete -c compress -s b --description 'The code size (see below) is limited to'
complete -c compress -s c --description 'Compressed or uncompressed output is written ... [See Man Page]'
complete -c compress -s f --description 'Files are overwritten without prompting for c... [See Man Page]'
complete -c compress -s v --description 'Print the percentage reduction of each file'

