# corelist: Type1
# Autogenerated from man pages
complete -c corelist -s a --description 'lists all versions of the given module (or th... [See Man Page]'
complete -c corelist -s d --description 'finds the first perl version where a module h... [See Man Page]'
complete -c corelist -s '?' -o help --description 'help! help! help! to see more help, try --man... [See Man Page]'
complete -c corelist -o man --description 'all of the help'

