# cp: Darwin man parser
# Autogenerated from man pages
complete -c cp -s a --description 'Same as '
complete -c cp -s f
complete -c cp -s H --description 'If the'
complete -c cp -s i --description Cause
complete -c cp -s L --description 'If the'
complete -c cp -s n --description 'Do not overwrite an existing file'
complete -c cp -s P --description 'If the'
complete -c cp -s p --description Cause
complete -c cp -s R --description If
complete -c cp -s v --description Cause
complete -c cp -s X --description 'Do not copy Extended Attributes (EAs) or reso... [See Man Page]'

