# CpMac: Darwin man parser
# Autogenerated from man pages
complete -c CpMac -s r --description If
complete -c CpMac -s p --description Causes
complete -c CpMac -l mac --description 'Allows use of HFS-style paths for both source... [See Man Page]'

