# createhomedir: Darwin man parser
# Autogenerated from man pages
complete -c createhomedir -s s --description 'creates home directories for server home path... [See Man Page]'
complete -c createhomedir -s c --description 'creates home directories for local home paths... [See Man Page]'
complete -c createhomedir -s b --description 'creates home directories for both server and ... [See Man Page]'
complete -c createhomedir -s a --description 'creates home directories for users defined in... [See Man Page]'
complete -c createhomedir -s l --description 'creates home directories for users defined in... [See Man Page]'
complete -c createhomedir -s n --description 'creates home directories for users defined in... [See Man Page]'
complete -c createhomedir -s u --description 'creates a home directory for a specific user ... [See Man Page]'
complete -c createhomedir -s i --description 'reads username list from standard input and c... [See Man Page]'
complete -c createhomedir -s h --description 'usage help'

