# crontab: Darwin man parser
# Autogenerated from man pages
complete -c crontab -s u --description 'Specify the name of the user whose crontab is... [See Man Page]'
complete -c crontab -s l --description 'Display the current crontab on standard outpu... [See Man Page]'
complete -c crontab -s r --description 'Remove the current crontab'
complete -c crontab -s e --description 'Edit the current crontab using the editor spe... [See Man Page]'

