# cs2cs: Deroffing man parser
# Autogenerated from man pages
complete -c cs2cs -s I --description 'method to specify inverse translation, conver... [See Man Page]'
complete -c cs2cs -s t --description 'A specifies a character employed as the first... [See Man Page]'
complete -c cs2cs -s e --description 'String is an arbitrary string to be output if... [See Man Page]'
complete -c cs2cs -s E --description 'causes the input coordinates to be copied to ... [See Man Page]'
complete -c cs2cs -s l --description 'List projection identifiers with  -l,  -lp or... [See Man Page]'
complete -c cs2cs -s r --description 'This options reverses the order of the expect... [See Man Page]'
complete -c cs2cs -s s --description 'This options reverses the order of the output... [See Man Page]'
complete -c cs2cs -s f --description 'Format is a  printf format string to control ... [See Man Page]'
complete -c cs2cs -o '[w' --description 'N is the number of significant fractional dig... [See Man Page]'
complete -c cs2cs -s b
complete -c cs2cs -s i --description or
complete -c cs2cs -s o --description 'options are employed, an error is returned as... [See Man Page]'
complete -c cs2cs -o lp --description or
complete -c cs2cs -o lP --description 'that can be selected with +proj'
complete -c cs2cs -o le --description 'that can be selected with +ellps,'
complete -c cs2cs -o lu --description 'list of cartesian to meter conversion factors... [See Man Page]'
complete -c cs2cs -o ld --description 'list of datums that can be selected with  +da... [See Man Page]'
complete -c cs2cs -o w3 --description 'is assumed)'
complete -c cs2cs -s W --description 'is employed the fields will be constant width... [See Man Page]'
complete -c cs2cs -s v --description 'causes a listing of cartographic control para... [See Man Page]'
complete -c cs2cs -s w --description 'switch is not employed) and precise to 0'

