# csplit: Darwin man parser
# Autogenerated from man pages
complete -c csplit -s f --description 'Give created files names beginning with'
complete -c csplit -s k --description 'Do not remove output files if an error occurs... [See Man Page]'
complete -c csplit -s n --description Use
complete -c csplit -s s --description 'Do not write the size of each output file to ... [See Man Page]'

