# csreq: Darwin man parser
# Autogenerated from man pages
complete -c csreq -s b --description 'Requests that the requirement read be written... [See Man Page]'
complete -c csreq -s r --description 'Specifies the input requirement'
complete -c csreq -s t --description 'Requests that the requirement read be written... [See Man Page]'
complete -c csreq -s v --description 'Increases the verbosity of output'

