# ctags: Darwin man parser
# Autogenerated from man pages
complete -c ctags -s d --description 'create tags for'
complete -c ctags -s t --description 'create tags for typedefs, structs, unions, an... [See Man Page]'
complete -c ctags -s v --description 'An index of the form expected by'

