# cupstestppd: Deroffing man parser
# Autogenerated from man pages
complete -c cupstestppd -s I
complete -c cupstestppd -s R
complete -c cupstestppd -s W
complete -c cupstestppd -s q
complete -c cupstestppd -s r
complete -c cupstestppd -s v
complete -c cupstestppd -o vv

