# cups-config: Deroffing man parser
# Autogenerated from man pages
complete -c cups-config -l api-version
complete -c cups-config -l build
complete -c cups-config -l cflags
complete -c cups-config -l datadir
complete -c cups-config -l help
complete -c cups-config -l image
complete -c cups-config -l ldflags
complete -c cups-config -l libs
complete -c cups-config -l serverbin
complete -c cups-config -l serverroot
complete -c cups-config -l static
complete -c cups-config -l version

