# cut: Darwin man parser
# Autogenerated from man pages
complete -c cut -s b --description The
complete -c cut -s c --description The
complete -c cut -s d --description Use
complete -c cut -s f --description The
complete -c cut -s n --description 'Do not split multi-byte characters'
complete -c cut -s s --description 'Suppress lines with no field delimiter charac... [See Man Page]'

