# dappprof: Deroffing man parser
# Autogenerated from man pages
complete -c dappprof -s a --description 'print all data'
complete -c dappprof -s c --description 'print function counts'
complete -c dappprof -s e --description 'print elapsed times, ns'
complete -c dappprof -s o --description 'print CPU times, ns'
complete -c dappprof -s T --description 'print totals'
complete -c dappprof -s p --description 'examine this PID'
complete -c dappprof -s u --description 'trace this library instead'
complete -c dappprof -s U --description 'trace all library and user functions'
complete -c dappprof -o ceo -s h
complete -c dappprof -o ap

