# dapptrace: Deroffing man parser
# Autogenerated from man pages
complete -c dapptrace -s a --description 'print all details'
complete -c dapptrace -s b --description 'dynamic variable buffer size'
complete -c dapptrace -s c --description 'print function call counts'
complete -c dapptrace -s d --description 'print relative timestamps, us'
complete -c dapptrace -s e --description 'print elapsed times, us'
complete -c dapptrace -s F --description 'print flow indentation'
complete -c dapptrace -s l --description 'force printing of pid/lwpid per line'
complete -c dapptrace -s o --description 'print on-cpu times, us'
complete -c dapptrace -s p --description 'examine this PID'
complete -c dapptrace -s u --description 'trace this library instead'
complete -c dapptrace -s U --description 'trace all library and user functions'
complete -c dapptrace -o Fp --description 'print elapsed and CPU times, # dapptrace'
complete -c dapptrace -o eop

