# datacopy: Deroffing man parser
# Autogenerated from man pages
complete -c datacopy -s t --description 'Truncate target table before loading data'
complete -c datacopy -s a --description 'Append data to target table'
complete -c datacopy -s c --description 'Create the target table with the same schema ... [See Man Page]'
complete -c datacopy -s b --description 'The number of rows per batch of data copied'
complete -c datacopy -s p --description 'The number of bytes, per network packet, sent... [See Man Page]'
complete -c datacopy -s v --description 'Produce verbose output, including diagnostic ... [See Man Page]'
complete -c datacopy -s d --description 'Produce freetds TDSDUMP output'
complete -c datacopy -s S --description 'The connection information for the source ser... [See Man Page]'
complete -c datacopy -s D --description 'The connection information for the destinatio... [See Man Page]'

