# date: Darwin man parser
# Autogenerated from man pages
complete -c date -s d --description 'Set the kernel\'s value for daylight saving ti... [See Man Page]'
complete -c date -s f --description Use
complete -c date -s j --description 'Do not try to set the date'
complete -c date -s n --description 'By default, if the'
complete -c date -s r --description 'Print the date and time represented by'
complete -c date -s t --description 'Set the system\'s value for minutes west of'
complete -c date -s u --description 'Display or set the date in'
complete -c date -s v --description 'Adjust (i'

