# dbiprof: Type1
# Autogenerated from man pages
complete -c dbiprof -l number --description 'Produce this many items in the report'
complete -c dbiprof -l sort --description 'Sort results by the given field'
complete -c dbiprof -l reverse --description 'Reverses the selected sort'
complete -c dbiprof -l match --description 'Consider only items where the specified key m... [See Man Page]'
complete -c dbiprof -l exclude --description 'Remove items for where the specified key matc... [See Man Page]'
complete -c dbiprof -l case-sensitive --description 'Using this option causes --match and --exclud... [See Man Page]'
complete -c dbiprof -l delete --description 'Sets the \\f(CW\\*(C`DeleteFiles\\*(C\' option to... [See Man Page]'
complete -c dbiprof -l dumpnodes --description 'Print the list of nodes in the form of a perl... [See Man Page]'

