# dc: Deroffing man parser
# Autogenerated from man pages
complete -c dc -l version --description 'Print out the version of \\*(dc that is being ... [See Man Page]'
complete -c dc -l help --description 'Print a usage message briefly summarizing the... [See Man Page]'
complete -c dc -l expression --description 'Add the commands in  script to the set of com... [See Man Page]'
complete -c dc -s V
complete -c dc -s h
complete -c dc -s e
complete -c dc -s f
complete -c dc -l file --description 'Add the commands contained in the file script... [See Man Page]'

