# defaults: Darwin man parser
# Autogenerated from man pages
complete -c defaults -l app --description 'The name of an application may be provided in... [See Man Page]'
complete -c defaults -s g --description 'Specify the global domain'
complete -c defaults -l string --description 'Allows the user to specify a string as the va... [See Man Page]'
complete -c defaults -l data --description 'Allows the user to specify a bunch of raw dat... [See Man Page]'
complete -c defaults -l 'int[eger]' --description 'Allows the user to specify an integer as the ... [See Man Page]'
complete -c defaults -l float --description 'Allows the user to specify a floating point n... [See Man Page]'
complete -c defaults -l 'bool[ean]' --description 'Allows the user to specify a boolean as the v... [See Man Page]'
complete -c defaults -l date --description 'Allows the user to specify a date as the valu... [See Man Page]'
complete -c defaults -l array --description 'Allows the user to specify an array as the va... [See Man Page]'
complete -c defaults -l array-add --description 'Allows the user to add new elements to the en... [See Man Page]'
complete -c defaults -l dict --description 'Allows the user to add a dictionary to the de... [See Man Page]'
complete -c defaults -l dict-add --description 'Allows the user to add new key/value pairs to... [See Man Page]'
complete -c defaults -l currentHost --description 'Restricts preferences operations to the host ... [See Man Page]'
complete -c defaults -l host --description 'Restricts preferences operations to \\fIhostna... [See Man Page]'

