# defncopy: Deroffing man parser
# Autogenerated from man pages
complete -c defncopy -s U --description 'database server login name'
complete -c defncopy -s P --description 'database server password'
complete -c defncopy -s S --description 'database server to which to connect'
complete -c defncopy -s D --description 'database to use'
complete -c defncopy -s i --description 'a script to apply to the database'
complete -c defncopy -s o --description 'a file to hold the script, defaults to standa... [See Man Page]'
complete -c defncopy -s v --description 'Show version information and copyright notice... [See Man Page]'

