# DeRez: Deroffing man parser
# Autogenerated from man pages
complete -c DeRez -o 'c[ompatible]' --description 'Generates output that is backward-compatible ... [See Man Page]'
complete -c DeRez -o 'd[efine]' --description 'Defines the macro variable   macro  as having... [See Man Page]'
complete -c DeRez -o 'e[scape]' --description 'Prints characters that are normally escaped, ... [See Man Page]'
complete -c DeRez -s i --description 'Specifies the directory to search for   #incl... [See Man Page]'
complete -c DeRez -o 'is[ysroot]' --description 'Specifies the system SDK in which to search f... [See Man Page]'
complete -c DeRez -o 'm[axstringsize]' --description 'Sets the maximum output string width to   n, ... [See Man Page]'
complete -c DeRez -o noResolve --description 'Suppresses leaf alias resolution of the file ... [See Man Page]'
complete -c DeRez -o only --description 'Reads only resources of the type indicated by... [See Man Page]'
complete -c DeRez -s p --description 'Writes progress and summary information to st... [See Man Page]'
complete -c DeRez -o rd --description 'Suppresses warning messages emitted when a re... [See Man Page]'
complete -c DeRez -o script --description 'Enables the recognition of any of several 2-b... [See Man Page]'
complete -c DeRez -o 's[kip]' --description 'Skips resources of the type indicated by   ty... [See Man Page]'
complete -c DeRez -o skip
complete -c DeRez -o 'u[ndef]' --description 'Undefines the preset macro variable  macro'
complete -c DeRez -o useDF --description 'Reads and writes resource information from th... [See Man Page]'

