# df: Darwin man parser
# Autogenerated from man pages
complete -c df -s a --description 'Show all mount points, including those that w... [See Man Page]'
complete -c df -s b --description 'Use (the default) 512-byte blocks'
complete -c df -s g --description 'Use 1073741824-byte (1-Gbyte) blocks rather t... [See Man Page]'
complete -c df -s H --description '"Human-readable" output'
complete -c df -s h --description '"Human-readable" output'
complete -c df -s i --description 'Include statistics on the number of free inod... [See Man Page]'
complete -c df -s k --description 'Use 1024-byte (1-Kbyte) blocks, rather than t... [See Man Page]'
complete -c df -s l --description 'Only display information about locally-mounte... [See Man Page]'
complete -c df -s m --description 'Use 1048576-byte (1-Mbyte) blocks rather than... [See Man Page]'
complete -c df -s n --description 'Print out the previously obtained statistics ... [See Man Page]'
complete -c df -s P --description 'Use (the default) 512-byte blocks'
complete -c df -s T --description 'Only print out statistics for filesystems of ... [See Man Page]'
complete -c df -s t --description 'If used with no arguments,this option is a no... [See Man Page]'

