# diff3: Deroffing man parser
# Autogenerated from man pages
complete -c diff3 -s e -l ed --description 'Output unmerged changes from OLDFILE to YOURF... [See Man Page]'
complete -c diff3 -s E -l show-overlap --description 'Output unmerged changes, bracketing conflicts... [See Man Page]'
complete -c diff3 -s A -l show-all --description 'Output all changes, bracketing conflicts'
complete -c diff3 -s x -l overlap-only --description 'Output overlapping changes'
complete -c diff3 -s X --description 'Output overlapping changes, bracketing them'
complete -c diff3 -s 3 -l easy-only --description 'Output unmerged nonoverlapping changes'
complete -c diff3 -s m -l merge --description 'Output merged file instead of ed script (defa... [See Man Page]'
complete -c diff3 -s L -l label --description 'Use LABEL instead of file name'
complete -c diff3 -s i --description 'Append `w\' and `q\' commands to ed scripts'
complete -c diff3 -s a -l text --description 'Treat all files as text'
complete -c diff3 -s T -l initial-tab --description 'Make tabs line up by prepending a tab'
complete -c diff3 -l diff-program --description 'Use PROGRAM to compare files'
complete -c diff3 -s v -l version --description 'Output version info'
complete -c diff3 -l help --description 'Output this help'

