# dig: Deroffing man parser
# Autogenerated from man pages
complete -c dig -s h --description 'option is given'
complete -c dig -s t --description and
complete -c dig -s c --description 'options to specify the type and class, use th... [See Man Page]'
complete -c dig -s q --description 'the specify the domain name, or use "IN'
complete -c dig -s b --description 'option sets the source IP address of the quer... [See Man Page]'
complete -c dig -s f --description 'option makes dig  operate in batch mode by re... [See Man Page]'
complete -c dig -s m --description 'option enables memory usage debugging'
complete -c dig -s p --description 'option is used'
complete -c dig -s 4 --description 'option forces dig to only use IPv4 query tran... [See Man Page]'
complete -c dig -s 6 --description 'option forces dig to only use IPv6 query tran... [See Man Page]'
complete -c dig -s x --description 'option is supplied to indicate a reverse look... [See Man Page]'
complete -c dig -s i --description option
complete -c dig -s k --description option
complete -c dig -s y --description 'option; hmac is the type of the TSIG, default... [See Man Page]'

