# distcc: Deroffing man parser
# Autogenerated from man pages
complete -c distcc -s j --description 'option, which runs several compiler processes... [See Man Page]'
complete -c distcc -l localslots_cpp --description 'parameter is by default set to 16'
complete -c distcc -o j80 --description 'or larger may be appropriate even for single-... [See Man Page]'
complete -c distcc -l allow --description 'options to restrict access'
complete -c distcc -l randomize --description 'option enforces a uniform usage of compile se... [See Man Page]'
complete -c distcc -l help --description 'Displays summary instructions'
complete -c distcc -l version --description 'Displays the distcc client version'
complete -c distcc -l show-hosts --description 'Displays the host list that distcc would use'
complete -c distcc -l scan-includes --description 'Displays the list of files that distcc would ... [See Man Page]'
complete -c distcc -s c --description 'use distcc for only some compilations or to t... [See Man Page]'
complete -c distcc -l localslots --description and
complete -c distcc -l verbose --description 'option on the server'
complete -c distcc -l program-suffix --description 'options to cause it to be installed with a na... [See Man Page]'

