# doxytag: Deroffing man parser
# Autogenerated from man pages
complete -c doxytag -s t --description 'Generate tag file <tag_file>'
complete -c doxytag -s s --description 'Generate search index <index_file>'

