# dscacheutil: Darwin man parser
# Autogenerated from man pages
complete -c dscacheutil -s h --description 'Lists the options for calling'
complete -c dscacheutil -s q --description 'Initiate a query using standard calls'
complete -c dscacheutil -s a --description 'Optional flag to '
complete -c dscacheutil -l cachedump --description 'Dumps an overview of the cache by default'
complete -c dscacheutil -l buckets --description 'Used in conjunction with'
complete -c dscacheutil -l entries --description 'Used in conjunction with'
complete -c dscacheutil -l configuration --description 'Prints current configuration information, suc... [See Man Page]'
complete -c dscacheutil -l flushcache --description 'Flushes the entire cache'
complete -c dscacheutil -l statistics --description 'Prints statistics from the cache including an... [See Man Page]'

