# dsexport: Darwin man parser
# Autogenerated from man pages
complete -c dsexport -l -N --description 'Export all attributes, including native attri... [See Man Page]'
complete -c dsexport -s r --description 'Comma-separated list of records to export fro... [See Man Page]'
complete -c dsexport -s e --description 'Comma-separated list of attributes that shoul... [See Man Page]'
complete -c dsexport -s a --description 'Address of the desired proxy machine'
complete -c dsexport -s u --description 'Username to use for the proxy connection'
complete -c dsexport -s p --description 'Password to use for the proxy connection'

