# dsimport: Darwin man parser
# Autogenerated from man pages
complete -c dsimport -l -crypt --description 'is used to signify that all user passwords ar... [See Man Page]'
complete -c dsimport -l -force --description 'forces a specific value for the named attribu... [See Man Page]'
complete -c dsimport -l -groupid --description 'is the GID used for any records that do not s... [See Man Page]'
complete -c dsimport -l -grouppreset --description 'designate a preset record to be applied to im... [See Man Page]'
complete -c dsimport -l -loglevel --description 'changes the amount of logging detail output t... [See Man Page]'
complete -c dsimport -l -outputfile --description 'Outputs a plist to the specified file with a ... [See Man Page]'
complete -c dsimport -l -password --description 'is the admin\'s password for import operations... [See Man Page]'
complete -c dsimport -l -recordformat --description 'passes in the delimiters and attributes and r... [See Man Page]'
complete -c dsimport -l -recordtype --description 'Override the record type defined in the impor... [See Man Page]'
complete -c dsimport -l -remotehost --description 'connects to a remote host at the network addr... [See Man Page]'
complete -c dsimport -l -remoteusername --description 'specifies user name to use for the remote con... [See Man Page]'
complete -c dsimport -l -remotepassword --description 'specifies password to use for the remote conn... [See Man Page]'
complete -c dsimport -l -startid --description 'indicates the ID number to start with when th... [See Man Page]'
complete -c dsimport -l -template --description 'is used for delimited import of files that la... [See Man Page]'
complete -c dsimport -l -username --description 'is the admin username to use when importing r... [See Man Page]'
complete -c dsimport -l -userpreset --description 'designate a preset record to be applied to im... [See Man Page]'

