# dsymutil: Darwin man parser
# Autogenerated from man pages
complete -c dsymutil -l -arch --description 'Link DWARF debug information only for specifi... [See Man Page]'
complete -c dsymutil -l h --description 'Display the help documentation for this comma... [See Man Page]'
complete -c dsymutil -l f --description 'Produce a flat dSYM file'
complete -c dsymutil -l 'o\\' --description 'Specifies an alternate path to place the '
complete -c dsymutil -l -oso-prepend-path --description 'Specifies a path to prepend to all debug symb... [See Man Page]'
complete -c dsymutil -l s --description 'Dumps the symbol table found in executable or... [See Man Page]'
complete -c dsymutil -l 't\\' --description 'Specifies the maximum number (n) of simultane... [See Man Page]'
complete -c dsymutil -l v --description 'Display the current version and build date of... [See Man Page]'
complete -c dsymutil -l -verbose --description 'Display verbose information when linking'
complete -c dsymutil -l u --description 'Update an existing dSYM file to contain the l... [See Man Page]'
complete -c dsymutil -l -minimize --description 'When used when creating a dSYM file, this opt... [See Man Page]'

