# dtruss: Deroffing man parser
# Autogenerated from man pages
complete -c dtruss -s a --description 'print all details'
complete -c dtruss -s b --description 'dynamic variable buffer size'
complete -c dtruss -s c --description 'print system call counts'
complete -c dtruss -s d --description 'print relative timestamps, us'
complete -c dtruss -s e --description 'print elapsed times, us'
complete -c dtruss -s f --description 'follow children as they are forked'
complete -c dtruss -s l --description 'force printing of pid/lwpid per line'
complete -c dtruss -s L --description 'don\'t print pid/lwpid per line'
complete -c dtruss -s n --description 'examine processes with this name'
complete -c dtruss -s o --description 'print on-cpu times, us'
complete -c dtruss -s s --description 'print stack backtraces'
complete -c dtruss -s p --description 'examine this PID'
complete -c dtruss -s t --description 'examine this syscall only'
complete -c dtruss -o eo

