# dyldinfo: Darwin man parser
# Autogenerated from man pages
complete -c dyldinfo -l arch --description 'Only display the specified architecture'
complete -c dyldinfo -l dylibs --description 'Display the table of dylibs on which this ima... [See Man Page]'
complete -c dyldinfo -l rebase --description 'Display the table of rebasing information'
complete -c dyldinfo -l bind --description 'Display the table of binding information'
complete -c dyldinfo -l weak_bind --description 'Display the table of weak binding information... [See Man Page]'
complete -c dyldinfo -l lazy_bind --description 'Display the table of lazy binding information... [See Man Page]'
complete -c dyldinfo -l export --description 'Display the table symbols which this image ex... [See Man Page]'
complete -c dyldinfo -l opcodes --description 'Display the low level opcodes used to encode ... [See Man Page]'
complete -c dyldinfo -l function_starts --description 'Decodes the list of function start addresses'

