# ed: Darwin man parser
# Autogenerated from man pages
complete -c ed -s s --description 'Suppress diagnostics'
complete -c ed -s x --description 'Prompt for an encryption key to be used in su... [See Man Page]'
complete -c ed -s p --description 'Specify a command prompt'

