# efax: Deroffing man parser
# Autogenerated from man pages
complete -c efax -s a --description 'use the command ATcmd when answering the phon... [See Man Page]'
complete -c efax -s c --description 'set the local modem capabilities'
complete -c efax -s d --description 'use the fax modem connected to device dev'
complete -c efax -s f --description 'use font file fnt for generating the header'
complete -c efax -s g --description 'if a CONNECT (or DATA) response indicates a d... [See Man Page]'
complete -c efax -s h --description 'put string `hdr\' at the top of each page'
complete -c efax -s k --description 'send the command ATstr to the modem to initia... [See Man Page]'
complete -c efax -s l --description 'set the local identification string to id'
complete -c efax -s o --description 'use option opt to accommodate a non-standard ... [See Man Page]'
complete -c efax -s q --description 'ask for retransmission of pages received with... [See Man Page]'
complete -c efax -s r --description 'each received fax page is stored in a separat... [See Man Page]'
complete -c efax -s s --description 'remove lock file(s) after initializing the mo... [See Man Page]'
complete -c efax -s t --description 'dial telephone number num and send the fax im... [See Man Page]'
complete -c efax -s v --description 'select types of messages to be printed'
complete -c efax -s w --description 'wait for an OK or CONNECT prompt instead of i... [See Man Page]'
complete -c efax -s i
complete -c efax -s j
complete -c efax -o olll --description '    n ignore requests for pages to be retrans... [See Man Page]'
complete -c efax -s x --description 'use a UUCP-style lock file lkf to lock the mo... [See Man Page]'
complete -c efax -o oh
complete -c efax -o iS0 --description rings
complete -c efax -o i+FCLASS -o oa --description 'option to then hang up and try again in fax m... [See Man Page]'
complete -c efax -o Pfax --description 'mailed to the user when the fax is sent'
complete -c efax -o or

