# encode_keychange: Deroffing man parser
# Autogenerated from man pages
complete -c encode_keychange -s E --description '<engineID> is intepreted as a hex string when... [See Man Page]'
complete -c encode_keychange -s f --description 'Force passphrases to be read from standard in... [See Man Page]'
complete -c encode_keychange -s h --description 'Display the help message'
complete -c encode_keychange -s N --description 'Passphrase used to generate the new Ku'
complete -c encode_keychange -s O --description 'Passphrase used to generate the old Ku'
complete -c encode_keychange -s P --description 'Turn off the prompt for passphrases when gett... [See Man Page]'
complete -c encode_keychange -s v --description 'Be verbose'
complete -c encode_keychange -s V --description 'Echo passphrases to terminal'

