# eqn: Deroffing man parser
# Autogenerated from man pages
complete -c eqn -s d --description 'Specify delimiters  x and\\~\\c  y for the left... [See Man Page]'
complete -c eqn -s C --description 'Recognize  '
complete -c eqn -s N --description 'Don\'t allow newlines within delimiters'
complete -c eqn -s v --description 'Print the version number'
complete -c eqn -s r --description 'Only one size reduction'
complete -c eqn -s m --description 'The minimum point-size is\\~\\c R n '
complete -c eqn -s T --description 'The output is for device R name '
complete -c eqn -s M --description 'Search  dir for  eqnrc before the default dir... [See Man Page]'
complete -c eqn -s R --description 'Don\'t load  eqnrc '
complete -c eqn -s f --description 'This is equivalent to a  gfont F command'
complete -c eqn -s s --description 'This is equivalent to a  gsize n command'
complete -c eqn -s e --description 'opsion of groff '
complete -c eqn -s p --description 'This says shas subscripss and superscripss sh... [See Man Page]'

