# eqn2graph: Deroffing man parser
# Autogenerated from man pages
complete -c eqn2graph -o unsafe --description 'Run   groff (1) in the `unsafe\' mode enabling... [See Man Page]'
complete -c eqn2graph -o format --description 'Specify an output format; the default is PNG ... [See Man Page]'

