# erb: Darwin man parser
# Autogenerated from man pages
complete -c erb -l -version --description 'Prints the version of'
complete -c erb -s E
complete -c erb -l -encoding --description 'Specifies the default value(s) for external e... [See Man Page]'
complete -c erb -s P --description 'Evaluates lines starting with'
complete -c erb -s S --description 'Specifies the safe level in which eRuby scrip... [See Man Page]'
complete -c erb -s T --description 'Specifies trim mode (default 0)'
complete -c erb -s U --description 'can be one ofSets the default value for inter... [See Man Page]'
complete -c erb -s d
complete -c erb -l -debug --description 'Turns on debug mode'
complete -c erb -s h
complete -c erb -l -help --description 'Prints a summary of the options'
complete -c erb -s n --description 'Used with'
complete -c erb -s v --description 'Enables verbose mode'
complete -c erb -s x --description 'Converts the eRuby script into Ruby script an... [See Man Page]'

