# errinfo: Deroffing man parser
# Autogenerated from man pages
complete -c errinfo -s c --description 'counts - print an aggregate style report cont... [See Man Page]'
complete -c errinfo -s p --description 'examine this PID only'
complete -c errinfo -s n --description 'examine processes with ths name only (eg, "ls... [See Man Page]'

