# execsnoop: Deroffing man parser
# Autogenerated from man pages
complete -c execsnoop -s a --description 'print all data'
complete -c execsnoop -s A --description 'dump all data, space delimited'
complete -c execsnoop -s e --description 'safe output, parseable'
complete -c execsnoop -s j --description 'print project ID'
complete -c execsnoop -s s --description 'print start time, us'
complete -c execsnoop -s v --description 'print start time, string'
complete -c execsnoop -s Z --description 'print zonename'
complete -c execsnoop -s c --description 'command name to snoop EXAMPLES'
complete -c execsnoop -s f

