# extcheck: Deroffing man parser
# Autogenerated from man pages
complete -c extcheck -o verbose --description 'Lists  jar files in the extension directory a... [See Man Page]'
complete -c extcheck -s J --description 'Pass option to the Java virtual machine, wher... [See Man Page]'
complete -c extcheck -o J-Xms48m --description 'sets the startup memory to 48 megabytes'

