# fax: Deroffing man parser
# Autogenerated from man pages
complete -c fax -s l --description 'use low (96 line per inch) resolution'
complete -c fax -s v --description 'display verbose messages for debugging'
complete -c fax -s m --description 'the phone call has already been dialed manual... [See Man Page]'

