# fax2ps: Deroffing man parser
# Autogenerated from man pages
complete -c fax2ps -s p --description 'Print only the indicated page'
complete -c fax2ps -s x --description 'Use  resolution as the horizontal resolution,... [See Man Page]'
complete -c fax2ps -s y --description 'Use  resolution as the vertical resolution, i... [See Man Page]'
complete -c fax2ps -s S --description 'Scale each page of image data to fill the out... [See Man Page]'
complete -c fax2ps -s W --description 'Use  width as the width, in inches, of the ou... [See Man Page]'
complete -c fax2ps -s H --description options

