# file: Darwin man parser
# Autogenerated from man pages
complete -c file -s b --description 'Do not prepend filenames to output lines (bri... [See Man Page]'
complete -c file -s C --description 'Write a'
complete -c file -s c --description 'Cause a checking printout of the parsed form ... [See Man Page]'
complete -c file -s d --description 'Apply the default system tests; this is the d... [See Man Page]'
complete -c file -s D --description 'Print debugging messages'
complete -c file -s e --description 'Exclude the test named in'
complete -c file -s F --description 'Use the specified string as the separator bet... [See Man Page]'
complete -c file -s f --description 'Read the names of the files to be examined fr... [See Man Page]'
complete -c file -s h --description 'option causes symlinks not to be followed(on ... [See Man Page]'
complete -c file -s i --description 'If the file is a regular file, do not classif... [See Man Page]'
complete -c file -s I --description 'Causes the file command to output mime type s... [See Man Page]'
complete -c file -l -mime-type --description Like
complete -c file -s k --description 'Don\'t stop at the first match, keep going'
complete -c file -s L --description 'option causes symlinks to be followed, as the... [See Man Page]'
complete -c file -s m --description 'Specify an alternate list of files and direct... [See Man Page]'
complete -c file -s M --description Like
complete -c file -s n --description 'Force stdout to be flushed after checking eac... [See Man Page]'
complete -c file -s p --description 'On systems that support'
complete -c file -s r --description 'No operation, included for historical compati... [See Man Page]'
complete -c file -s s --description 'Normally,'
complete -c file -s v --description 'Print the version of the program and exit'
complete -c file -s z --description 'Try to look inside compressed files'
complete -c file -s 0 --description 'Output a null character'
complete -c file -l -help --description 'Print a help message and exit'

