# filtercalltree: Darwin man parser
# Autogenerated from man pages
complete -c filtercalltree -l invertCallTree --description 'Print the call tree from hottest to coldest s... [See Man Page]'
complete -c filtercalltree -l pruneCount --description 'Remove branches of the call tree that have co... [See Man Page]'
complete -c filtercalltree -l pruneMallocSize --description 'Remove branches of the call tree that have ma... [See Man Page]'
complete -c filtercalltree -l chargeSystemLibraries --description 'Remove stack frames from all libraries in /Sy... [See Man Page]'
complete -c filtercalltree -l chargeLibrary --description 'Remove stack frames from'
complete -c filtercalltree -l keepBoundaries --description 'When charging libraries to callers, keep the ... [See Man Page]'

