# find: Darwin man parser
# Autogenerated from man pages
complete -c find -s E --description 'Interpret regular expressions followed by'
complete -c find -s H --description 'Cause the file information and file type (see... [See Man Page]'
complete -c find -s L --description 'Cause the file information and file type (see... [See Man Page]'
complete -c find -s P --description 'Cause the file information and file type (see... [See Man Page]'
complete -c find -s X --description Permit
complete -c find -s d --description Cause
complete -c find -s f --description 'Specify a file hierarchy for'
complete -c find -s s --description Cause
complete -c find -s x --description Prevent

