# finger: Darwin man parser
# Autogenerated from man pages
complete -c finger -s 4 --description Forces
complete -c finger -s 6 --description Forces
complete -c finger -s g --description 'This option restricts the gecos output to onl... [See Man Page]'
complete -c finger -s h --description 'When used in conjunction with the'
complete -c finger -s k --description 'Disable all use of'
complete -c finger -s l --description 'Produce a multi-line format displaying all of... [See Man Page]'
complete -c finger -s m --description 'Prevent matching of'
complete -c finger -s o --description 'When used in conjunction with the'
complete -c finger -s p --description Preventthe
complete -c finger -s s --description 'Display the user\'s login name, real name, ter... [See Man Page]'

