# fixproc: Deroffing man parser
# Autogenerated from man pages
complete -c fixproc -o min --description 'minimum number of processes that should be ru... [See Man Page]'
complete -c fixproc -o max --description 'maximum number of processes that should be ru... [See Man Page]'
complete -c fixproc -o check --description 'check process against database /local/etc/fix... [See Man Page]'
complete -c fixproc -o kill --description 'kill process, wait 5 seconds, kill -9 if stil... [See Man Page]'
complete -c fixproc -o restart --description 'kill process, wait 5 seconds, kill -9 if stil... [See Man Page]'
complete -c fixproc -o exist --description 'checks if proc exists in ps && (min <= num'
complete -c fixproc -o fix --description 'check process against database /local/etc/fix... [See Man Page]'

