# FixupResourceForks: Darwin man parser
# Autogenerated from man pages
complete -c FixupResourceForks -l 'q[uiet]' --description 'Suppress verbose diagnostics to standard outp... [See Man Page]'
complete -c FixupResourceForks -l nosetinfo --description 'Do not set file system metadata (type, creato... [See Man Page]'
complete -c FixupResourceForks -l nodelete --description 'Leave the AppleDouble files in the directory ... [See Man Page]'

