# fmt: Darwin man parser
# Autogenerated from man pages
complete -c fmt -s c --description 'Center the text, line by line'
complete -c fmt -s m --description 'Try to format mail header lines contained in ... [See Man Page]'
complete -c fmt -s n --description 'Format lines beginning with a'
complete -c fmt -s p --description 'Allow indented paragraphs'
complete -c fmt -s s --description 'Collapse whitespace inside lines, so that mul... [See Man Page]'
complete -c fmt -s d --description 'Treat the'
complete -c fmt -s l --description 'Replace multiple spaces with tabs at the star... [See Man Page]'
complete -c fmt -s t --description 'Assume that the input files\' tabs assume'

