# fold: Darwin man parser
# Autogenerated from man pages
complete -c fold -s b --description Count
complete -c fold -s s --description 'Fold line after the last blank character with... [See Man Page]'
complete -c fold -s w --description 'Specify a line width to use instead of the de... [See Man Page]'

