# fs_usage: Darwin man parser
# Autogenerated from man pages
complete -c fs_usage -s e --description 'Specifying the'
complete -c fs_usage -s f --description 'Specifying the'
complete -c fs_usage -s w --description 'Specifying the'
complete -c fs_usage -s R --description 'Specifies a raw trace file to process'
complete -c fs_usage -s S --description 'If '
complete -c fs_usage -s E --description 'If '

