# ftp: Darwin man parser
# Autogenerated from man pages
complete -c ftp -s 4 --description Forces
complete -c ftp -s 6 --description Forces
complete -c ftp -s A --description 'Force active mode ftp'
complete -c ftp -s a --description Causes
complete -c ftp -s d --description 'Enables debugging'
complete -c ftp -s e --description 'Disables command line editing'
complete -c ftp -s f --description 'Forces a cache reload for transfers that go t... [See Man Page]'
complete -c ftp -s g --description 'Disables file name globbing'
complete -c ftp -s i --description 'Turns off interactive prompting duringmultipl... [See Man Page]'
complete -c ftp -s n --description Restrains
complete -c ftp -s N --description Use
complete -c ftp -s o --description 'When auto-fetching files, save the contents i... [See Man Page]'
complete -c ftp -s p --description 'Enable passive mode operation for use behind ... [See Man Page]'
complete -c ftp -s P --description 'Sets the port number to'
complete -c ftp -s q --description 'Quit if the connection has stalled for'
complete -c ftp -s r --description 'Retry the connection attempt if it failed, pa... [See Man Page]'
complete -c ftp -s R --description 'Restart all non-proxied auto-fetches'
complete -c ftp -s s --description Uses
complete -c ftp -s t --description 'Enables packet tracing'
complete -c ftp -s u --description 'Upload files on the command line to'
complete -c ftp -s v --description Enable
complete -c ftp -s V --description Disable

