# fuser: Deroffing man parser
# Autogenerated from man pages
complete -c fuser -s c --description 'The file is treated as a mount point and the ... [See Man Page]'
complete -c fuser -s f --description 'The report shall be only for the named files'
complete -c fuser -s u --description 'The user name, in parentheses, associated wit... [See Man Page]'

