# fwkdp: Darwin man parser
# Autogenerated from man pages
complete -c fwkdp -l -setargs --description 'Sets the nvram boot-args on the current machi... [See Man Page]'
complete -c fwkdp -l -proxy --description 'Use proxy mode only'
complete -c fwkdp -l -gdb --description 'Use proxy mode only and automatically start g... [See Man Page]'
complete -c fwkdp -l -core --description 'Use core dump receive mode only'
complete -c fwkdp -l -verbose --description 'Verbose mode'
complete -c fwkdp -l -disable --description 'Sets the nvram boot-args on the current machi... [See Man Page]'
complete -c fwkdp -l -erase --description 'Deletes the boot-args variable from nvram'
complete -c fwkdp -l -ioff --description 'Turns off interactive mode'
complete -c fwkdp -l -restart --description 'Automatically restarts the machine only after... [See Man Page]'
complete -c fwkdp -l -help --description 'Displays usage info for fwkdp'

