# fwkpfv: Darwin man parser
# Autogenerated from man pages
complete -c fwkpfv -l -appendlog --description 'Append output logging to /Library/Logs/FireWi... [See Man Page]'
complete -c fwkpfv -l -openlog --description 'Open log file with Console'
complete -c fwkpfv -l -newlog --description 'Create a new log file, rather than append'
complete -c fwkpfv -l -prefix --description 'Prefix logger machine\'s ID to each log'
complete -c fwkpfv -l -publish --description 'Do not publish FireWire unit directory keys'
complete -c fwkpfv -l -single --description 'Use a single window even if multiple loggers ... [See Man Page]'
complete -c fwkpfv -l -buffer --description 'Sets the host\'s psuedo address space queue bu... [See Man Page]'
complete -c fwkpfv -l -setargs --description 'Sets the nvram boot-args on the current machi... [See Man Page]'
complete -c fwkpfv -l -setpm --description 'Sets the nvram boot-args on the current machi... [See Man Page]'
complete -c fwkpfv -l -disable --description 'Sets the nvram boot-args on the current machi... [See Man Page]'
complete -c fwkpfv -l -erase --description 'Deletes the boot-args variable from nvram'
complete -c fwkpfv -l -ioff --description 'Turns off interactive mode'
complete -c fwkpfv -l -restart --description 'Automatically restarts the machine only after... [See Man Page]'
complete -c fwkpfv -l -help --description 'Displays usage info for fwkpfv'

