# gdb: Deroffing man parser
# Autogenerated from man pages
complete -c gdb -s h --description 'List all options, with brief explanations'
complete -c gdb -s s --description 'Read symbol table from file \\c  file\\c '
complete -c gdb -o write --description 'Enable writing into executable and core files... [See Man Page]'
complete -c gdb -s e --description 'Use file \\c  file\\c  as the executable file t... [See Man Page]'
complete -c gdb -o se --description 'Read symbol table from file \\c  file\\c  and u... [See Man Page]'
complete -c gdb -s c --description 'Use file \\c  file\\c  as a core dump to examin... [See Man Page]'
complete -c gdb -s x --description 'Execute GDB commands from file \\c  file\\c '
complete -c gdb -s d --description 'Add \\c  directory\\c  to the path to search fo... [See Man Page]'
complete -c gdb -s n --description 'Do not execute commands from any `\\|\\c  '
complete -c gdb -s q --description '``Quiet\'\''
complete -c gdb -o batch --description 'Run in batch mode'
complete -c gdb -o cd --description 'Run GDB using \\c  directory\\c  as its working... [See Man Page]'
complete -c gdb -s f --description 'Emacs sets this option when it runs GDB as a ... [See Man Page]'
complete -c gdb -s b --description 'Set the line speed (baud rate or bits per sec... [See Man Page]'
complete -c gdb -o sec --description '\' option, and the second, if any, is equivale... [See Man Page]'
complete -c gdb -o cc --description '\' option if it\'s the name of a file'
complete -c gdb -o xc --description '\' option is used'
complete -c gdb -o help
complete -c gdb -o symbols
complete -c gdb -o exec
complete -c gdb -o core
complete -c gdb -o command
complete -c gdb -o directory
complete -c gdb -o nx
complete -c gdb -o quiet
complete -c gdb -o fullname
complete -c gdb -o tty

