# gdiffmk: Deroffing man parser
# Autogenerated from man pages
complete -c gdiffmk -s a --description 'Use the  addmark for source lines not in  fil... [See Man Page]'
complete -c gdiffmk -s B --description 'By default, the deleted texts marked by the  ... [See Man Page]'
complete -c gdiffmk -s c --description 'Use the  changemark for changed source lines'
complete -c gdiffmk -s d --description 'Use the  deletemark for deleted source lines'
complete -c gdiffmk -s D --description 'Show the deleted portions from changed and de... [See Man Page]'
complete -c gdiffmk -s M --description 'Change the delimiting marks for the  -D optio... [See Man Page]'
complete -c gdiffmk -s x --description 'Use the  diffcmd command to perform the compa... [See Man Page]'
complete -c gdiffmk -l help --description 'Print a usage message on standard error outpu... [See Man Page]'

