# gen_bridge_metadata: Darwin man parser
# Autogenerated from man pages
complete -c gen_bridge_metadata -s f --description 'Generates metadata for the given'
complete -c gen_bridge_metadata -s p --description 'Generates metadata based on the private heade... [See Man Page]'
complete -c gen_bridge_metadata -s F --description 'Selects the metadata format that will be gene... [See Man Page]'
complete -c gen_bridge_metadata -s e --description 'Considers the given exception file when gener... [See Man Page]'
complete -c gen_bridge_metadata -l -64-bit --description '(This option is included for backwards compat... [See Man Page]'
complete -c gen_bridge_metadata -l -no-64-bit --description 'Do not write the 64-bit annotations to the fi... [See Man Page]'
complete -c gen_bridge_metadata -s c --description 'Provides custom flags that will be passed to ... [See Man Page]'
complete -c gen_bridge_metadata -s C --description 'Provides custom flags that will be passed to ... [See Man Page]'
complete -c gen_bridge_metadata -s o --description 'Writes the output to the given file'
complete -c gen_bridge_metadata -s h --description 'Prints a summary of the options'
complete -c gen_bridge_metadata -s d --description 'Turns on debugging messages'
complete -c gen_bridge_metadata -s v --description 'Shows the version of the program'

