# genstrings: Darwin man parser
# Autogenerated from man pages
complete -c genstrings -s a --description 'Allows the output to be appended to the old o... [See Man Page]'
complete -c genstrings -s s --description 'Substitutes \\fIroutine\\fR for NSLocalizedStri... [See Man Page]'
complete -c genstrings -l skipTable --description 'Causes genstrings to skip over the file for \\... [See Man Page]'
complete -c genstrings -l noPositionalParameters --description 'Turns off generation of positional parameters... [See Man Page]'
complete -c genstrings -s u --description 'Allow unicode characters in the value of stri... [See Man Page]'
complete -c genstrings -l macRoman --description 'For compatibility, read source files using Ma... [See Man Page]'
complete -c genstrings -s q --description 'Turns off multiple key/value pairs warning'
complete -c genstrings -s o --description 'Specifies what directory the tables should be... [See Man Page]'

