# geod: Deroffing man parser
# Autogenerated from man pages
complete -c geod -s I --description 'Specifies that the inverse geodesic computati... [See Man Page]'
complete -c geod -s a --description 'Latitude and longitudes of the initial and te... [See Man Page]'
complete -c geod -s t --description 'A specifies a character employed as the first... [See Man Page]'
complete -c geod -o le --description 'Gives a listing of all the ellipsoids that ma... [See Man Page]'
complete -c geod -o lu --description 'Gives a listing of all the units that may be ... [See Man Page]'
complete -c geod -o '[f' --description 'Format is a  printf format string to control ... [See Man Page]'
complete -c geod -o '[w' --description 'N is the number of significant fractional dig... [See Man Page]'
complete -c geod -o w3 --description 'is assumed)'
complete -c geod -s W --description 'is employed the fields will be constant width... [See Man Page]'
complete -c geod -s p --description 'This option causes the azimuthal values to be... [See Man Page]'
complete -c geod -s f --description 'switch is not employed) to 0'

