# GetFileInfo: Darwin man parser
# Autogenerated from man pages
complete -c GetFileInfo -s P --description 'Acts on a symlink file instead of the file th... [See Man Page]'
complete -c GetFileInfo -l 'a[<attribute-letter>]' --description 'Gets a file\'s attribute bits where'
complete -c GetFileInfo -s t --description 'Gets the file type, a string of exactly four ... [See Man Page]'
complete -c GetFileInfo -s c --description 'Gets the file\'s creator, a string of four cha... [See Man Page]'
complete -c GetFileInfo -s d --description 'Gets the creation date, a string of the form ... [See Man Page]'
complete -c GetFileInfo -s m --description 'Gets the modification date, a string of the f... [See Man Page]'

