# git-grep: Deroffing man parser
# Autogenerated from man pages
complete -c git-grep -o '[ABC]' --description 'Show context trailing (A \\(em after), or lead... [See Man Page]'
complete -c git-grep -o 'C<num>.'

