# git-check-ref-format: Deroffing man parser
# Autogenerated from man pages
complete -c git-check-ref-format -l allow-onelevel -l no-allow-onelevel --description 'Controls whether one-level refnames are accep... [See Man Page]'
complete -c git-check-ref-format -l refspec-pattern --description 'Interpret <refname> as a reference name patte... [See Man Page]'
complete -c git-check-ref-format -l normalize --description 'Normalize refname by removing any leading sla... [See Man Page]'
complete -c git-check-ref-format -l 'no-allow-onelevel.'
complete -c git-check-ref-format -l 'normalize.)'

