# git-diff-files: Deroffing man parser
# Autogenerated from man pages
complete -c git-diff-files -l 'dirstat-by-file[' --description 'Same as --dirstat, but counts changed files i... [See Man Page]'
complete -c git-diff-files -l cumulative --description 'is used'

