# git-format-patch: Deroffing man parser
# Autogenerated from man pages
complete -c git-format-patch -l 'dirstat-by-file[' --description 'Same as --dirstat, but counts changed files i... [See Man Page]'
complete -c git-format-patch -l cumulative --description 'is used'

