# git-diff-index: Deroffing man parser
# Autogenerated from man pages
complete -c git-diff-index -l 'dirstat-by-file[' --description 'Same as --dirstat, but counts changed files i... [See Man Page]'
complete -c git-diff-index -l cumulative --description 'is used'

