# glibtool: Darwin man parser
# Autogenerated from man pages
complete -c glibtool -l '\\-config' --description '\\&show all configuration variables'
complete -c glibtool -l '\\-debug' --description '\\&enable verbose shell tracing'
complete -c glibtool -s n --description '\\&display commands without modifying any file... [See Man Page]'
complete -c glibtool -l '\\-features' --description '\\&display basic configuration information and... [See Man Page]'
complete -c glibtool -l '\\-mode' --description '\\&use operation mode MODE'
complete -c glibtool -l '\\-preserve-dup-deps' --description '\\&don\'t remove duplicate dependency libraries'
complete -c glibtool -l '\\-quiet' --description '\\&don\'t print informational messages'
complete -c glibtool -l '\\-no-quiet' --description '\\&print informational messages (default)'
complete -c glibtool -l '\\-tag' --description '\\&use configuration variables from tag TAG'
complete -c glibtool -s v --description '\\&print more informational messages than defa... [See Man Page]'
complete -c glibtool -l '\\-no-verbose' --description '\\&don\'t print the extra informational message... [See Man Page]'
complete -c glibtool -l '\\-version' --description '\\&print version information'
complete -c glibtool -s h --description '\\&print short, long, or detailed help message... [See Man Page]'

