# glibtoolize: Deroffing man parser
# Autogenerated from man pages
complete -c glibtoolize -s c -l copy --description 'copy files rather than symlinking them'
complete -c glibtoolize -l debug --description 'enable verbose shell tracing'
complete -c glibtoolize -s n -l dry-run --description 'print commands rather than running them'
complete -c glibtoolize -s f -l force --description 'replace existing files'
complete -c glibtoolize -s i -l install --description 'copy missing auxiliary files'
complete -c glibtoolize -l 'ltdl[' --description 'install libltdl sources [default: libltdl]'
complete -c glibtoolize -l no-warn --description 'don\'t display warning messages'
complete -c glibtoolize -l nonrecursive --description 'prepare ltdl for non-recursive make'
complete -c glibtoolize -s q -l quiet --description 'work silently'
complete -c glibtoolize -l recursive --description 'prepare ltdl for recursive make'
complete -c glibtoolize -l subproject --description 'prepare ltdl to configure and build independe... [See Man Page]'
complete -c glibtoolize -s v -l verbose --description 'verbosely report processing'
complete -c glibtoolize -l version --description 'print version information and exit'
complete -c glibtoolize -s h -l help --description 'print short or long help message '

