# gnudoit: Deroffing man parser
# Autogenerated from man pages
complete -c gnudoit -o nw --description 'This option makes gnuclient act as a frontend... [See Man Page]'
complete -c gnudoit -o display -l display --description 'If this option is given or the `DISPLAY\' envi... [See Man Page]'
complete -c gnudoit -s q --description 'This option informs gnuclient to exit once co... [See Man Page]'
complete -c gnudoit -s v --description 'When this option is specified gnuclient will ... [See Man Page]'
complete -c gnudoit -s l --description 'Tell Emacs to load the specified library'
complete -c gnudoit -o batch --description 'Tell Emacs not to open any frames'
complete -c gnudoit -s f --description 'Make Emacs execute the lisp function'
complete -c gnudoit -o eval --description 'Make Emacs execute the lisp form'
complete -c gnudoit -s h --description 'Used only with Internet-domain sockets, this ... [See Man Page]'
complete -c gnudoit -s p --description 'Used only with Internet-domain sockets, this ... [See Man Page]'
complete -c gnudoit -s r --description 'Used only with Internet-domain sockets, the p... [See Man Page]'

