# grap2graph: Deroffing man parser
# Autogenerated from man pages
complete -c grap2graph -o unsafe --description 'Run   pic (1) and  groff (1) in the `unsafe\' ... [See Man Page]'
complete -c grap2graph -o format --description 'Specify an output format; the default is PNG ... [See Man Page]'

