# grind: Deroffing man parser
# Autogenerated from man pages
complete -c grind -s v --description 'Verify integrity of input without generating ... [See Man Page]'
complete -c grind -s s --description 'Suppress generation of warning messages'
complete -c grind -s L --description 'Write all messages to logfile instead of stde... [See Man Page]'
complete -c grind -s a --description 'Generate statistical report on input files pr... [See Man Page]'
complete -c grind -s d --description 'Generate distribution of senses by string len... [See Man Page]'
complete -c grind -s i --description 'Generate sense index file'
complete -c grind -s o --description 'Order senses using cntlist'
complete -c grind -s n --description 'Generate nominalization (derivational morphol... [See Man Page]'

