# grodvi: Deroffing man parser
# Autogenerated from man pages
complete -c grodvi -s d --description 'Do not use tpic specials to implement drawing... [See Man Page]'
complete -c grodvi -s F --description 'Prepend directory B dir /dev name to the sear... [See Man Page]'
complete -c grodvi -s l --description 'Specify landscape orientation'
complete -c grodvi -s p --description 'Specify paper dimensions'
complete -c grodvi -s v --description 'Print the version number'
complete -c grodvi -o Tdvi --description 'loads pspic'
complete -c grodvi -s w --description 'Set the default line thickness to n thousandt... [See Man Page]'
complete -c grodvi -o mec --description '(which loads the file ec'

