# groffer: Deroffing man parser
# Autogenerated from man pages
complete -c groffer -l shell
complete -c groffer -l foreground
complete -c groffer -l resolution
complete -c groffer -l x-viewer -o geometry --description '# # some shell commands if test "$DISPLAY" = ... [See Man Page]'

