# groff: Deroffing man parser
# Autogenerated from man pages
complete -c groff -s p --description and
complete -c groff -s l --description 'See groff_font (5) and the man pages of the o... [See Man Page]'
complete -c groff -s P --description 'to pass options to output devices; for exampl... [See Man Page]'

