# grolj4: Deroffing man parser
# Autogenerated from man pages
complete -c grolj4 -s c --description 'Print  n copies of each page'
complete -c grolj4 -s l --description 'Print the document with a landscape orientati... [See Man Page]'
complete -c grolj4 -s d --description 'Use duplex mode R n : 1is long-side binding; ... [See Man Page]'
complete -c grolj4 -s p --description 'Set the paper size to R size , which must be ... [See Man Page]'
complete -c grolj4 -s v --description 'Print the version number'
complete -c grolj4 -s w --description 'Set the default line thickness to  n thousand... [See Man Page]'
complete -c grolj4 -s F --description 'Prepend directory B dir /dev name to the sear... [See Man Page]'

