# grops: Deroffing man parser
# Autogenerated from man pages
complete -c grops -s b --description 'Provide workarounds for older printers, broke... [See Man Page]'
complete -c grops -s c --description 'Print  n copies of each page'
complete -c grops -s F --description 'Prepend directory B dir /dev name to the sear... [See Man Page]'
complete -c grops -s g --description 'Guess the page length'
complete -c grops -s I --description 'This option may be used to specify a director... [See Man Page]'
complete -c grops -s l --description 'Print the document in landscape format'
complete -c grops -s m --description 'Turn manual feed on for the document'
complete -c grops -s p --description 'Set physical dimension of output medium'
complete -c grops -s P --description 'Use the file  prologue-file (in the font path... [See Man Page]'
complete -c grops -s w --description 'Lines should be drawn using a thickness of R ... [See Man Page]'
complete -c grops -o Tps --description option
complete -c grops -s v --description 'Print the version number'

