# grotty: Deroffing man parser
# Autogenerated from man pages
complete -c grotty -s b --description 'Suppress the use of overstriking for bold cha... [See Man Page]'
complete -c grotty -s B --description 'Use only overstriking for bold-italic charact... [See Man Page]'
complete -c grotty -s c --description 'Use  grotty \'s old output format (see above)'
complete -c grotty -s d --description 'Ignore all  \\[rs]D commands'
complete -c grotty -s f --description 'Use form feeds in the output'
complete -c grotty -s F --description 'Prepend directory B dir /dev name to the sear... [See Man Page]'
complete -c grotty -s h --description 'Use horizontal tabs in the output'
complete -c grotty -s i --description 'Use escape sequences to set the italic text a... [See Man Page]'
complete -c grotty -s o --description 'Suppress overstriking (other than for bold or... [See Man Page]'
complete -c grotty -s r --description 'Use escape sequences to set the reverse text ... [See Man Page]'
complete -c grotty -s u --description 'Suppress the use of underlining for italic ch... [See Man Page]'
complete -c grotty -s U --description 'Use only underlining for bold-italic characte... [See Man Page]'
complete -c grotty -o Tascii
complete -c grotty -o Tlatin1 --description or
complete -c grotty -o Tutf8 --description 'option on ASCII based systems, and with'
complete -c grotty -o Tcp1047 --description and
complete -c grotty -s R --description 'option of less (1) to disable the interpretat... [See Man Page]'
complete -c grotty -s P --description 'option of man to set the pager executable and... [See Man Page]'
complete -c grotty -s v --description 'Print the version number'

