# gzip: Deroffing man parser
# Autogenerated from man pages
complete -c gzip -s a -l ascii --description 'Ascii text mode: convert end-of-lines using l... [See Man Page]'
complete -c gzip -s c -l stdout -l to-stdout --description 'Write output on standard output; keep origina... [See Man Page]'
complete -c gzip -s d -l decompress -l uncompress --description Decompress
complete -c gzip -s f -l force --description 'Force compression or decompression even if th... [See Man Page]'
complete -c gzip -s h -l help --description 'Display a help screen and quit'
complete -c gzip -s l -l list --description 'For each compressed file, list the following ... [See Man Page]'
complete -c gzip -s L -l license --description 'Display the  gzip license and quit'
complete -c gzip -s n -l no-name --description 'When compressing, do not save the original fi... [See Man Page]'
complete -c gzip -s N -l name --description 'When compressing, always save the original fi... [See Man Page]'
complete -c gzip -s q -l quiet --description 'Suppress all warnings'
complete -c gzip -s r -l recursive --description 'Travel the directory structure recursively'
complete -c gzip -s S -l suffix --description 'Use suffix '
complete -c gzip -s t -l test --description Test
complete -c gzip -s v -l verbose --description Verbose
complete -c gzip -s V -l version --description Version
complete -c gzip -o gz --description 'for VMS, z for MSDOS, OS/2 FAT, Windows NT FA... [See Man Page]'
complete -c gzip -o 'c.' --description '(On some systems, zcat may be installed as gz... [See Man Page]'
complete -c gzip -s '#' -l fast -l best --description 'Regulate the speed of compression using the s... [See Man Page]'
complete -c gzip -s 1 --description or
complete -c gzip -s 9 --description or
complete -c gzip -s 6 --description '(that is, biased towards high compression at ... [See Man Page]'

