# h2ph: Type1
# Autogenerated from man pages
complete -c h2ph -s d --description 'Put the resulting '
complete -c h2ph -s r --description 'Run recursively; if any of headerfiles are di... [See Man Page]'
complete -c h2ph -s a --description 'Run automagically; convert headerfiles, as we... [See Man Page]'
complete -c h2ph -s l --description 'Symbolic links will be replicated in the dest... [See Man Page]'
complete -c h2ph -s h --description 'Put ``hints\'\' in the '
complete -c h2ph -s D --description 'Include the code from the '

