# headerdoc2html: Darwin man parser
# Autogenerated from man pages
complete -c headerdoc2html -s H --description The
complete -c headerdoc2html -s X --description The
complete -c headerdoc2html -s d --description The
complete -c headerdoc2html -s h --description The
complete -c headerdoc2html -s p --description The
complete -c headerdoc2html -s q --description The
complete -c headerdoc2html -s u --description The
complete -c headerdoc2html -s v --description The

