# heap: Darwin man parser
# Autogenerated from man pages
complete -c heap -l guessNonObjects --description 'Look through the memory contents of each Obje... [See Man Page]'
complete -c heap -l sumObjectFields --description 'Do the same analysis as with the'
complete -c heap -l showSizes --description 'Show the distribution of each malloc size for... [See Man Page]'
complete -c heap -l addresses --description 'Print the addresses of all malloc blocks foun... [See Man Page]'

