# hexdump: Darwin man parser
# Autogenerated from man pages
complete -c hexdump -s b
complete -c hexdump -s C
complete -c hexdump -s c
complete -c hexdump -s d
complete -c hexdump -s e --description 'Specify a format string to be used for displa... [See Man Page]'
complete -c hexdump -s f --description 'Specify a file that contains one or more newl... [See Man Page]'
complete -c hexdump -s n --description 'Interpret only'
complete -c hexdump -s o
complete -c hexdump -s s --description Skip
complete -c hexdump -s v --description Cause
complete -c hexdump -s x

