# hostname: Darwin man parser
# Autogenerated from man pages
complete -c hostname -s f --description 'Include domain information in the printed nam... [See Man Page]'
complete -c hostname -s s --description 'Trim off any domain information from the prin... [See Man Page]'

