# host: Deroffing man parser
# Autogenerated from man pages
complete -c host -s a --description '(all) option is equivalent to setting the'
complete -c host -s v --description 'option and asking host to make a query of typ... [See Man Page]'
complete -c host -s C --description 'option is used, host will attempt to display ... [See Man Page]'
complete -c host -s c --description 'option instructs to make a DNS query of class... [See Man Page]'
complete -c host -s d --description or
complete -c host -s l --description option
complete -c host -s i --description 'option specifies that reverse lookups of IPv6... [See Man Page]'
complete -c host -s N --description 'option sets the number of dots that have to b... [See Man Page]'
complete -c host -s R --description option
complete -c host -s r --description option
complete -c host -s T --description 'option makes it use a TCP connection when que... [See Man Page]'
complete -c host -s 4 --description 'option forces host to only use IPv4 query tra... [See Man Page]'
complete -c host -s 6 --description 'option forces host to only use IPv6 query tra... [See Man Page]'
complete -c host -s t --description 'option is used to select the query type'
complete -c host -s W --description and
complete -c host -s w --description options
complete -c host -s s --description 'option tells host not to send the query to th... [See Man Page]'
complete -c host -s m --description 'can be used to set the memory usage debugging... [See Man Page]'

