# hpftodit: Deroffing man parser
# Autogenerated from man pages
complete -c hpftodit -s a --description 'Include characters in the TFM file that are n... [See Man Page]'
complete -c hpftodit -s d --description 'Dump information about the TFM file to the st... [See Man Page]'
complete -c hpftodit -s q --description 'Suppress warnings about characters in the map... [See Man Page]'
complete -c hpftodit -s v --description 'Print the  hpftodit version number'
complete -c hpftodit -s s --description 'The font is special'
complete -c hpftodit -s i --description 'Generate an italic correction for each charac... [See Man Page]'

