# htdbm: Type1
# Autogenerated from man pages
complete -c htdbm -s b --description 'Use batch mode; i'
complete -c htdbm -s c --description 'Create the passwdfile'
complete -c htdbm -s n --description 'Display the results on standard output rather... [See Man Page]'
complete -c htdbm -s m --description 'Use MD5 encryption for passwords'
complete -c htdbm -s d --description 'Use crypt() encryption for passwords'
complete -c htdbm -s s --description 'Use SHA encryption for passwords'
complete -c htdbm -s p --description 'Use plaintext passwords'
complete -c htdbm -s l --description 'Print each of the usernames and comments from... [See Man Page]'
complete -c htdbm -s t --description 'Interpret the final parameter as a comment'
complete -c htdbm -s v --description 'Verify the username and password'
complete -c htdbm -s x --description 'Delete user'

