# htop: Deroffing man parser
# Autogenerated from man pages
complete -c htop -s d --description 'Delay between updates, in tenths of seconds'
complete -c htop -s u --description 'Show only processes of a given user'
complete -c htop -l sort-key --description 'Sort by this column (use --sort-key help for ... [See Man Page]'

