# htpasswd: Type1
# Autogenerated from man pages
complete -c htpasswd -s b --description 'Use batch mode; i'
complete -c htpasswd -s c --description 'Create the passwdfile'
complete -c htpasswd -s n --description 'Display the results on standard output rather... [See Man Page]'
complete -c htpasswd -s m --description 'Use MD5 encryption for passwords'
complete -c htpasswd -s d --description 'Use crypt() encryption for passwords'
complete -c htpasswd -s s --description 'Use SHA encryption for passwords'
complete -c htpasswd -s p --description 'Use plaintext passwords'
complete -c htpasswd -s D --description 'Delete user'

