# icc2ps: Deroffing man parser
# Autogenerated from man pages
complete -c icc2ps -s b --description 'Black point compensation (CRD only)'
complete -c icc2ps -s i --description 'Input profile: Generates Color Space Array (C... [See Man Page]'
complete -c icc2ps -s o
complete -c icc2ps -s t --description 'Intent (0=Perceptual, 1=Colorimetric, 2=Satur... [See Man Page]'
complete -c icc2ps -s u --description 'Do NOT generate resource name on CRD'

