# icclink: Deroffing man parser
# Autogenerated from man pages
complete -c icclink -s 8 --description 'Creates 8-bit devicelink'
complete -c icclink -s b --description 'Black point compensation'
complete -c icclink -s c --description 'Precission (0=LowRes, 1=Normal, 2=Hi-res)'
complete -c icclink -s d --description 'Description text (quotes can be used)'
complete -c icclink -s h --description 'Show summary of options and examples'
complete -c icclink -s i --description 'Input profile (defaults to sRGB)'
complete -c icclink -s k --description 'Ink-limiting in % (CMYK only)'
complete -c icclink -s o --description 'Output devicelink profile'
complete -c icclink -s t --description 'Intent (0=Perceptual, 1=Colorimetric, 2=Satur... [See Man Page]'
complete -c icclink -s x --description 'Creatively, guess deviceclass of resulting pr... [See Man Page]'

