# iconutil: Darwin man parser
# Autogenerated from man pages
complete -c iconutil -s c --description 'Given the argument '
complete -c iconutil -s o --description 'Overrides the default output file name that'

