# iconv: Deroffing man parser
# Autogenerated from man pages
complete -c iconv -s f -l from-code --description 'Specifies the encoding of the input'
complete -c iconv -s t -l to-code --description 'Specifies the encoding of the output'
complete -c iconv -s c --description 'When this option is given, characters that ca... [See Man Page]'
complete -c iconv -l unicode-subst --description 'When this option is given, Unicode characters... [See Man Page]'
complete -c iconv -l byte-subst --description 'When this option is given, bytes in the input... [See Man Page]'
complete -c iconv -l widechar-subst --description 'When this option is given, wide characters in... [See Man Page]'
complete -c iconv -s s -l silent --description 'When this option is given, error messages abo... [See Man Page]'

