# ident: Deroffing man parser
# Autogenerated from man pages
complete -c ident -s q --description 'suppresses the warning given if there are no ... [See Man Page]'
complete -c ident -s V --description 'prints ident \'s version number'
complete -c ident -s z --description 'option, times are given with a numeric time z... [See Man Page]'
complete -c ident -s s --description 'option of rcs (1) or ci (1)'

