# idlj: Deroffing man parser
# Autogenerated from man pages
complete -c idlj -s d --description 'This is equivalent to the following line in a... [See Man Page]'
complete -c idlj -o emitAll --description 'Emit all types, including those found in  #in... [See Man Page]'
complete -c idlj -o fside --description 'Defines what bindings to emit'
complete -c idlj -s i --description 'By default, the current directory is scanned ... [See Man Page]'
complete -c idlj -o keep --description 'If a file to be generated already exists, do ... [See Man Page]'
complete -c idlj -o noWarn --description 'Supresses warning messages'
complete -c idlj -o oldImplBase --description 'Generates skeletons compatible with old (pre-... [See Man Page]'
complete -c idlj -o pkgPrefix --description 'Wherever   type  is encountered at file scope... [See Man Page]'
complete -c idlj -o pkgTranslate --description 'Wherever the type or module name   type  is e... [See Man Page]'
complete -c idlj -o skeletonName --description 'Use  xxx%yyy as the pattern for naming the sk... [See Man Page]'
complete -c idlj -o td --description 'Use  dir for the output directory instead of ... [See Man Page]'
complete -c idlj -o tieName --description 'Name the tie according to the pattern'
complete -c idlj -o nowarn -o verbose --description 'Verbose mode'
complete -c idlj -s v --description 'option to activate this "verbose" mode:  idlj... [See Man Page]'
complete -c idlj -o version --description 'option on the command-line: idlj -version  Ve... [See Man Page]'
complete -c idlj -o fserverTIE
complete -c idlj -o fallTIE --description 'options cause delegate model skeletons to be ... [See Man Page]'
complete -c idlj -o fclient --description 'if the flag is not specified'
complete -c idlj -o fserver --description or
complete -c idlj -o fall
complete -c idlj -o fserverTie --description or
complete -c idlj -o fallTie

