# ifnames: Deroffing man parser
# Autogenerated from man pages
complete -c ifnames -s h -l help --description 'print this help, then exit'
complete -c ifnames -s V -l version --description 'print version number, then exit AUTHOR Writte... [See Man Page]'

