# include_server: Deroffing man parser
# Autogenerated from man pages
complete -c include_server -o dPAT -l debug_pattern --description 'Bit vector for turning on warnings and debugg... [See Man Page]'
complete -c include_server -s e -l email --description 'Send email to \'distcc-pump-errors\' or if defi... [See Man Page]'
complete -c include_server -l email_bound --description 'Maximal number of emails to send (in addition... [See Man Page]'
complete -c include_server -l no-email --description 'Do not send email'
complete -c include_server -l path_observation_re --description 'Issue warning message whenever a filename is ... [See Man Page]'
complete -c include_server -l pid_file --description 'The pid of the include server is written to f... [See Man Page]'
complete -c include_server -s s -l statistics --description 'Print information to stdout about include ana... [See Man Page]'
complete -c include_server -l stat_reset_triggers --description 'Flush stat caches when the timestamp of any f... [See Man Page]'
complete -c include_server -s t -l time --description 'Print elapsed, user, and system time to stder... [See Man Page]'
complete -c include_server -l unsafe_absolute_includes --description 'Do preprocessing on the compilation server ev... [See Man Page]'
complete -c include_server -s v -l verify --description 'Verify that files in CPP closure are containe... [See Man Page]'
complete -c include_server -s w -l write_include_closure --description 'Write a '
complete -c include_server -s x -l exact_analysis --description 'Use CPP instead, do not omit system headers f... [See Man Page]'

