# indxbib: Deroffing man parser
# Autogenerated from man pages
complete -c indxbib -s v --description 'Print the version number'
complete -c indxbib -s w --description 'Index whole files'
complete -c indxbib -s c --description 'Read the list of common words from  file inst... [See Man Page]'
complete -c indxbib -s d --description 'Use  dir as the pathname of the current worki... [See Man Page]'
complete -c indxbib -s f --description 'Read the files to be indexed from R file '
complete -c indxbib -s i --description 'Don\'t index the contents of fields whose name... [See Man Page]'
complete -c indxbib -s h --description 'Use the first prime greater than or equal to ... [See Man Page]'
complete -c indxbib -s k --description 'Use at most  n keys per input record'
complete -c indxbib -s l --description 'Discard keys that are shorter than R n '
complete -c indxbib -s n --description 'Discard the  n most common words'
complete -c indxbib -s o --description 'The index should be named B basename '
complete -c indxbib -s t --description 'options are stored in the index; when the ind... [See Man Page]'

