# infocmp: Deroffing man parser
# Autogenerated from man pages
complete -c infocmp -s a --description 'tells infocmp to retain commented-out capabil... [See Man Page]'
complete -c infocmp -s s --description 'The -s option sorts the fields within each ty... [See Man Page]'
complete -c infocmp -s t --description 'tells tic to discard commented-out capabiliti... [See Man Page]'
complete -c infocmp -s I --description 'the -d option will be assumed'
complete -c infocmp -o C/use
complete -c infocmp -o r/when -s C --description 'If no termnames are given, the environment va... [See Man Page]'
complete -c infocmp -s 1 --description 'causes the fields to be printed out one to a ... [See Man Page]'
complete -c infocmp -s E --description 'Dump the capabilities of the given terminal a... [See Man Page]'
complete -c infocmp -s e --description 'Dump the capabilities of the given terminal a... [See Man Page]'
complete -c infocmp -s F --description 'compare terminfo files'
complete -c infocmp -s f --description 'Display complex terminfo strings which contai... [See Man Page]'
complete -c infocmp -s G --description 'Display constant literals in decimal form rat... [See Man Page]'
complete -c infocmp -s g --description 'Display constant character literals in quoted... [See Man Page]'
complete -c infocmp -s i --description 'Analyze the initialization (is1, is2, is3), a... [See Man Page]'
complete -c infocmp -s l --description 'Set output format to terminfo'
complete -c infocmp -s p --description 'Ignore padding specifications when comparing ... [See Man Page]'
complete -c infocmp -s q --description 'Make the comparison listing shorter by omitti... [See Man Page]'
complete -c infocmp -o Rsubset --description 'Restrict output to a given subset'
complete -c infocmp -s T --description 'eliminates size-restrictions on the generated... [See Man Page]'
complete -c infocmp -s U --description 'tells infocmp to not post-process the data af... [See Man Page]'
complete -c infocmp -s V --description 'reports the version of ncurses which was used... [See Man Page]'
complete -c infocmp -s v --description 'prints out tracing information on standard er... [See Man Page]'
complete -c infocmp -s w --description 'changes the output to width characters'
complete -c infocmp -s x --description 'print information for user-defined capabiliti... [See Man Page]'
complete -c infocmp -s R

