# info: Deroffing man parser
# Autogenerated from man pages
complete -c info -l apropos --description 'look up STRING in all indices of all manuals'
complete -c info -s d -l directory --description 'add DIR to INFOPATH'
complete -c info -l dribble --description 'remember user keystrokes in FILENAME'
complete -c info -s f -l file --description 'specify Info file to visit'
complete -c info -s h -l help --description 'display this help and exit'
complete -c info -l index-search --description 'go to node pointed by index entry STRING'
complete -c info -s n -l node --description 'specify nodes in first visited Info file'
complete -c info -s o -l output --description 'output selected nodes to FILENAME'
complete -c info -s R -l raw-escapes --description 'output "raw" ANSI escapes (default)'
complete -c info -l no-raw-escapes --description 'output escapes as literal text'
complete -c info -l restore --description 'read initial keystrokes from FILENAME'
complete -c info -s O -l show-options -l usage --description 'go to command-line options node'
complete -c info -l subnodes --description 'recursively output menu items'
complete -c info -s w -l where -l location --description 'print physical location of Info file'
complete -c info -l vi-keys --description 'use vi-like and less-like key bindings'
complete -c info -l version --description 'display version information and exit'

