# infokey: Deroffing man parser
# Autogenerated from man pages
complete -c infokey -l output --description 'output to FILE instead of $HOME/'
complete -c infokey -l help --description 'display this help and exit'
complete -c infokey -l version --description 'display version information and exit'

