# initdb: Deroffing man parser
# Autogenerated from man pages
complete -c initdb -s A -l auth --description 'This option specifies the authentication meth... [See Man Page]'
complete -c initdb -s D -l pgdata --description 'This option specifies the directory where the... [See Man Page]'
complete -c initdb -s E -l encoding --description 'Selects the encoding of the template database... [See Man Page]'
complete -c initdb -l locale --description 'Sets the default locale for the database clus... [See Man Page]'
complete -c initdb -l lc-collate -l lc-ctype -l lc-messages -l lc-monetary -l lc-numeric -l lc-time --description 'Like --locale, but only sets the locale in th... [See Man Page]'
complete -c initdb -l pwfile --description 'Makes initdb read the database superuser\\(aqs... [See Man Page]'
complete -c initdb -s U -l username --description 'Selects the user name of the database superus... [See Man Page]'
complete -c initdb -s W -l pwprompt --description 'Makes initdb prompt for a password to give th... [See Man Page]'
complete -c initdb -s X -l xlogdir --description 'This option specifies the directory where the... [See Man Page]'
complete -c initdb -s d -l debug --description 'Print debugging output from the bootstrap bac... [See Man Page]'
complete -c initdb -s L --description 'Specifies where initdb should find its input ... [See Man Page]'
complete -c initdb -s n -l noclean --description 'By default, when initdb determines that an er... [See Man Page]'
complete -c initdb -s V -l version --description 'Print the initdb version and exit'
complete -c initdb -s '?' -l help --description 'Show help about initdb command line arguments... [See Man Page]'
complete -c initdb -l 'encoding.' --description 'Section 22'

