# innochecksum: Deroffing man parser
# Autogenerated from man pages
complete -c innochecksum -s c
complete -c innochecksum -s d
complete -c innochecksum -s e
complete -c innochecksum -s p
complete -c innochecksum -s s
complete -c innochecksum -s v

