# install-info: Deroffing man parser
# Autogenerated from man pages
complete -c install-info -l delete --description 'delete existing entries for INFO-FILE from DI... [See Man Page]'
complete -c install-info -l dir-file --description 'specify file name of Info directory file'
complete -c install-info -l entry --description 'insert TEXT as an Info directory entry'
complete -c install-info -l help --description 'display this help and exit'
complete -c install-info -l info-file --description 'specify Info file to install in the directory... [See Man Page]'
complete -c install-info -l info-dir --description 'same as --dir-file=DIR/dir'
complete -c install-info -l item --description 'same as --entry TEXT'
complete -c install-info -l quiet --description 'suppress warnings'
complete -c install-info -l remove --description 'same as --delete'
complete -c install-info -l section --description 'put this file\'s entries in section SEC of the... [See Man Page]'
complete -c install-info -l version --description 'display version information and exit'

