# install: Darwin man parser
# Autogenerated from man pages
complete -c install -s B --description Use
complete -c install -s b --description 'Back up any existing files before overwriting... [See Man Page]'
complete -c install -s C --description 'Copy the file'
complete -c install -s c --description 'Copy the file'
complete -c install -s d --description 'Create directories'
complete -c install -s f --description 'Specify the target\'s file flags; see'
complete -c install -s g --description 'Specify a group'
complete -c install -s M --description 'Disable all use of'
complete -c install -s m --description 'Specify an alternate mode'
complete -c install -s o --description 'Specify an owner'
complete -c install -s p --description 'Preserve the modification time'
complete -c install -s S --description 'Safe copy'
complete -c install -s s
complete -c install -s v --description Causes

