# install_name_tool: Deroffing man parser
# Autogenerated from man pages
complete -c install_name_tool -o change --description 'Changes the dependent shared library install ... [See Man Page]'
complete -c install_name_tool -o id --description 'Changes the shared library identification nam... [See Man Page]'
complete -c install_name_tool -o rpath --description 'Changes the rpath path name  old to  new in t... [See Man Page]'
complete -c install_name_tool -o add_rpath --description 'Adds the rpath path name  new in the specifie... [See Man Page]'
complete -c install_name_tool -o headerpad_max_install_names --description option
complete -c install_name_tool -o delete_rpath --description 'deletes the rpath path name old in the specif... [See Man Page]'

