# iodbc-config: Deroffing man parser
# Autogenerated from man pages
complete -c iodbc-config -l version --description 'Print the currently installed version of iODB... [See Man Page]'
complete -c iodbc-config -l cflags --description 'Print the compiler flags that are necessary t... [See Man Page]'
complete -c iodbc-config -l libs --description 'Print the linker flags that are necessary to ... [See Man Page]'
complete -c iodbc-config -l static-libs --description 'Print the linker flags that are necessary to ... [See Man Page]'
complete -c iodbc-config -l libtool-libs --description 'Print the linker flags that are necessary to ... [See Man Page]'
complete -c iodbc-config -l odbcini --description 'Print the path of the system wide odbc'
complete -c iodbc-config -l odbcinstini --description 'Print the path of the system wide odbcinst'
complete -c iodbc-config -l 'prefix[' --description 'If specified, use PREFIX instead of the insta... [See Man Page]'
complete -c iodbc-config -l exec-prefix --description 'If specified, use PREFIX instead of the insta... [See Man Page]'

