# iopattern: Deroffing man parser
# Autogenerated from man pages
complete -c iopattern -s v --description 'print timestamp, string'
complete -c iopattern -s d --description 'instance name to snoop (eg, dad0)'
complete -c iopattern -s f --description 'full pathname of file to snoop'
complete -c iopattern -s m --description 'mountpoint for filesystem to snoop EXAMPLES'

