# iopending: Deroffing man parser
# Autogenerated from man pages
complete -c iopending -s c --description 'clear screen'
complete -c iopending -s d --description 'instance name to snoop (eg, dad0)'
complete -c iopending -s f --description 'full pathname of file to snoop'
complete -c iopending -s m --description 'mountpoint for filesystem to snoop EXAMPLES'

