# iosnoop: Deroffing man parser
# Autogenerated from man pages
complete -c iosnoop -s a --description 'print all data'
complete -c iosnoop -s A --description 'dump all data, space delimited'
complete -c iosnoop -s D --description 'print time delta, us (elapsed)'
complete -c iosnoop -s e --description 'print device name'
complete -c iosnoop -s i --description 'print device instance'
complete -c iosnoop -s n --description 'print major and minor numbers'
complete -c iosnoop -s o --description 'print disk delta time, us'
complete -c iosnoop -s s --description 'print start time, us'
complete -c iosnoop -s t --description 'print completion time, us'
complete -c iosnoop -s v --description 'print completion time, string'
complete -c iosnoop -s d --description 'instance name to snoop (eg, dad0)'
complete -c iosnoop -s f --description 'full pathname of file to snoop'
complete -c iosnoop -s m --description 'mountpoint for filesystem to snoop'
complete -c iosnoop -s p --description 'process ID'

