# iotop: Deroffing man parser
# Autogenerated from man pages
complete -c iotop -s C --description 'don\'t clear the screen'
complete -c iotop -s D --description 'print delta times - elapsed, us'
complete -c iotop -s j --description 'print project ID'
complete -c iotop -s o --description 'print disk delta times, us'
complete -c iotop -s P --description 'print %I/O (disk delta times)'
complete -c iotop -s Z --description 'print zone ID'
complete -c iotop -s d --description 'instance name to snoop (eg, dad0)'
complete -c iotop -s f --description 'full pathname of file to snoop'
complete -c iotop -s m --description 'mountpoint for filesystem to snoop'
complete -c iotop -s t --description 'print top number only'

