# ipcrm: Darwin man parser
# Autogenerated from man pages
complete -c ipcrm -s M --description 'Mark the shared memory segment associated wit... [See Man Page]'
complete -c ipcrm -s m --description 'Mark the shared memory segment associated wit... [See Man Page]'
complete -c ipcrm -s Q --description 'Remove the message queue associated with key ... [See Man Page]'
complete -c ipcrm -s q --description 'Remove the message queue associated with the ... [See Man Page]'
complete -c ipcrm -s S --description 'Remove the semaphore set associated with key'
complete -c ipcrm -s s --description 'Removes the semaphore set associated with id'

