# ipcs: Darwin man parser
# Autogenerated from man pages
complete -c ipcs -s a --description 'Show the maximum amount of information possib... [See Man Page]'
complete -c ipcs -s b --description 'Show the maximum allowed sizes for active sem... [See Man Page]'
complete -c ipcs -s c --description 'Show the creator\'s name and group for active ... [See Man Page]'
complete -c ipcs -s M --description 'Display system information about shared memor... [See Man Page]'
complete -c ipcs -s m --description 'Display information about active shared memor... [See Man Page]'
complete -c ipcs -s o --description 'Show outstanding usage for active message que... [See Man Page]'
complete -c ipcs -s p --description 'Show the process ID information for active se... [See Man Page]'
complete -c ipcs -s Q --description 'Display system information about messages que... [See Man Page]'
complete -c ipcs -s q --description 'Display information about active message queu... [See Man Page]'
complete -c ipcs -s S --description 'Display system information about semaphores'
complete -c ipcs -s s --description 'Display information about active semaphores'
complete -c ipcs -s T --description 'Display system information about shared memor... [See Man Page]'
complete -c ipcs -s t --description 'Show access times for active semaphores, mess... [See Man Page]'

