# irb: Darwin man parser
# Autogenerated from man pages
complete -c irb -l -version --description 'Prints the version of'
complete -c irb -s E
complete -c irb -l -encoding --description 'Same as `ruby -E\' '
complete -c irb -s I --description 'Same as `ruby -I\' '
complete -c irb -s U --description 'Same as `ruby -U\' '
complete -c irb -s d --description 'Same as `ruby -d\' '
complete -c irb -s f --description 'Suppresses read of'
complete -c irb -s h
complete -c irb -l -help --description 'Prints a summary of the options'
complete -c irb -s m --description 'Bc mode (load mathn, fraction or matrix are a... [See Man Page]'
complete -c irb -s r --description 'Same as `ruby -r\''
complete -c irb -l -inspect --description 'Uses `inspect\' for output (default except for... [See Man Page]'
complete -c irb -l -noinspect --description 'Doesn\'t use inspect for output'
complete -c irb -l -readline --description 'Uses Readline extension module'
complete -c irb -l -noreadline --description 'Doesn\'t use Readline extension module'
complete -c irb -l -prompt
complete -c irb -l -prompt-mode --description 'Switch prompt mode'
complete -c irb -l -inf-ruby-mode --description 'Uses prompt appropriate for inf-ruby-mode on ... [See Man Page]'
complete -c irb -l -simple-prompt --description 'Makes prompts simple'
complete -c irb -l -noprompt --description 'No prompt mode'
complete -c irb -l -tracer --description 'Displays trace for each execution of commands... [See Man Page]'
complete -c irb -l -back-trace-limit --description 'Displays backtrace top'
complete -c irb -l -irb_debug --description 'Sets internal debug level to n (not for popul... [See Man Page]'

