# isc-config: Deroffing man parser
# Autogenerated from man pages
complete -c isc-config -l cflags --description 'Prints the compiler command line options requ... [See Man Page]'
complete -c isc-config -l exec-prefix --description 'Prints the directory prefix used in the ISC B... [See Man Page]'
complete -c isc-config -l libs --description 'Prints the linker command line options used t... [See Man Page]'
complete -c isc-config -l prefix --description 'Prints the directory prefix used in the ISC B... [See Man Page]'
complete -c isc-config -l version --description 'Prints the version of the installed ISC BIND ... [See Man Page]'

