# jarsigner: Deroffing man parser
# Autogenerated from man pages
complete -c jarsigner -o keystore --description 'Specifies the URL that tells the keystore loc... [See Man Page]'
complete -c jarsigner -o storetype --description 'Specifies the type of keystore to be instanti... [See Man Page]'
complete -c jarsigner -o storepass --description 'Specifies the password which is required to a... [See Man Page]'
complete -c jarsigner -o keypass --description 'Specifies the password used to protect the pr... [See Man Page]'
complete -c jarsigner -o sigfile --description 'Specifies the base file name to be used for t... [See Man Page]'
complete -c jarsigner -o signedjar --description 'Specifies the name to be used for the signed ... [See Man Page]'
complete -c jarsigner -o verify --description 'If this appears on the command line, the spec... [See Man Page]'
complete -c jarsigner -o certs --description 'If this appears on the command line, along wi... [See Man Page]'
complete -c jarsigner -o verbose --description 'If this appears on the command line, it indic... [See Man Page]'
complete -c jarsigner -o internalsf --description 'In the past, the   '
complete -c jarsigner -o sectionsonly --description 'If this appears on the command line, the   '
complete -c jarsigner -o provider --description 'Used to specify the name of the cryptographic... [See Man Page]'
complete -c jarsigner -o sigFile --description option
complete -c jarsigner -s J --description 'Passes the specified javaoption string direct... [See Man Page]'

