# java: Deroffing man parser
# Autogenerated from man pages
complete -c java -o client --description 'Selects the Java HotSpot Client '
complete -c java -o server --description 'Selects the Java HotSpot Server '
complete -c java -o 'agentlib:libname[' --description 'Load native agent library R libname , e'
complete -c java -o 'agentpath:pathname[' --description 'Load a native agent library by full pathname'
complete -c java -o cp
complete -c java -s D --description 'Sets a system property value'
complete -c java -o d32 -o d64 --description 'Specified whether the program is to be run in... [See Man Page]'
complete -c java -o ea --description 'Enable assertions'
complete -c java -o da --description 'Disable assertions'
complete -c java -o esa --description 'Enable asserts in all system classes (sets th... [See Man Page]'
complete -c java -o dsa --description 'Disables asserts in all system classes '
complete -c java -o jar --description 'Execute a program encapsulated in a JAR archi... [See Man Page]'
complete -c java -o 'javaagent:jarpath[' --description 'Load a Java programming language agent, see j... [See Man Page]'
complete -c java -o verbose: --description 'Displays information about each class loaded'
complete -c java -o verbose:gc --description 'Reports on each garbage collection event'
complete -c java -o verbose:jni --description 'Reports information about use of native metho... [See Man Page]'
complete -c java -o version --description 'Displays version information and exit'
complete -c java -o showversion --description 'Displays version information and continues'
complete -c java -o help --description 'Displays usage information and exit'
complete -c java -s X --description 'Displays information about non-standard optio... [See Man Page]'
complete -c java -o Xint --description 'Operates in interpreted-only mode'
complete -c java -o Xbatch --description 'Disable background compilation'
complete -c java -o Xdebug --description 'Start with support for JVMDI enabled'
complete -c java -o Xbootclasspath: --description 'Specify a colon-separated list of directories... [See Man Page]'
complete -c java -o Xbootclasspath/a: --description 'Specifies a colon-separated  path of director... [See Man Page]'
complete -c java -o Xbootclasspath/p: --description 'Specifies a colon-separated  path of director... [See Man Page]'
complete -c java -o Xcheck:jni --description 'Perform additional checks for Java Native Int... [See Man Page]'
complete -c java -o Xfuture --description 'Performs strict class-file format checks'
complete -c java -o Xnoclassgc --description 'Disables class garbage collection'
complete -c java -o Xincgc --description 'Enable the incremental garbage collector'
complete -c java -o Xloggc: --description 'Report on each garbage collection event, as w... [See Man Page]'
complete -c java -o Xms --description 'Specifies the initial size of the memory allo... [See Man Page]'
complete -c java -o Xmx --description 'Specifies the maximum size, in bytes, of the ... [See Man Page]'
complete -c java -o Xprof --description 'Profiles the running program, and sends profi... [See Man Page]'
complete -c java -o Xrs --description 'Reduce usage of operating-system signals by J... [See Man Page]'
complete -c java -o Xss --description 'Set thread stack size'
complete -c java -o agentlib:hprof
complete -c java -o agentlib:jdwp
complete -c java -o classpath
complete -c java -o enableassertions
complete -c java -o enablesystemassertions --description below
complete -c java -o disableassertions
complete -c java -o disablesystemassertions --description below
complete -c java -o verbose
complete -c java -s '?'
complete -c java -o Xms6291456
complete -c java -o Xms6144k
complete -c java -o Xms6m
complete -c java -o Xmx83886080
complete -c java -o Xmx81920k
complete -c java -o Xmx80m --description ' 20 On Mac OS X platforms, the upper limit fo... [See Man Page]'
complete -c java -o 'Xrunhprof[:help][:suboption' --description 'Enables cpu, heap, or monitor profiling'
complete -c java -o XX:+UseAltSigs --description 'The VM uses SIGUSR1 and SIGUSR2 by default,  ... [See Man Page]'

