# java_home: Deroffing man parser
# Autogenerated from man pages
complete -c java_home -s v -l version --description 'Filters the returned JVMs by the major platfo... [See Man Page]'
complete -c java_home -s a -l arch --description 'Filters the returned JVMs by the architecture... [See Man Page]'
complete -c java_home -s d -l datamodel --description 'Filters the returned JVMs capable of running ... [See Man Page]'
complete -c java_home -s t -l task --description 'Selects from the list of JVMs which can run a... [See Man Page]'
complete -c java_home -s F -l failfast --description 'Immediately fails when filters return no JVMs... [See Man Page]'
complete -c java_home -l exec --description 'Executes the command at $JAVA_HOME/bin/<comma... [See Man Page]'
complete -c java_home -s X -l xml --description 'Prints the list of selected JVMs and associat... [See Man Page]'
complete -c java_home -s V -l verbose --description 'Prints the matching list of JVMs and architec... [See Man Page]'
complete -c java_home -s h -l help --description 'Brief usage information'

