# javah: Deroffing man parser
# Autogenerated from man pages
complete -c javah -s o --description 'Concatenates the resulting header or source f... [See Man Page]'
complete -c javah -o bootclasspath --description 'Specifies path from which to load bootstrap c... [See Man Page]'
complete -c javah -o classpath --description 'Specifies the path   javah  uses to look up c... [See Man Page]'
complete -c javah -s d --description 'Sets the directory where   javah  saves the h... [See Man Page]'
complete -c javah -o force --description 'Specifies that output files should always be ... [See Man Page]'
complete -c javah -o help --description 'Prints help message for   javah usage'
complete -c javah -o jni --description 'Causes   javah  to create an output file cont... [See Man Page]'
complete -c javah -o old --description 'Specifies the old JDK1'
complete -c javah -o stubs --description 'Causes   javah  to generate C declarations fr... [See Man Page]'
complete -c javah -o trace --description 'Tracing is no longer supported'
complete -c javah -o verbose --description 'Indicates verbose output and causes   javah  ... [See Man Page]'
complete -c javah -o version --description 'Print out javah version information'
complete -c javah -o verbose:jni --description 'option of the virtual machine'
complete -c javah -s J --description 'Pass option to the Java virtual machine, wher... [See Man Page]'
complete -c javah -o J-Xms48m --description 'sets the startup memory to 48 megabytes'

