# jconsole: Deroffing man parser
# Autogenerated from man pages
complete -c jconsole -o interval --description 'Set the update interval to \\f2n seconds (defa... [See Man Page]'
complete -c jconsole -o notile --description 'Do not tile windows initially (for two or mor... [See Man Page]'
complete -c jconsole -o version --description 'Output version information abd exit'
complete -c jconsole -o help --description 'Output help message and exit'

