# jdb: Deroffing man parser
# Autogenerated from man pages
complete -c jdb -o sourcepath --description 'Uses the given path in searching for source f... [See Man Page]'
complete -c jdb -o attach --description 'Attaches the debugger to previously running V... [See Man Page]'
complete -c jdb -o launch --description 'Launches the debugged application immediately... [See Man Page]'
complete -c jdb -o Xrunjdwp:transport --description 'server=y,suspend=n T}	T{'
complete -c jdb -s D
complete -c jdb -o classpath --description and
complete -c jdb -s X
complete -c jdb -s J --description 'Pass option to the Java virtual machine, wher... [See Man Page]'
complete -c jdb -o J-Xms48m --description 'sets the startup memory to 48 megabytes'

