# jhat: Type1
# Autogenerated from man pages
complete -c jhat -o stack --description 'Turn off tracking object allocation call stac... [See Man Page]'
complete -c jhat -o refs --description 'Turn off tracking of references to objects'
complete -c jhat -o port --description 'Set the port for the jhat\'s HTTP server'
complete -c jhat -o exclude --description 'Specify a file that lists data members that s... [See Man Page]'
complete -c jhat -o baseline --description 'Specify a baseline heap dump'
complete -c jhat -o debug --description 'Set debug level for this tool'
complete -c jhat -o version --description 'Report version number and exit'
complete -c jhat -s h --description 'Output help message and exit'
complete -c jhat -o help --description 'Output help message and exit'

