# jinfo: Deroffing man parser
# Autogenerated from man pages
complete -c jinfo -o flags --description 'prints command line flags as name, value pair... [See Man Page]'
complete -c jinfo -o sysprops --description 'prints JavaSystem properties as name, value p... [See Man Page]'
complete -c jinfo -s h --description 'prints a help message '
complete -c jinfo -o help --description 'prints a help message SEE ALSO jps (1) jsadeb... [See Man Page]'

