# jmap: Deroffing man parser
# Autogenerated from man pages
complete -c jmap -o heap --description 'Prints a heap summary'
complete -c jmap -o histo --description 'Prints a histogram of the heap'
complete -c jmap -o permstat --description 'Prints class loader wise statistics of perman... [See Man Page]'
complete -c jmap -s h --description 'Prints a help message'
complete -c jmap -o help --description 'Prints a help message'

