# join: Darwin man parser
# Autogenerated from man pages
complete -c join -s a --description 'In addition to the default output, produce a ... [See Man Page]'
complete -c join -s e --description 'Replace empty output fields with'
complete -c join -s o --description The
complete -c join -s t --description 'Use character'
complete -c join -s v --description 'Do not display the default output, but displa... [See Man Page]'
complete -c join -s 1 --description 'Join on the'
complete -c join -s 2 --description 'Join on the'
complete -c join -l j1 --description 'Join on the'
complete -c join -l j2 --description 'Join on the'
complete -c join -s j --description 'Join on the'

