# jot: Darwin man parser
# Autogenerated from man pages
complete -c jot -s r --description 'Generate random data instead of the default s... [See Man Page]'
complete -c jot -s b --description 'Just print'
complete -c jot -s w --description Print
complete -c jot -s c --description 'This is an abbreviation for'
complete -c jot -s s --description 'Print data separated by'
complete -c jot -s n --description 'Do not print the final newline normally appen... [See Man Page]'
complete -c jot -s p --description 'Print only as many digits or characters of th... [See Man Page]'

