# jpegicc: Deroffing man parser
# Autogenerated from man pages
complete -c jpegicc -s b --description 'Black point compensation'
complete -c jpegicc -s c --description 'Precalculates transform'
complete -c jpegicc -s g --description 'Marks out-of-gamut colors on softproof'
complete -c jpegicc -s h --description 'Show summary of options and examples'
complete -c jpegicc -s i --description 'Input profile (defaults to sRGB)'
complete -c jpegicc -s m --description 'SoftProof intent'
complete -c jpegicc -s n --description 'Ignore embedded profile'
complete -c jpegicc -s p --description 'Soft proof profile'
complete -c jpegicc -s o
complete -c jpegicc -s q --description 'Output JPEG quality'
complete -c jpegicc -s t --description 'Intent (0=Perceptual, 1=Colorimetric, 2=Satur... [See Man Page]'
complete -c jpegicc -s v --description Verbose

