# jpegtran: Deroffing man parser
# Autogenerated from man pages
complete -c jpegtran -o optimize --description 'Perform optimization of entropy encoding para... [See Man Page]'
complete -c jpegtran -o progressive --description 'Create progressive JPEG file'
complete -c jpegtran -o restart --description 'Emit a JPEG restart marker every N MCU rows, ... [See Man Page]'
complete -c jpegtran -o arithmetic --description 'Use arithmetic coding'
complete -c jpegtran -o scans --description 'Use the scan script given in the specified te... [See Man Page]'
complete -c jpegtran -o flip --description 'Mirror image horizontally (left-right)'
complete -c jpegtran -o rotate --description 'Rotate image 90 degrees clockwise'
complete -c jpegtran -o transpose --description 'Transpose image (across UL-to-LR axis)'
complete -c jpegtran -o transverse --description 'Transverse transpose (across UR-to-LL axis)'
complete -c jpegtran -o trim --description 'Drop non-transformable edge blocks'
complete -c jpegtran -o perfect --description 'Fails with an error if the transformation is ... [See Man Page]'
complete -c jpegtran -o rot --description foo
complete -c jpegtran -o crop --description 'Crop to a rectangular subarea of width W, hei... [See Man Page]'
complete -c jpegtran -o grayscale --description 'Force grayscale output'
complete -c jpegtran -o scale --description 'Scale the output image by a factor M/N'
complete -c jpegtran -o copy --description 'Copy no extra markers from source file'
complete -c jpegtran -o maxmemory --description 'Set limit for amount of memory to use in proc... [See Man Page]'
complete -c jpegtran -o outfile --description 'Send output image to the named file, not to s... [See Man Page]'
complete -c jpegtran -o verbose --description 'Enable debug printout'
complete -c jpegtran -o opt --description or
complete -c jpegtran -s o --description 'Upper and lower case are equivalent'
complete -c jpegtran -o optimise --description 'though for brevity these are not mentioned be... [See Man Page]'
complete -c jpegtran -o max --description 'selects 4000000 bytes'
complete -c jpegtran -s v --description 'give more output'
complete -c jpegtran -o debug --description 'Same as'

