# jps: Deroffing man parser
# Autogenerated from man pages
complete -c jps -s q --description 'Suppress the output of the class name, JAR fi... [See Man Page]'
complete -c jps -s m --description 'Output the arguments passed to the main metho... [See Man Page]'
complete -c jps -s l --description 'Output the full package name for the applicat... [See Man Page]'
complete -c jps -s v --description 'Output the arguments passed to the JVM'
complete -c jps -s V --description 'Output the arguments passed to the JVM throug... [See Man Page]'
complete -c jps -s J --description 'Pass option to the java launcher called by ja... [See Man Page]'
complete -c jps -o J-Xms48m --description 'sets the startup memory to 48 megabytes'

