# jrunscript: Type1
# Autogenerated from man pages
complete -c jrunscript -o classpath --description 'Specify where to find the user\'s '
complete -c jrunscript -o cp --description 'This is a synonym for \\f3-classpath \\f2path'
complete -c jrunscript -s D --description 'Set a Java system property'
complete -c jrunscript -s J --description 'Pass \\f2flag directly to the Java virtual mac... [See Man Page]'
complete -c jrunscript -s l --description 'Use the specified scripting language'
complete -c jrunscript -s e --description 'Evaluate the given script'
complete -c jrunscript -o encoding --description 'Specify the character encoding used while rea... [See Man Page]'
complete -c jrunscript -s f --description 'Evaluate the given script file (batch mode)'
complete -c jrunscript -o help --description 'Output help message and exit'
complete -c jrunscript -s '?' --description 'Output help message and exit'

