# jstat: Deroffing man parser
# Autogenerated from man pages
complete -c jstat -o help --description 'Display help message'
complete -c jstat -o version --description 'Display version information'
complete -c jstat -o options --description 'Display list of statistics options'
complete -c jstat -o statOption --description 'Determines the statistics information that js... [See Man Page]'
complete -c jstat -s h --description 'Display a column header every n samples (outp... [See Man Page]'
complete -c jstat -s t --description 'Display a timestamp column as the first colum... [See Man Page]'
complete -c jstat -s J --description 'Pass \\f2javaOption to the java application la... [See Man Page]'
complete -c jstat -o gcutil --description 'jstat -gcutil 21891 250 7   S0     S1     E  ... [See Man Page]'

