# jstatd: Deroffing man parser
# Autogenerated from man pages
complete -c jstatd -o nr --description 'Do not attempt to create an internal RMI regi... [See Man Page]'
complete -c jstatd -s p --description 'Port number where the RMI registry is expecte... [See Man Page]'
complete -c jstatd -s n --description 'Name to which the remote RMI object is bound ... [See Man Page]'
complete -c jstatd -s J --description 'Pass option to the java launcher called by ja... [See Man Page]'

