# jstack: Deroffing man parser
# Autogenerated from man pages
complete -c jstack -s m --description 'prints mixed mode (both Java and native C/C++... [See Man Page]'
complete -c jstack -s h --description 'Prints a help message'
complete -c jstack -o help --description 'Prints a help message'

