# kdestroy: Darwin man parser
# Autogenerated from man pages
complete -c kdestroy -l credential --description remove
complete -c kdestroy -s p
complete -c kdestroy -l principal --description 'The cache with client principal to remove'
complete -c kdestroy -s c
complete -c kdestroy -l cache --description 'The cache file to remove'
complete -c kdestroy -s A
complete -c kdestroy -s a
complete -c kdestroy -l -all --description 'remove all credential caches'
complete -c kdestroy -l -no-unlog --description 'Do not remove AFS tokens'
complete -c kdestroy -l -no-delete-v4 --description 'Do not remove v4 tickets'

