# keytool: Deroffing man parser
# Autogenerated from man pages
complete -c keytool -o identitydb --description subcommand
complete -c keytool -o genkey --description 'subcommand to generate a key pair (public and... [See Man Page]'
complete -c keytool -o import --description 'subcommand to add a certificate or certificat... [See Man Page]'
complete -c keytool -o keystore --description 'option for specifying the name and location o... [See Man Page]'
complete -c keytool -o storetype --description option
complete -c keytool -o keyalg --description 'and '
complete -c keytool -o sigalg --description 'options for various subcommands must be suppo... [See Man Page]'
complete -c keytool -o dname --description 'option, as for the'
complete -c keytool -o selfcert --description 'subcommands, the string must be in the follow... [See Man Page]'
complete -c keytool -o printcert --description 'subcommands can be in either this format or b... [See Man Page]'
complete -c keytool -o export --description 'subcommand by default outputs a certificate i... [See Man Page]'
complete -c keytool -o rfc --description 'option is specified'
complete -c keytool -o list --description 'subcommand by default prints the MD5 fingerpr... [See Man Page]'
complete -c keytool -s v --description 'option is specified, the certificate is print... [See Man Page]'
complete -c keytool -l ---BEGIN --description 'and at the end by'
complete -c keytool -l ---END --description 'Certificate Chains'
complete -c keytool -o certreq --description 'subcommand) and sent to a Certification Autho... [See Man Page]'
complete -c keytool -o alias --description option
complete -c keytool -o noprompt --description 'option), and make sure that the displayed cer... [See Man Page]'
complete -c keytool -o keyclone
complete -c keytool -o delete
complete -c keytool -s J --description 'options, which only have meaning if they appe... [See Man Page]'
complete -c keytool -o keypass --description 'option, if you do not specify the option on t... [See Man Page]'
complete -c keytool -o help --description 'subcommand is the default'
complete -c keytool -o keysize
complete -c keytool -o validity
complete -c keytool -o file --description 'The signature algorithm ('
complete -c keytool -o javaoption --description 'string is passed through directly to the Java... [See Man Page]'
complete -c keytool -o storepass --description 'The password which is used to protect the int... [See Man Page]'
complete -c keytool -o provider --description 'Used to specify the name of the cryptographic... [See Man Page]'
complete -c keytool -o trustcacerts --description 'option has been specified, additional certifi... [See Man Page]'
complete -c keytool -o keypasswd --description 'keytool command option'
complete -c keytool -o new --description 'option is supplied at the command line, the u... [See Man Page]'
complete -c keytool -o storepasswd

