# killall: Darwin man parser
# Autogenerated from man pages
complete -c killall -s d --description 'Be more verbose about what will be done'
complete -c killall -s e --description 'Use the effective user ID instead of the (def... [See Man Page]'
complete -c killall -l help --description 'Give a help on the command usage and exit'
complete -c killall -s l --description 'List the names of the available signals and e... [See Man Page]'
complete -c killall -s m --description 'Match the argument'
complete -c killall -s s --description 'Show only what would be done, but do not send... [See Man Page]'
complete -c killall -l SIGNAL --description 'Send a different signal instead of the defaul... [See Man Page]'
complete -c killall -s u --description 'Limit potentially matching processes to those... [See Man Page]'
complete -c killall -s t --description 'Limit potentially matching processes to those... [See Man Page]'
complete -c killall -s c --description 'When used with the'
complete -c killall -s z --description 'Do not skip zombies'

