# kill: Darwin man parser
# Autogenerated from man pages
complete -c kill -s s --description 'A symbolic signal name specifying the signal ... [See Man Page]'
complete -c kill -s l --description 'If no operand is given, list the signal names... [See Man Page]'
complete -c kill -l signal_name --description 'A symbolic signal name specifying the signal ... [See Man Page]'
complete -c kill -l signal_number --description 'A non-negative decimal integer, specifying th... [See Man Page]'

