# krb5-config: Darwin man parser
# Autogenerated from man pages
complete -c krb5-config -l -prefix --description 'Print the prefix if no'
complete -c krb5-config -l -exec-prefix --description 'Print the exec-prefix if no'
complete -c krb5-config -l -libs --description 'Output the set of libraries that should be li... [See Man Page]'
complete -c krb5-config -l -cflags --description 'Output the set of flags to give to the C comp... [See Man Page]'

