# lam: Darwin man parser
# Autogenerated from man pages
complete -c lam -s f --description 'Print line fragments according to the format ... [See Man Page]'
complete -c lam -s p --description Like
complete -c lam -s s --description Print
complete -c lam -s t --description 'The input line terminator is'

