# languagesetup: Darwin man parser
# Autogenerated from man pages
complete -c languagesetup -s a --description 'Description of -a flag'
complete -c languagesetup -s b --description 'Description of -b flag'

