# latency: Darwin man parser
# Autogenerated from man pages
complete -c latency -s c --description 'When the'
complete -c latency -s h --description 'Display high resolution interrupt latencies a... [See Man Page]'
complete -c latency -s m --description 'Display per-CPU interrupt latency statistics'
complete -c latency -l it --description 'Set the interrupt latency threshold,expressed... [See Man Page]'
complete -c latency -s l --description 'Specifies a log file that is written to whene... [See Man Page]'
complete -c latency -s n --description 'By default,'
complete -c latency -s p --description 'Specifies the priority level to observe sched... [See Man Page]'
complete -c latency -l st --description 'Set the scheduler latency threshold in micros... [See Man Page]'
complete -c latency -s R --description 'Specifies a raw trace file to use as input'

