# launchctl: Darwin man parser
# Autogenerated from man pages
complete -c launchctl -s w --description 'Overrides the Disabled key and sets it to fal... [See Man Page]'
complete -c launchctl -s F --description 'Force the loading of the plist'
complete -c launchctl -s S --description 'Some jobs only make sense in certain contexts... [See Man Page]'
complete -c launchctl -s D --description 'Look for'
complete -c launchctl -s l --description 'What unique label to assign this job to launc... [See Man Page]'
complete -c launchctl -s p --description 'What program to really execute, regardless of... [See Man Page]'
complete -c launchctl -s o --description 'Where to send the stdout of the program'
complete -c launchctl -s e --description 'Where to send the stderr of the program'

