# ldapurl: Deroffing man parser
# Autogenerated from man pages
complete -c ldapurl -s a --description 'Set a comma-separated list of attribute selec... [See Man Page]'
complete -c ldapurl -s b --description 'Set the searchbase'
complete -c ldapurl -s E --description 'Specify general extensions with -e and search... [See Man Page]'
complete -c ldapurl -s f --description 'Set the URL filter'
complete -c ldapurl -s H --description 'Specify URI to be exploded'
complete -c ldapurl -s h --description 'Set the host'
complete -c ldapurl -s p --description 'Set the TCP port'
complete -c ldapurl -s S --description 'Set the URL scheme'
complete -c ldapurl -s s --description OPTIONS
complete -c ldapurl -s e

