# ldapwhoami: Deroffing man parser
# Autogenerated from man pages
complete -c ldapwhoami -s n --description 'Show what would be done, but don\'t actually p... [See Man Page]'
complete -c ldapwhoami -s v --description 'Run in verbose mode, with many diagnostics wr... [See Man Page]'
complete -c ldapwhoami -s d --description 'Set the LDAP debugging level to debuglevel'
complete -c ldapwhoami -s x --description 'Use simple authentication instead of SASL'
complete -c ldapwhoami -s D --description 'Use the Distinguished Name binddn to bind to ... [See Man Page]'
complete -c ldapwhoami -s W --description 'Prompt for simple authentication'
complete -c ldapwhoami -s w --description 'Use passwd as the password for simple authent... [See Man Page]'
complete -c ldapwhoami -s y --description 'Use complete contents of passwdfile as the pa... [See Man Page]'
complete -c ldapwhoami -s H --description 'Specify URI(s) referring to the ldap server(s... [See Man Page]'
complete -c ldapwhoami -s h --description 'Specify an alternate host on which the ldap s... [See Man Page]'
complete -c ldapwhoami -s p --description 'Specify an alternate TCP port where the ldap ... [See Man Page]'
complete -c ldapwhoami -s O --description 'Specify SASL security properties'
complete -c ldapwhoami -s E --description 'Specify general extensions with -e and search... [See Man Page]'
complete -c ldapwhoami -s I --description 'Enable SASL Interactive mode'
complete -c ldapwhoami -s Q --description 'Enable SASL Quiet mode'
complete -c ldapwhoami -s U --description 'Specify the authentication ID for SASL bind'
complete -c ldapwhoami -s R --description 'Specify the realm of authentication ID for SA... [See Man Page]'
complete -c ldapwhoami -s X --description 'Specify the requested authorization ID for SA... [See Man Page]'
complete -c ldapwhoami -s Y --description 'Specify the SASL mechanism to be used for aut... [See Man Page]'
complete -c ldapwhoami -s e
complete -c ldapwhoami -s Z --description 'Issue StartTLS (Transport Layer Security) ext... [See Man Page]'
complete -c ldapwhoami -o ZZ --description EXAMPLE

