# leaks: Darwin man parser
# Autogenerated from man pages
complete -c leaks -l nocontext --description 'Do not print the string or hex representation... [See Man Page]'
complete -c leaks -l nostacks --description 'Do not print backtraces of leaked blocks even... [See Man Page]'
complete -c leaks -l exclude --description 'Exclude leaked blocks whose backtraces includ... [See Man Page]'

