# lessecho: Deroffing man parser
# Autogenerated from man pages
complete -c lessecho -o ox --description 'Specifies "x" to be the open quote character'
complete -c lessecho -o cx --description 'Specifies "x" to be the close quote character... [See Man Page]'
complete -c lessecho -o pn --description 'Specifies "n" to be the open quote character,... [See Man Page]'
complete -c lessecho -o dn --description 'Specifies "n" to be the close quote character... [See Man Page]'
complete -c lessecho -o mx --description 'Specifies "x" to be a metachar'
complete -c lessecho -o nn --description 'Specifies "n" to be a metachar, as an integer... [See Man Page]'
complete -c lessecho -o ex --description 'Specifies "x" to be the escape char for metac... [See Man Page]'
complete -c lessecho -o fn --description 'Specifies "n" to be the escape char for metac... [See Man Page]'
complete -c lessecho -s a --description 'Specifies that all arguments are to be quoted... [See Man Page]'

