# libtool: Deroffing man parser
# Autogenerated from man pages
complete -c libtool -o static --description 'Produce a statically linked (archive) library... [See Man Page]'
complete -c libtool -o dynamic --description 'Produce a dynamically linked shared library f... [See Man Page]'
complete -c libtool -o install_name --description 'For a dynamic shared library, this specifies ... [See Man Page]'
complete -c libtool -o compatibility_version --description 'For a dynamic shared library, this specifies ... [See Man Page]'
complete -c libtool -o current_version --description 'For dynamic shared library files this specifi... [See Man Page]'
complete -c libtool -o noall_load --description 'For dynamic shared library files this specifi... [See Man Page]'
complete -c libtool -s v --description 'Verbose mode, which prints the R ld (1) comma... [See Man Page]'
complete -c libtool -s V --description 'Print the version of libtool'
complete -c libtool -o filelist --description 'The  listfile contains a list of file names a... [See Man Page]'
complete -c libtool -o arch_only --description 'This option causes libtool to build a library... [See Man Page]'
complete -c libtool -s s --description 'Produce the preferred type of table of conten... [See Man Page]'
complete -c libtool -s a --description 'Produce the original type of table of content... [See Man Page]'
complete -c libtool -s c --description 'Include common symbols as definitions with re... [See Man Page]'
complete -c libtool -s L --description 'Use the 4'
complete -c libtool -s T --description 'Truncate archive member names to 16 character... [See Man Page]'
complete -c libtool -s f --description 'Warns when the output archive is universal an... [See Man Page]'
complete -c libtool -s q --description 'Do nothing if a universal file would be creat... [See Man Page]'
complete -c libtool -s t --description 'This option used to request that   ranlib onl... [See Man Page]'
complete -c libtool -s o --description 'flag)'
complete -c libtool -o 'static.' --description 'DYNAMICALLY LINKED SHARED LIBRARIES'
complete -c libtool -o dylib --description 'once for each architecture present in the inp... [See Man Page]'
complete -c libtool -o dynamiclib --description option
complete -c libtool -s l
complete -c libtool -o weak-l
complete -c libtool -o search_paths_first
complete -c libtool -o weak_library
complete -c libtool -s y
complete -c libtool -s u
complete -c libtool -o init
complete -c libtool -s i
complete -c libtool -o seg1addr
complete -c libtool -o segs_read_only_addr
complete -c libtool -o segs_read_write_addr
complete -c libtool -o seg_addr_table
complete -c libtool -o seg_addr_table_filename
complete -c libtool -o segprot
complete -c libtool -o segalign
complete -c libtool -o sectcreate
complete -c libtool -o sectorder
complete -c libtool -o sectorder_detail
complete -c libtool -o sectalign
complete -c libtool -o undefined
complete -c libtool -o read_only_relocs
complete -c libtool -o prebind
complete -c libtool -o prebind_all_twolevel_modules
complete -c libtool -o prebind_allow_overlap
complete -c libtool -o noprebind
complete -c libtool -o framework
complete -c libtool -o weak_framework
complete -c libtool -o umbrella
complete -c libtool -o allowable_client
complete -c libtool -o sub_umbrella
complete -c libtool -o sub_library
complete -c libtool -s F
complete -c libtool -s U
complete -c libtool -s Y
complete -c libtool -o Sn
complete -c libtool -o Si
complete -c libtool -o Sp
complete -c libtool -s S
complete -c libtool -s X
complete -c libtool -s x
complete -c libtool -o whyload
complete -c libtool -o 'all_load.'
complete -c libtool -o arch_errors_fatal
complete -c libtool -o dylib_file
complete -c libtool -o run_init_lazily
complete -c libtool -o final_output
complete -c libtool -o macosx_version_min
complete -c libtool -o multiply_defined
complete -c libtool -o multiply_defined_unused
complete -c libtool -o twolevel_namespace
complete -c libtool -o twolevel_namespace_hints
complete -c libtool -o flat_namespace
complete -c libtool -o nomultidefs
complete -c libtool -o headerpad
complete -c libtool -o headerpad_max_install_names
complete -c libtool -o weak_reference_mismatches
complete -c libtool -s M
complete -c libtool -o no_arch_warnings
complete -c libtool -o single_module
complete -c libtool -o multi_module
complete -c libtool -o exported_symbols_list
complete -c libtool -o unexported_symbols_list
complete -c libtool -s m
complete -c libtool -o dead_strip
complete -c libtool -o no_dead_strip_inits_and_terms
complete -c libtool -o executable_path
complete -c libtool -o syslibroot
complete -c libtool -o 'no_uuid.' --description 'See the ld (1) man page for details on these ... [See Man Page]'
complete -c libtool -o image_base --description 'is a synonym for'
complete -c libtool -o 'seg1addr.'
complete -c libtool -o force_cpusubtype_ALL --description 'flag and passes the'
complete -c libtool -o arch --description 'flag so that the output is tagged with that c... [See Man Page]'

