# link: Darwin man parser
# Autogenerated from man pages
complete -c link -s F --description 'If the target file already exists and is a di... [See Man Page]'
complete -c link -s h --description 'If the'
complete -c link -s f --description 'If the target file already exists,then unlink... [See Man Page]'
complete -c link -s i --description Cause
complete -c link -s n --description 'Same as'
complete -c link -s s --description 'Create a symbolic link'
complete -c link -s v --description Cause

