# link-parser: Deroffing man parser
# Autogenerated from man pages
complete -c link-parser -o pp
complete -c link-parser -s c
complete -c link-parser -s a
complete -c link-parser -o ppoff
complete -c link-parser -o coff
complete -c link-parser -o aoff
complete -c link-parser -o batch
complete -c link-parser -o '<special' --description USE

