# lkbib: Deroffing man parser
# Autogenerated from man pages
complete -c lkbib -s v --description 'Print the version number'
complete -c lkbib -s p --description 'Search R filename '
complete -c lkbib -s i --description 'When searching files for which no index exist... [See Man Page]'
complete -c lkbib -s t --description 'Only require the first n characters of keys t... [See Man Page]'

