# ln: Darwin man parser
# Autogenerated from man pages
complete -c ln -s F --description 'If the target file already exists and is a di... [See Man Page]'
complete -c ln -s h --description 'If the'
complete -c ln -s f --description 'If the target file already exists,then unlink... [See Man Page]'
complete -c ln -s i --description Cause
complete -c ln -s n --description 'Same as'
complete -c ln -s s --description 'Create a symbolic link'
complete -c ln -s v --description Cause

