# localedef: Darwin man parser
# Autogenerated from man pages
complete -c localedef -s c --description 'Create permanent output even if warning messa... [See Man Page]'
complete -c localedef -s f --description 'Specify the pathname of a file containing a m... [See Man Page]'
complete -c localedef -s i --description 'The pathname of a file containing the source ... [See Man Page]'

