# locate: Darwin man parser
# Autogenerated from man pages
complete -c locate -s 0 --description 'Print pathnames separated by an'
complete -c locate -s S --description 'Print some statistics about the database and ... [See Man Page]'
complete -c locate -s c --description 'Suppress normal output; instead print a count... [See Man Page]'
complete -c locate -s d --description 'Search in'
complete -c locate -s i --description 'Ignore case distinctions in both the pattern ... [See Man Page]'
complete -c locate -s l --description 'Limit output to'
complete -c locate -s m --description Use
complete -c locate -s s --description 'Use the'

