# locale: Darwin man parser
# Autogenerated from man pages
complete -c locale -s a --description 'Lists all public locales'
complete -c locale -s c --description 'Lists the category name before each keyword,u... [See Man Page]'
complete -c locale -s k --description 'Displays the name of each keyword prior to it... [See Man Page]'
complete -c locale -s m --description 'Lists all available public charmaps'

