# lockfile: Deroffing man parser
# Autogenerated from man pages
complete -c lockfile -o r-1 --description 'lockfile will retry forever'
complete -c lockfile -s '!' --description 'flag to invert the exit status'
complete -c lockfile -s f
complete -c lockfile -o ml --description and
complete -c lockfile -o mu --description respectively

