# logger: Darwin man parser
# Autogenerated from man pages
complete -c logger -s i --description 'Log the process id of the logger processwith ... [See Man Page]'
complete -c logger -s s --description 'Log the message to standard error, as well as... [See Man Page]'
complete -c logger -s f --description 'Log the specified file'
complete -c logger -s p --description 'Enter the message with the specified priority... [See Man Page]'
complete -c logger -s t --description 'Mark every line in the log with the specified... [See Man Page]'

