# login: Darwin man parser
# Autogenerated from man pages
complete -c login -s f --description 'When a user name is specified, this option in... [See Man Page]'
complete -c login -s h --description 'Specify the host from which the connection wa... [See Man Page]'
complete -c login -s l --description 'Tells the program executed by'
complete -c login -s p --description 'By default,'
complete -c login -s q --description 'This forces quiet logins, as if a'

