# lp: Deroffing man parser
# Autogenerated from man pages
complete -c lp -s E
complete -c lp -s U
complete -c lp -s c
complete -c lp -s d
complete -c lp -s h
complete -c lp -s i
complete -c lp -s m
complete -c lp -s n
complete -c lp -s o
complete -c lp -s q
complete -c lp -s s
complete -c lp -s t
complete -c lp -s H
complete -c lp -s P

