# lpoptions: Deroffing man parser
# Autogenerated from man pages
complete -c lpoptions -s E
complete -c lpoptions -s U
complete -c lpoptions -s d
complete -c lpoptions -s h
complete -c lpoptions -s l
complete -c lpoptions -s o
complete -c lpoptions -s p
complete -c lpoptions -s r
complete -c lpoptions -s x

