# lpr: Deroffing man parser
# Autogenerated from man pages
complete -c lpr -s E
complete -c lpr -s H
complete -c lpr -s T
complete -c lpr -s P
complete -c lpr -s U
complete -c lpr -s '#'
complete -c lpr -s h
complete -c lpr -s l
complete -c lpr -s m
complete -c lpr -s o
complete -c lpr -s p
complete -c lpr -s q
complete -c lpr -s C
complete -c lpr -s J
complete -c lpr -s r

