# macruby_deploy: Darwin man parser
# Autogenerated from man pages
complete -c macruby_deploy -l -compile --description 'Compile the bundle source code'
complete -c macruby_deploy -l -embed --description 'Embed MacRuby inside the bundle'
complete -c macruby_deploy -l -no-stdlib --description 'Do not embed the standard library (creates sm... [See Man Page]'
complete -c macruby_deploy -l -stdlib --description 'Embed only'
complete -c macruby_deploy -l -gem --description Embed
complete -c macruby_deploy -l -bs --description 'Embed the BridgeSupport system files'
complete -c macruby_deploy -l -verbose --description 'Log actions to standard out'
complete -c macruby_deploy -s v --description 'Display the version'

