# macrubyc: Darwin man parser
# Autogenerated from man pages
complete -c macrubyc -s a --description 'Compile for specified CPU architecture'
complete -c macrubyc -s c --description 'Compile and assemble, but do not link'
complete -c macrubyc -s C --description 'Compile, assemble, and link a loadable object... [See Man Page]'
complete -c macrubyc -l h --description 'Display a short description of the command li... [See Man Page]'
complete -c macrubyc -s o --description 'Place the output into'
complete -c macrubyc -l -dylib --description 'Create a dynamic library instead of an execut... [See Man Page]'
complete -c macrubyc -l -compatibility_version
complete -c macrubyc -l -current_version
complete -c macrubyc -l -install_name
complete -c macrubyc -l -static --description 'Create a standalone, static executable'
complete -c macrubyc -l -framework --description 'Use a given framework during compilation and ... [See Man Page]'
complete -c macrubyc -l -sdk --description 'Use a given SDK during compilation and link'
complete -c macrubyc -l v --description 'Display the version'
complete -c macrubyc -l V --description 'Print every command line executed by'

