# macruby: Darwin man parser
# Autogenerated from man pages
complete -c macruby -l -copyright --description 'Prints the copyright notice'
complete -c macruby -l -version --description 'Prints the version of Ruby interpreter'
complete -c macruby -s 0 --description '(The digit'
complete -c macruby -s C
complete -c macruby -s X --description 'Causes Ruby to switch to the directory'
complete -c macruby -s E
complete -c macruby -l -encoding --description 'Specifies the encoding for the program codes'
complete -c macruby -s F --description 'Specifies input field separator'
complete -c macruby -s I --description 'Used to tell Ruby where to load the library s... [See Man Page]'
complete -c macruby -s K --description 'Specifies KANJI (Japanese) encoding'
complete -c macruby -s S --description 'Makes Ruby use the'
complete -c macruby -s T --description 'Turns on taint checks at the specified level ... [See Man Page]'
complete -c macruby -s W --description 'Turns on verbose mode at the specified level,... [See Man Page]'
complete -c macruby -s a --description 'Turns on auto-split mode when used with'
complete -c macruby -s c --description 'Causes Ruby to check the syntax of the script... [See Man Page]'
complete -c macruby -s d
complete -c macruby -l -debug --description 'Turns on debug mode'
complete -c macruby -s e --description 'Specifies script from command-line while tell... [See Man Page]'
complete -c macruby -s h
complete -c macruby -l -help --description 'Prints a summary of the options'
complete -c macruby -s i --description 'Specifies in-place-edit mode'
complete -c macruby -s l --description '(The lowercase letter'
complete -c macruby -s n --description 'Causes Ruby to assume the following loop arou... [See Man Page]'
complete -c macruby -s p --description 'Acts mostly same as -n switch, but print the ... [See Man Page]'
complete -c macruby -s r --description 'Causes Ruby to load the library using require... [See Man Page]'
complete -c macruby -s s --description 'Enables some switch parsing for switches afte... [See Man Page]'
complete -c macruby -s v --description 'Enables verbose mode'
complete -c macruby -s w --description 'Enables verbose mode without printing version... [See Man Page]'
complete -c macruby -s x --description 'Tells Ruby that the script is embedded in a m... [See Man Page]'
complete -c macruby -s y
complete -c macruby -l -yydebug --description 'Turns on compiler debug mode'
complete -c macruby -l -disable-
complete -c macruby -l -enable- --description 'Disables (or enables) the specified'
complete -c macruby -l -disable-gems
complete -c macruby -l -enable-gems --description 'Disables (or enables) RubyGems libraries'
complete -c macruby -l -disable-rubyopt
complete -c macruby -l -enable-rubyopt --description 'Ignores (or considers) the'
complete -c macruby -l -disable-all
complete -c macruby -l -enable-all --description 'Disables (or enables) all features'
complete -c macruby -l -verbose --description 'Enables verbose mode without printing version... [See Man Page]'

