# Magick-config: Deroffing man parser
# Autogenerated from man pages
complete -c Magick-config -l cflags --description 'Print the compiler flags that were used to co... [See Man Page]'
complete -c Magick-config -l cppflags --description 'Print the preprocessor flags that are needed ... [See Man Page]'
complete -c Magick-config -l exec-prefix --description 'Print the directory under which target specif... [See Man Page]'
complete -c Magick-config -l ldflags --description 'Print the linker flags that are needed to lin... [See Man Page]'
complete -c Magick-config -l libs --description 'Print the linker flags that are needed to lin... [See Man Page]'
complete -c Magick-config -l version --description 'Print the version of the ImageMagick distribu... [See Man Page]'

