# mailstat: Deroffing man parser
# Autogenerated from man pages
complete -c mailstat -s k --description 'keep logfile intact'
complete -c mailstat -s l --description 'long display format'
complete -c mailstat -s m --description 'merge any errors into one line'
complete -c mailstat -s o --description 'use the old logfile'
complete -c mailstat -s t --description 'terse display format'
complete -c mailstat -s s --description 'silent in case of no mail NOTES Customise to ... [See Man Page]'

