# malloc_history: Darwin man parser
# Autogenerated from man pages
complete -c malloc_history -l showContent --description 'Show the content of malloc blocks of various ... [See Man Page]'
complete -c malloc_history -l invert --description 'Invert the call tree, so that malloc (and the... [See Man Page]'
complete -c malloc_history -l ignoreThreads --description 'Combine the call trees for all threads into a... [See Man Page]'
complete -c malloc_history -l collapseRecursion --description 'Collapse recursion within the call trees'
complete -c malloc_history -l chargeSystemLibraries --description 'Remove stack frames from all libraries in /Sy... [See Man Page]'

