# mcxquery: Darwin man parser
# Autogenerated from man pages
complete -c mcxquery -l user --description 'Specify the short name of the user record to ... [See Man Page]'
complete -c mcxquery -l group --description 'Specify the short name of the group record to... [See Man Page]'
complete -c mcxquery -l computer --description 'Specify the computer record to read managed p... [See Man Page]'

