# mcxrefresh: Darwin man parser
# Autogenerated from man pages
complete -c mcxrefresh -s u --description 'Specify the numeric user id of the user to be... [See Man Page]'
complete -c mcxrefresh -s n --description 'Specify the short name of the user to be refr... [See Man Page]'
complete -c mcxrefresh -s a --description 'Ask for authentication and pass it to Managed... [See Man Page]'

