# mdfind: Darwin man parser
# Autogenerated from man pages
complete -c mdfind -s 0 --description 'Prints an'
complete -c mdfind -l live --description 'Causes the mdfind command to provide live-upd... [See Man Page]'
complete -c mdfind -l count --description 'Causes the mdfind command to output the total... [See Man Page]'
complete -c mdfind -l onlyin --description 'Limit the scope of the search to the director... [See Man Page]'
complete -c mdfind -l name --description 'Searches for matching file names only'
complete -c mdfind -l literal --description 'Force the provided query string to be taken a... [See Man Page]'
complete -c mdfind -l interpret --description 'Force the provided query string to be interpr... [See Man Page]'

