# mdimport: Darwin man parser
# Autogenerated from man pages
complete -c mdimport -s g --description 'Load the plugin at the provided path, ignorin... [See Man Page]'
complete -c mdimport -s V --description 'Print timing information for this run of'
complete -c mdimport -s A --description 'Print out the list of all of the attributes a... [See Man Page]'
complete -c mdimport -s X --description 'Print the schema file and exit'
complete -c mdimport -s r --description 'Ask the server to reimport files for UTIs cla... [See Man Page]'
complete -c mdimport -s p --description 'Print out performance information gathered du... [See Man Page]'
complete -c mdimport -s L --description 'Print the list of installed importers and exi... [See Man Page]'
complete -c mdimport -s d --description 'Print debugging information'
complete -c mdimport -s n --description 'Don\'t actually set the attributes on the file... [See Man Page]'
complete -c mdimport -s w --description 'Wait for the specified interval between scann... [See Man Page]'

