# mdls: Darwin man parser
# Autogenerated from man pages
complete -c mdls -l name --description 'Print only the matching metadata attribute va... [See Man Page]'
complete -c mdls -l raw --description 'Print raw attribute data in the order that wa... [See Man Page]'
complete -c mdls -l nullMarker --description 'Sets a marker string to be used when a reques... [See Man Page]'

