# mdutil: Darwin man parser
# Autogenerated from man pages
complete -c mdutil -s p --description 'Spotlight caches indexes of some network devi... [See Man Page]'
complete -c mdutil -s E --description 'This flag will cause each local store for the... [See Man Page]'
complete -c mdutil -s i --description 'Sets the indexing status for the provided vol... [See Man Page]'
complete -c mdutil -s s --description 'Display the indexing status of the listed vol... [See Man Page]'
complete -c mdutil -s a --description 'Apply command to all volumes'
complete -c mdutil -s v --description 'Print verbose information when available'

