# merge: Deroffing man parser
# Autogenerated from man pages
complete -c merge -s A --description 'Output conflicts using the  -A style of  diff... [See Man Page]'
complete -c merge -s L --description 'This option may be given up to three times, a... [See Man Page]'
complete -c merge -s p --description 'Send results to standard output instead of ov... [See Man Page]'
complete -c merge -s E -s e --description 'These options specify conflict styles that ge... [See Man Page]'
complete -c merge -s q --description 'Quiet; do not warn about conflicts'
complete -c merge -s V --description 'Print \'s version number'

