# MergePef: Darwin man parser
# Autogenerated from man pages
complete -c MergePef -s v --description 'Produce verbose diagnostics to standard outpu... [See Man Page]'
complete -c MergePef -s t --description 'Set the Extended HFS file type of the output ... [See Man Page]'
complete -c MergePef -s c --description 'Set the Extended HFS file creator of the outp... [See Man Page]'
complete -c MergePef -s o --description 'Path to the output file'

