# mib2c: Type1
# Autogenerated from man pages
complete -c mib2c -s h --description 'Display a help message'
complete -c mib2c -s c --description 'Use CONFIGFILE when generating code'
complete -c mib2c -s I --description 'Search for configuration files in PATH'
complete -c mib2c -s f --description 'Places the output code into OUTNAME'
complete -c mib2c -s i --description 'Do not run indent on the resulting code'
complete -c mib2c -s s --description 'Do not look for MIBNODE'
complete -c mib2c -s q --description 'Run in "quiet" mode, which minimizes the stat... [See Man Page]'

