# mkdep: Darwin man parser
# Autogenerated from man pages
complete -c mkdep -s a --description 'Append to the output file,so that multiple'
complete -c mkdep -s f --description 'Write the include file dependencies to '
complete -c mkdep -s p --description Cause

