# mkdir: Darwin man parser
# Autogenerated from man pages
complete -c mkdir -s m --description 'Set the file permission bits of the final cre... [See Man Page]'
complete -c mkdir -s p --description 'Create intermediate directories as required'
complete -c mkdir -s v --description 'Be verbose when creating directories, listing... [See Man Page]'

