# mnthome: Darwin man parser
# Autogenerated from man pages
complete -c mnthome -s v --description 'Display version number'
complete -c mnthome -s d --description 'Print debugging information'
complete -c mnthome -s m --description 'Alternative mount point is specified with the... [See Man Page]'
complete -c mnthome -s n --description 'Do not force the unmount of the previous moun... [See Man Page]'
complete -c mnthome -s b --description 'Exec the user\'s shell after mount of home'
complete -c mnthome -s p --description 'A password may be specified with the '
complete -c mnthome -s i --description 'Display information about the AFP home mount ... [See Man Page]'
complete -c mnthome -s u --description 'Attempt to unmount the current home directory... [See Man Page]'
complete -c mnthome -s x --description 'This option must be followed by a path to an ... [See Man Page]'
complete -c mnthome -s s --description 'Skip preflight check to see if the currently ... [See Man Page]'

