# mv: Darwin man parser
# Autogenerated from man pages
complete -c mv -s f --description 'Do not prompt for confirmation before overwri... [See Man Page]'
complete -c mv -s i --description Cause
complete -c mv -s n --description 'Do not overwrite an existing file'
complete -c mv -s v --description Cause

