# my_print_defaults: Deroffing man parser
# Autogenerated from man pages
complete -c my_print_defaults -l user
complete -c my_print_defaults -l password
complete -c my_print_defaults -l host --description 'The output consists of options, one per line,... [See Man Page]'
complete -c my_print_defaults -l help
complete -c my_print_defaults -s '?'
complete -c my_print_defaults -l config-file
complete -c my_print_defaults -l defaults-file
complete -c my_print_defaults -s c
complete -c my_print_defaults -l debug
complete -c my_print_defaults -s '#'
complete -c my_print_defaults -l defaults-extra-file
complete -c my_print_defaults -l extra-file
complete -c my_print_defaults -s e
complete -c my_print_defaults -l defaults-group-suffix
complete -c my_print_defaults -s g
complete -c my_print_defaults -l no-defaults
complete -c my_print_defaults -s n
complete -c my_print_defaults -l verbose
complete -c my_print_defaults -s v
complete -c my_print_defaults -l version
complete -c my_print_defaults -s V

