# myisamchk: Deroffing man parser
# Autogenerated from man pages
complete -c myisamchk -l help
complete -c myisamchk -s '?'
complete -c myisamchk -l HELP
complete -c myisamchk -s H
complete -c myisamchk -l debug
complete -c myisamchk -s '#'
complete -c myisamchk -l silent
complete -c myisamchk -s s
complete -c myisamchk -l verbose
complete -c myisamchk -s v
complete -c myisamchk -s d --description and
complete -c myisamchk -o 'e.'
complete -c myisamchk -o 'vvv)' --description 'oc o 2'
complete -c myisamchk -l version
complete -c myisamchk -s V
complete -c myisamchk -l wait
complete -c myisamchk -s w
complete -c myisamchk -l var_name --description 'syntax: T{ Variable T}:T{ Default Value T} T{... [See Man Page]'
complete -c myisamchk -l 'recover.'
complete -c myisamchk -l extend-check --description 'or when the keys are repaired by inserting ke... [See Man Page]'
complete -c myisamchk -l 'safe-recover.' --description 'oc o 2'
complete -c myisamchk -l sort-recover --description option
complete -c myisamchk -l analyze --description 'option is given'
complete -c myisamchk -l check
complete -c myisamchk -s c
complete -c myisamchk -l check-only-changed
complete -c myisamchk -s C
complete -c myisamchk -s e
complete -c myisamchk -l fast
complete -c myisamchk -s F
complete -c myisamchk -l force
complete -c myisamchk -s f
complete -c myisamchk -l recover --description or
complete -c myisamchk -s r --description option
complete -c myisamchk -l information
complete -c myisamchk -s i
complete -c myisamchk -l medium-check
complete -c myisamchk -s m
complete -c myisamchk -l read-only
complete -c myisamchk -s T
complete -c myisamchk -l update-state
complete -c myisamchk -s U
complete -c myisamchk -l safe-recover --description 'is given): oc o 2'
complete -c myisamchk -l backup
complete -c myisamchk -s B
complete -c myisamchk -l character-sets-dir
complete -c myisamchk -l correct-checksum
complete -c myisamchk -l data-file-length
complete -c myisamchk -s D
complete -c myisamchk -l keys-used
complete -c myisamchk -s k
complete -c myisamchk -l no-symlinks
complete -c myisamchk -s l
complete -c myisamchk -l max-record-length
complete -c myisamchk -l parallel-recover
complete -c myisamchk -s p
complete -c myisamchk -s n --description 'This is beta-quality code'
complete -c myisamchk -l quick
complete -c myisamchk -s q
complete -c myisamchk -s o
complete -c myisamchk -l set-character-set
complete -c myisamchk -l set-collation --description 'in MySQL 5'
complete -c myisamchk -l tmpdir
complete -c myisamchk -s t
complete -c myisamchk -l unpack
complete -c myisamchk -s u
complete -c myisamchk -s a
complete -c myisamchk -l block-search
complete -c myisamchk -s b
complete -c myisamchk -l description
complete -c myisamchk -l 'set-auto-increment['
complete -c myisamchk -o 'A[value]'
complete -c myisamchk -l sort-index
complete -c myisamchk -s S
complete -c myisamchk -l sort-records
complete -c myisamchk -s R
complete -c myisamchk -o eis --description 'The tbl_name argument can be either the name ... [See Man Page]'
complete -c myisamchk -o rw-rw----
complete -c myisamchk -l sort_buffer_size --description 'is probably enough for most cases'
complete -c myisamchk -l 'quick;' --description 'This space must be available on the same file... [See Man Page]'
complete -c myisamchk -l 'safe-recover)' --description 'TMPDIR or'

