# myisam_ftdump: Deroffing man parser
# Autogenerated from man pages
complete -c myisam_ftdump -l help
complete -c myisam_ftdump -s h
complete -c myisam_ftdump -s '?'
complete -c myisam_ftdump -l count
complete -c myisam_ftdump -s c
complete -c myisam_ftdump -l dump
complete -c myisam_ftdump -s d
complete -c myisam_ftdump -l length
complete -c myisam_ftdump -s l
complete -c myisam_ftdump -l stats
complete -c myisam_ftdump -s s
complete -c myisam_ftdump -l verbose
complete -c myisam_ftdump -s v

