# mysqlbinlog: Deroffing man parser
# Autogenerated from man pages
complete -c mysqlbinlog -l read-from-remote-server --description option
complete -c mysqlbinlog -l host
complete -c mysqlbinlog -l password
complete -c mysqlbinlog -l port
complete -c mysqlbinlog -l protocol
complete -c mysqlbinlog -l socket
complete -c mysqlbinlog -l 'user;'
complete -c mysqlbinlog -l help
complete -c mysqlbinlog -s '?'
complete -c mysqlbinlog -l 'base64-output['
complete -c mysqlbinlog -l base64-output --description 'option is given, the effect is the same as'
complete -c mysqlbinlog -l verbose --description option
complete -c mysqlbinlog -l bind-address
complete -c mysqlbinlog -l character-sets-dir
complete -c mysqlbinlog -l database
complete -c mysqlbinlog -s d
complete -c mysqlbinlog -l binlog-do-db --description 'option for mysqld, but can be used to specify... [See Man Page]'
complete -c mysqlbinlog -l log-bin-use-v1-row-events --description 'oc o 2'
complete -c mysqlbinlog -l 'debug['
complete -c mysqlbinlog -s '#'
complete -c mysqlbinlog -l debug-check
complete -c mysqlbinlog -l debug-info
complete -c mysqlbinlog -l default-auth
complete -c mysqlbinlog -l disable-log-bin
complete -c mysqlbinlog -s D
complete -c mysqlbinlog -l to-last-log --description 'option and are sending the output to the same... [See Man Page]'
complete -c mysqlbinlog -l force-read
complete -c mysqlbinlog -s f
complete -c mysqlbinlog -l hexdump
complete -c mysqlbinlog -s H
complete -c mysqlbinlog -s h
complete -c mysqlbinlog -l local-load
complete -c mysqlbinlog -s l
complete -c mysqlbinlog -l offset
complete -c mysqlbinlog -s o
complete -c mysqlbinlog -l 'password['
complete -c mysqlbinlog -o 'p[password]'
complete -c mysqlbinlog -s p --description 'option on the command line, mysqlbinlog promp... [See Man Page]'
complete -c mysqlbinlog -l plugin-dir
complete -c mysqlbinlog -s P
complete -c mysqlbinlog -l position
complete -c mysqlbinlog -l start-position --description instead
complete -c mysqlbinlog -s R
complete -c mysqlbinlog -l 'user.'
complete -c mysqlbinlog -l result-file
complete -c mysqlbinlog -s r
complete -c mysqlbinlog -l server-id
complete -c mysqlbinlog -l server-id-bits
complete -c mysqlbinlog -l set-charset
complete -c mysqlbinlog -l short-form
complete -c mysqlbinlog -s s
complete -c mysqlbinlog -s S
complete -c mysqlbinlog -l start-datetime
complete -c mysqlbinlog -s j
complete -c mysqlbinlog -l stop-datetime
complete -c mysqlbinlog -l stop-position
complete -c mysqlbinlog -s t
complete -c mysqlbinlog -l 'read-from-remote-server.' --description 'oc o 2'
complete -c mysqlbinlog -l user
complete -c mysqlbinlog -s u
complete -c mysqlbinlog -s v
complete -c mysqlbinlog -l version
complete -c mysqlbinlog -s V
complete -c mysqlbinlog -l var_name --description 'syntax: oc o 2'

