# mysql_waitpid: Deroffing man parser
# Autogenerated from man pages
complete -c mysql_waitpid -l help
complete -c mysql_waitpid -s '?'
complete -c mysql_waitpid -s I
complete -c mysql_waitpid -l verbose
complete -c mysql_waitpid -s v
complete -c mysql_waitpid -l version
complete -c mysql_waitpid -s V

