# mysqlslap: Deroffing man parser
# Autogenerated from man pages
complete -c mysqlslap -l create --description or
complete -c mysqlslap -l query --description 'enable you to specify a string containing an ... [See Man Page]'
complete -c mysqlslap -l delimiter --description 'option to specify a different delimiter, whic... [See Man Page]'
complete -c mysqlslap -l help
complete -c mysqlslap -s '?'
complete -c mysqlslap -l auto-generate-sql
complete -c mysqlslap -s a
complete -c mysqlslap -l auto-generate-sql-add-autoincrement
complete -c mysqlslap -l auto-generate-sql-execute-number
complete -c mysqlslap -l auto-generate-sql-guid-primary
complete -c mysqlslap -l auto-generate-sql-load-type
complete -c mysqlslap -l auto-generate-sql-secondary-indexes
complete -c mysqlslap -l auto-generate-sql-unique-query-number
complete -c mysqlslap -l auto-generate-sql-unique-write-number
complete -c mysqlslap -l 'auto-generate-sql-write-number.' --description 'oc o 2'
complete -c mysqlslap -l auto-generate-sql-write-number
complete -c mysqlslap -l commit
complete -c mysqlslap -l compress
complete -c mysqlslap -s C
complete -c mysqlslap -l concurrency
complete -c mysqlslap -s c
complete -c mysqlslap -l create-and-drop-schema
complete -c mysqlslap -l create-schema
complete -c mysqlslap -l 'csv['
complete -c mysqlslap -l 'debug['
complete -c mysqlslap -s '#'
complete -c mysqlslap -l debug-check
complete -c mysqlslap -l debug-info
complete -c mysqlslap -s T
complete -c mysqlslap -l default-auth
complete -c mysqlslap -s F
complete -c mysqlslap -l detach
complete -c mysqlslap -l engine
complete -c mysqlslap -s e
complete -c mysqlslap -l host
complete -c mysqlslap -s h
complete -c mysqlslap -l iterations
complete -c mysqlslap -s i
complete -c mysqlslap -l number-char-cols
complete -c mysqlslap -s x
complete -c mysqlslap -l number-int-cols
complete -c mysqlslap -s y
complete -c mysqlslap -l number-of-queries
complete -c mysqlslap -l only-print
complete -c mysqlslap -l 'password['
complete -c mysqlslap -o 'p[password]'
complete -c mysqlslap -l password --description or
complete -c mysqlslap -s p --description 'option on the command line, mysqlslap prompts... [See Man Page]'
complete -c mysqlslap -l pipe
complete -c mysqlslap -s W
complete -c mysqlslap -l plugin-dir
complete -c mysqlslap -l port
complete -c mysqlslap -s P
complete -c mysqlslap -l post-query
complete -c mysqlslap -l shared-memory-base-name
complete -c mysqlslap -l post-system
complete -c mysqlslap -l pre-query
complete -c mysqlslap -l pre-system
complete -c mysqlslap -l protocol
complete -c mysqlslap -s q
complete -c mysqlslap -l silent
complete -c mysqlslap -s s
complete -c mysqlslap -l socket
complete -c mysqlslap -s S
complete -c mysqlslap -l 'ssl*'
complete -c mysqlslap -l ssl --description 'specify whether to connect to the server usin... [See Man Page]'
complete -c mysqlslap -l user
complete -c mysqlslap -s u
complete -c mysqlslap -l verbose
complete -c mysqlslap -s v
complete -c mysqlslap -l version
complete -c mysqlslap -s V

