# mysql-stress-test: Deroffing man parser
# Autogenerated from man pages
complete -c mysql-stress-test -l help
complete -c mysql-stress-test -l abort-on-error
complete -c mysql-stress-test -l check-tests-file
complete -c mysql-stress-test -l cleanup
complete -c mysql-stress-test -l log-error-details
complete -c mysql-stress-test -l loop-count
complete -c mysql-stress-test -l mysqltest
complete -c mysql-stress-test -l server-database
complete -c mysql-stress-test -l server-host
complete -c mysql-stress-test -l server-logs-dir
complete -c mysql-stress-test -l server-password
complete -c mysql-stress-test -l server-port
complete -c mysql-stress-test -l server-socket
complete -c mysql-stress-test -l server-user
complete -c mysql-stress-test -l sleep-time
complete -c mysql-stress-test -l stress-basedir
complete -c mysql-stress-test -l stress-datadir
complete -c mysql-stress-test -l stress-suite-basedir --description option
complete -c mysql-stress-test -l 'stress-init-file['
complete -c mysql-stress-test -l stress-mode
complete -c mysql-stress-test -l stress-tests-file --description option
complete -c mysql-stress-test -l 'stress-tests-file['
complete -c mysql-stress-test -l 'stress-suite-basedir.)' --description 'oc o 2'
complete -c mysql-stress-test -l suite
complete -c mysql-stress-test -l test-count
complete -c mysql-stress-test -l test-duration
complete -c mysql-stress-test -l threads
complete -c mysql-stress-test -l verbose

