# mysql-test-run: Deroffing man parser
# Autogenerated from man pages
complete -c mysql-test-run -l do-test --description option
complete -c mysql-test-run -l skip-test --description 'has the opposite effect of skipping test case... [See Man Page]'
complete -c mysql-test-run -l bootstrap --description and
complete -c mysql-test-run -l skip-grant-tables --description options
complete -c mysql-test-run -l disable-grant-options --description 'option (only MySQL 5'
complete -c mysql-test-run -o DDISABLE_GRANT_OPTIONS
complete -c mysql-test-run -l init-file --description 'will be disabled'
complete -c mysql-test-run -l vs-config --description 'option), and invoke mysql-test-run'
complete -c mysql-test-run -l mysqld --description 'option to mysql-test-run'
complete -c mysql-test-run -l help
complete -c mysql-test-run -s h
complete -c mysql-test-run -l big-test
complete -c mysql-test-run -l source --description 'BIG_TEST is set to 1'
complete -c mysql-test-run -l boot-dbx
complete -c mysql-test-run -l boot-ddd
complete -c mysql-test-run -l boot-gdb
complete -c mysql-test-run -l build-thread
complete -c mysql-test-run -l port-base --description 'is supported as an alternative'
complete -c mysql-test-run -l callgrind
complete -c mysql-test-run -l check-testcases
complete -c mysql-test-run -l clean-vardir
complete -c mysql-test-run -l 'mem.'
complete -c mysql-test-run -l client-bindir
complete -c mysql-test-run -l client-dbx
complete -c mysql-test-run -l client-ddd
complete -c mysql-test-run -l client-debugger
complete -c mysql-test-run -l client-gdb
complete -c mysql-test-run -l client-libdir
complete -c mysql-test-run -l combination
complete -c mysql-test-run -l comment
complete -c mysql-test-run -l compress
complete -c mysql-test-run -l cursor-protocol
complete -c mysql-test-run -l 'ps-protocol).' --description 'oc o 2'
complete -c mysql-test-run -l dbx
complete -c mysql-test-run -l ddd
complete -c mysql-test-run -l debug
complete -c mysql-test-run -l debugger
complete -c mysql-test-run -l debug-server
complete -c mysql-test-run -l debug-sync-timeout
complete -c mysql-test-run -l loose-debug-sync-timeout --description 'to mysqld'
complete -c mysql-test-run -l loose --description 'prefix is used so that mysqld does not fail i... [See Man Page]'
complete -c mysql-test-run -l default-myisam
complete -c mysql-test-run -l 'nodefault-myisam.' --description 'oc o 2'
complete -c mysql-test-run -l defaults-file
complete -c mysql-test-run -l defaults_extra_file
complete -c mysql-test-run -l embedded-server
complete -c mysql-test-run -l enable-disabled
complete -c mysql-test-run -l experimental
complete -c mysql-test-run -l extern --description option=value
complete -c mysql-test-run -l fast
complete -c mysql-test-run -l shutdown-timeout --description 'oc o 2'
complete -c mysql-test-run -l force
complete -c mysql-test-run -l force-restart
complete -c mysql-test-run -l gcov
complete -c mysql-test-run -l gdb
complete -c mysql-test-run -l gprof
complete -c mysql-test-run -l include-ndbcluster
complete -c mysql-test-run -l include-ndb
complete -c mysql-test-run -l manual-dbx
complete -c mysql-test-run -l manual-ddd
complete -c mysql-test-run -l manual-debug
complete -c mysql-test-run -l manual-gdb
complete -c mysql-test-run -l mark-progress
complete -c mysql-test-run -l max-connections
complete -c mysql-test-run -l max-save-core
complete -c mysql-test-run -l max-save-datadir
complete -c mysql-test-run -l max-test-fail
complete -c mysql-test-run -l mem
complete -c mysql-test-run -l mysqld-env
complete -c mysql-test-run -l ndb-connectstring
complete -c mysql-test-run -l nocheck-testcases
complete -c mysql-test-run -l nodefault-myisam
complete -c mysql-test-run -l noreorder
complete -c mysql-test-run -l notimer
complete -c mysql-test-run -l nounit-tests
complete -c mysql-test-run -l nowarnings
complete -c mysql-test-run -l parallel
complete -c mysql-test-run -l 'build-thread.'
complete -c mysql-test-run -l print-testcases
complete -c mysql-test-run -l ps-protocol
complete -c mysql-test-run -l record
complete -c mysql-test-run -l reorder
complete -c mysql-test-run -l repeat
complete -c mysql-test-run -l report-features
complete -c mysql-test-run -l report-times
complete -c mysql-test-run -l retry
complete -c mysql-test-run -l retry-failure --description 'options do not affect how many times a test r... [See Man Page]'
complete -c mysql-test-run -l skip-combinations
complete -c mysql-test-run -l skip-ndbcluster
complete -c mysql-test-run -l skip-ndb
complete -c mysql-test-run -l skip-ndbcluster-slave
complete -c mysql-test-run -l skip-ndb-slave
complete -c mysql-test-run -l skip-rpl
complete -c mysql-test-run -l skip-ssl
complete -c mysql-test-run -l skip-test-list
complete -c mysql-test-run -l 'skip-*'
complete -c mysql-test-run -l sleep
complete -c mysql-test-run -l sp-protocol
complete -c mysql-test-run -l ssl
complete -c mysql-test-run -l start
complete -c mysql-test-run -l start-and-exit
complete -c mysql-test-run -l start-dirty
complete -c mysql-test-run -l start-from
complete -c mysql-test-run -l strace-client
complete -c mysql-test-run -l strace-server
complete -c mysql-test-run -l stress
complete -c mysql-test-run -l suite
complete -c mysql-test-run -l suite-timeout
complete -c mysql-test-run -l testcase-timeout
complete -c mysql-test-run -l timediff
complete -c mysql-test-run -l timestamp --description 'oc o 2'
complete -c mysql-test-run -l timer
complete -c mysql-test-run -l tmpdir
complete -c mysql-test-run -l unit-tests
complete -c mysql-test-run -l user
complete -c mysql-test-run -l user-args
complete -c mysql-test-run -l valgrind
complete -c mysql-test-run -l valgrind-mysqld
complete -c mysql-test-run -l valgrind-mysqltest
complete -c mysql-test-run -l valgrind-option
complete -c mysql-test-run -l valgrind-path
complete -c mysql-test-run -l vardir
complete -c mysql-test-run -l verbose
complete -c mysql-test-run -l verbose-restart
complete -c mysql-test-run -l view-protocol
complete -c mysql-test-run -l wait-all
complete -c mysql-test-run -l warnings
complete -c mysql-test-run -l 'nowarnings.' --description 'oc o 2'
complete -c mysql-test-run -l with-ndbcluster-only

