# mysqld_safe: Deroffing man parser
# Autogenerated from man pages
complete -c mysqld_safe -l mysqld --description or
complete -c mysqld_safe -l mysqld-version --description 'option to mysqld_safe'
complete -c mysqld_safe -l ledir --description 'to indicate the directory where mysqld_safe s... [See Man Page]'
complete -c mysqld_safe -l log-error --description 'option: [mysqld] log-error=error'
complete -c mysqld_safe -l help
complete -c mysqld_safe -l basedir
complete -c mysqld_safe -l core-file-size
complete -c mysqld_safe -l datadir
complete -c mysqld_safe -l defaults-extra-file
complete -c mysqld_safe -l defaults-file
complete -c mysqld_safe -l malloc-lib
complete -c mysqld_safe -l nice
complete -c mysqld_safe -l no-defaults
complete -c mysqld_safe -l open-files-limit
complete -c mysqld_safe -l pid-file
complete -c mysqld_safe -l port
complete -c mysqld_safe -l skip-kill-mysqld
complete -c mysqld_safe -l socket
complete -c mysqld_safe -l syslog
complete -c mysqld_safe -l skip-syslog
complete -c mysqld_safe -l syslog-tag
complete -c mysqld_safe -l timezone
complete -c mysqld_safe -l user
complete -c mysqld_safe -l syslog: --description 'syslog on systems that support the logger pro... [See Man Page]'
complete -c mysqld_safe -l skip-syslog: --description syslog
complete -c mysqld_safe -l 'skip-syslog.'

