# mysql_convert_table_format: Deroffing man parser
# Autogenerated from man pages
complete -c mysql_convert_table_format -l help
complete -c mysql_convert_table_format -l force
complete -c mysql_convert_table_format -l host
complete -c mysql_convert_table_format -l password
complete -c mysql_convert_table_format -l port
complete -c mysql_convert_table_format -l socket
complete -c mysql_convert_table_format -l type
complete -c mysql_convert_table_format -l user
complete -c mysql_convert_table_format -l verbose
complete -c mysql_convert_table_format -l version

