# mysql_upgrade: Deroffing man parser
# Autogenerated from man pages
complete -c mysql_upgrade -l all-databases --description 'option, it processes all tables in all databa... [See Man Page]'
complete -c mysql_upgrade -l check-upgrade --description 'option entails, see the description of the FO... [See Man Page]'
complete -c mysql_upgrade -l force --description option
complete -c mysql_upgrade -l 'password[' --description option
complete -c mysql_upgrade -l help
complete -c mysql_upgrade -l basedir
complete -c mysql_upgrade -l datadir
complete -c mysql_upgrade -l debug-check
complete -c mysql_upgrade -l debug-info
complete -c mysql_upgrade -s T
complete -c mysql_upgrade -l default-auth
complete -c mysql_upgrade -l plugin-dir
complete -c mysql_upgrade -l tmpdir
complete -c mysql_upgrade -s t
complete -c mysql_upgrade -l upgrade-system-tables
complete -c mysql_upgrade -s s
complete -c mysql_upgrade -l user
complete -c mysql_upgrade -s u
complete -c mysql_upgrade -l verbose
complete -c mysql_upgrade -l write-binlog
complete -c mysql_upgrade -l 'skip-write-binlog).'

