# mysql_config: Deroffing man parser
# Autogenerated from man pages
complete -c mysql_config -l cflags
complete -c mysql_config -l include --description 'for more portable options that contain only i... [See Man Page]'
complete -c mysql_config -l libmysqld-libs
complete -c mysql_config -l embedded
complete -c mysql_config -l libs
complete -c mysql_config -l libs_r
complete -c mysql_config -l plugindir
complete -c mysql_config -l port
complete -c mysql_config -l socket
complete -c mysql_config -l version

