# mysql_plugin: Deroffing man parser
# Autogenerated from man pages
complete -c mysql_plugin -l plugin-load --description 'option at server startup or using the INSTALL... [See Man Page]'
complete -c mysql_plugin -l plugin_name --description 'options named for specific plugins, as descri... [See Man Page]'
complete -c mysql_plugin -l basedir
complete -c mysql_plugin -l datadir
complete -c mysql_plugin -l plugin-dir --description 'options and ignores others'
complete -c mysql_plugin -l help
complete -c mysql_plugin -s '?'
complete -c mysql_plugin -s b
complete -c mysql_plugin -s d
complete -c mysql_plugin -l my-print-defaults
complete -c mysql_plugin -l mysqld
complete -c mysql_plugin -l no-defaults
complete -c mysql_plugin -s p
complete -c mysql_plugin -l 'no-defaults.' --description 'oc o 2'
complete -c mysql_plugin -l plugin-ini
complete -c mysql_plugin -s i
complete -c mysql_plugin -l print-defaults
complete -c mysql_plugin -s P
complete -c mysql_plugin -l 'print-defaults.' --description 'oc o 2'
complete -c mysql_plugin -l verbose
complete -c mysql_plugin -s v
complete -c mysql_plugin -l version
complete -c mysql_plugin -s V

