# mysqld_multi: Deroffing man parser
# Autogenerated from man pages
complete -c mysqld_multi -l config-file --description 'option)'
complete -c mysqld_multi -l no-defaults --description 'oc o 2'
complete -c mysqld_multi -l defaults-file --description 'oc o 2'
complete -c mysqld_multi -l defaults-extra-file --description 'option, if one is given'
complete -c mysqld_multi -l help
complete -c mysqld_multi -l example
complete -c mysqld_multi -l log
complete -c mysqld_multi -l mysqladmin
complete -c mysqld_multi -l mysqld
complete -c mysqld_multi -l no-log
complete -c mysqld_multi -l password
complete -c mysqld_multi -l silent
complete -c mysqld_multi -l tcp-ip
complete -c mysqld_multi -l user
complete -c mysqld_multi -l verbose
complete -c mysqld_multi -l version
complete -c mysqld_multi -l bind-address --description 'to cause different servers to listen to diffe... [See Man Page]'
complete -c mysqld_multi -l pid-file --description 'option is very important if you are using mys... [See Man Page]'
complete -c mysqld_multi -l -------------------------------------------------------------- --description 'MY_PWD=`pwd` # Check if we are starting this ... [See Man Page]'

