# mysqltest: Deroffing man parser
# Autogenerated from man pages
complete -c mysqltest -l test-file --description option
complete -c mysqltest -l help
complete -c mysqltest -s '?'
complete -c mysqltest -l basedir
complete -c mysqltest -s b
complete -c mysqltest -l character-sets-dir
complete -c mysqltest -l compress
complete -c mysqltest -s C
complete -c mysqltest -l cursor-protocol
complete -c mysqltest -l database
complete -c mysqltest -s D
complete -c mysqltest -l 'debug['
complete -c mysqltest -o '#[debug_options]'
complete -c mysqltest -l debug-check
complete -c mysqltest -l debug-info
complete -c mysqltest -l host
complete -c mysqltest -s h
complete -c mysqltest -l include
complete -c mysqltest -s i
complete -c mysqltest -l source --description 'command as the first line of the test file'
complete -c mysqltest -l logdir
complete -c mysqltest -l mark-progress
complete -c mysqltest -l max-connect-retries
complete -c mysqltest -l max-connections
complete -c mysqltest -l no-defaults
complete -c mysqltest -l plugin-dir
complete -c mysqltest -l 'password['
complete -c mysqltest -o 'p[password]'
complete -c mysqltest -l password --description or
complete -c mysqltest -s p --description 'option on the command line, you are prompted ... [See Man Page]'
complete -c mysqltest -l port
complete -c mysqltest -s P
complete -c mysqltest -l protocol
complete -c mysqltest -l ps-protocol
complete -c mysqltest -l quiet
complete -c mysqltest -l 'silent.' --description 'oc o 2'
complete -c mysqltest -l record
complete -c mysqltest -s r
complete -c mysqltest -l result-file --description 'option, if that option is given'
complete -c mysqltest -l 'result-file.' --description 'oc o 2'
complete -c mysqltest -s R
complete -c mysqltest -l server-arg
complete -c mysqltest -s A
complete -c mysqltest -l tmpdir --description or
complete -c mysqltest -l 'core.' --description 'oc o 2'
complete -c mysqltest -l server-file
complete -c mysqltest -s F
complete -c mysqltest -l silent
complete -c mysqltest -s s
complete -c mysqltest -l skip-safemalloc
complete -c mysqltest -l sleep
complete -c mysqltest -s T
complete -c mysqltest -l socket
complete -c mysqltest -s S
complete -c mysqltest -l sp-protocol
complete -c mysqltest -l tail-lines
complete -c mysqltest -s x
complete -c mysqltest -l timer-file
complete -c mysqltest -s m
complete -c mysqltest -s t
complete -c mysqltest -l user
complete -c mysqltest -s u
complete -c mysqltest -l verbose
complete -c mysqltest -s v
complete -c mysqltest -l version
complete -c mysqltest -s V
complete -c mysqltest -l view-protocol

