# mysqlshow: Deroffing man parser
# Autogenerated from man pages
complete -c mysqlshow -l help
complete -c mysqlshow -s '?'
complete -c mysqlshow -l bind-address
complete -c mysqlshow -l character-sets-dir
complete -c mysqlshow -l compress
complete -c mysqlshow -s C
complete -c mysqlshow -l count
complete -c mysqlshow -l 'debug['
complete -c mysqlshow -s '#'
complete -c mysqlshow -l debug-check
complete -c mysqlshow -l debug-info
complete -c mysqlshow -l default-character-set
complete -c mysqlshow -l default-auth
complete -c mysqlshow -l host
complete -c mysqlshow -s h
complete -c mysqlshow -l keys
complete -c mysqlshow -s k
complete -c mysqlshow -l 'password['
complete -c mysqlshow -o 'p[password]'
complete -c mysqlshow -l password --description or
complete -c mysqlshow -s p --description 'option on the command line, mysqlshow prompts... [See Man Page]'
complete -c mysqlshow -l pipe
complete -c mysqlshow -s W
complete -c mysqlshow -l plugin-dir
complete -c mysqlshow -l port
complete -c mysqlshow -s P
complete -c mysqlshow -l protocol
complete -c mysqlshow -l show-table-type
complete -c mysqlshow -s t
complete -c mysqlshow -l socket
complete -c mysqlshow -s S
complete -c mysqlshow -l 'ssl*'
complete -c mysqlshow -l ssl --description 'specify whether to connect to the server usin... [See Man Page]'
complete -c mysqlshow -l status
complete -c mysqlshow -s i
complete -c mysqlshow -l user
complete -c mysqlshow -s u
complete -c mysqlshow -l verbose
complete -c mysqlshow -s v
complete -c mysqlshow -l version
complete -c mysqlshow -s V

