# mysqldump: Deroffing man parser
# Autogenerated from man pages
complete -c mysqldump -l single-transaction --description 'option is not used'
complete -c mysqldump -l databases --description or
complete -c mysqldump -l all-databases --description 'option, entire databases are dumped'
complete -c mysqldump -l skip-lock-tables --description option
complete -c mysqldump -l opt --description 'is the same as specifying'
complete -c mysqldump -l add-drop-table
complete -c mysqldump -l add-locks
complete -c mysqldump -l create-options
complete -c mysqldump -l disable-keys
complete -c mysqldump -l extended-insert
complete -c mysqldump -l lock-tables
complete -c mysqldump -l quick
complete -c mysqldump -l 'set-charset.'
complete -c mysqldump -l compact --description 'is the same as specifying'
complete -c mysqldump -l skip-add-drop-table
complete -c mysqldump -l skip-add-locks
complete -c mysqldump -l skip-comments
complete -c mysqldump -l skip-disable-keys
complete -c mysqldump -l skip-set-charset --description options
complete -c mysqldump -l skip-xxx --description 'form (--skip-opt or'
complete -c mysqldump -l 'skip-compact).' --description 'oc o 2'
complete -c mysqldump -l skip --description 'option for each feature'
complete -c mysqldump -l skip-extended-insert
complete -c mysqldump -l 'skip-quick.'
complete -c mysqldump -l skip-quick --description 'is sufficient because'
complete -c mysqldump -l skip-opt
complete -c mysqldump -l 'lock-tables.' --description 'When you selectively enable or disable the ef... [See Man Page]'
complete -c mysqldump -l 'quick).'
complete -c mysqldump -l 'quick)'
complete -c mysqldump -l help
complete -c mysqldump -s '?'
complete -c mysqldump -l add-drop-database
complete -c mysqldump -l add-drop-trigger
complete -c mysqldump -s A
complete -c mysqldump -l all-tablespaces
complete -c mysqldump -s Y
complete -c mysqldump -l allow-keywords
complete -c mysqldump -l apply-slave-statements
complete -c mysqldump -l dump-slave --description 'option, add a STOP SLAVE statement before the... [See Man Page]'
complete -c mysqldump -l bind-address
complete -c mysqldump -l character-sets-dir
complete -c mysqldump -l comments
complete -c mysqldump -s i
complete -c mysqldump -l 'skip-comments.' --description 'oc o 2'
complete -c mysqldump -l compatible
complete -c mysqldump -l complete-insert
complete -c mysqldump -s c
complete -c mysqldump -l compress
complete -c mysqldump -s C
complete -c mysqldump -s B
complete -c mysqldump -l 'debug['
complete -c mysqldump -s '#'
complete -c mysqldump -l debug-check
complete -c mysqldump -l debug-info
complete -c mysqldump -l default-auth
complete -c mysqldump -l default-character-set
complete -c mysqldump -l delayed-insert
complete -c mysqldump -l delete-master-logs
complete -c mysqldump -l 'master-data.' --description 'oc o 2'
complete -c mysqldump -s K
complete -c mysqldump -l dump-date
complete -c mysqldump -l skip-dump-date --description 'control whether the date is added to the comm... [See Man Page]'
complete -c mysqldump -l 'dump-slave['
complete -c mysqldump -l master-data --description 'except that it is used to dump a replication ... [See Man Page]'
complete -c mysqldump -l include-master-host-port --description 'options can also be used'
complete -c mysqldump -l events
complete -c mysqldump -s E
complete -c mysqldump -s e
complete -c mysqldump -l fields-terminated-by
complete -c mysqldump -l fields-enclosed-by
complete -c mysqldump -l fields-optionally-enclosed-by
complete -c mysqldump -l fields-escaped-by
complete -c mysqldump -l tab --description 'option and have the same meaning as the corre... [See Man Page]'
complete -c mysqldump -l first-slave
complete -c mysqldump -l lock-all-tables --description instead
complete -c mysqldump -l flush-logs
complete -c mysqldump -s F
complete -c mysqldump -l master-data:
complete -c mysqldump -l flush-privileges
complete -c mysqldump -l force
complete -c mysqldump -s f
complete -c mysqldump -l host
complete -c mysqldump -s h
complete -c mysqldump -l hex-blob
complete -c mysqldump -l ignore-table
complete -c mysqldump -l insert-ignore
complete -c mysqldump -l lines-terminated-by
complete -c mysqldump -s x
complete -c mysqldump -s l
complete -c mysqldump -l log-error
complete -c mysqldump -l 'master-data['
complete -c mysqldump -l 'single-transaction).'
complete -c mysqldump -l no-autocommit
complete -c mysqldump -l no-create-db
complete -c mysqldump -s n
complete -c mysqldump -l no-create-info
complete -c mysqldump -s t
complete -c mysqldump -l no-tablespaces --description 'option for this purpose'
complete -c mysqldump -l no-data
complete -c mysqldump -s d
complete -c mysqldump -l no-set-names
complete -c mysqldump -s N
complete -c mysqldump -l 'skip-set-charset.' --description 'oc o 2'
complete -c mysqldump -s y
complete -c mysqldump -l 'opt.' --description 'oc o 2'
complete -c mysqldump -l order-by-primary
complete -c mysqldump -l 'password['
complete -c mysqldump -o 'p[password]'
complete -c mysqldump -l password --description or
complete -c mysqldump -s p --description 'option on the command line, mysqldump prompts... [See Man Page]'
complete -c mysqldump -l pipe
complete -c mysqldump -s W
complete -c mysqldump -l plugin-dir
complete -c mysqldump -l port
complete -c mysqldump -s P
complete -c mysqldump -l protocol
complete -c mysqldump -s q
complete -c mysqldump -l quote-names
complete -c mysqldump -s Q
complete -c mysqldump -l skip-quote-names
complete -c mysqldump -l 'quote-names.' --description 'oc o 2'
complete -c mysqldump -l replace
complete -c mysqldump -l result-file
complete -c mysqldump -s r
complete -c mysqldump -l routines
complete -c mysqldump -s R
complete -c mysqldump -l 'routines.' --description mysql
complete -c mysqldump -l xml --description option
complete -c mysqldump -l set-charset
complete -c mysqldump -l 'quick.' --description 'oc o 2'
complete -c mysqldump -l socket
complete -c mysqldump -s S
complete -c mysqldump -l 'ssl*'
complete -c mysqldump -l ssl --description 'specify whether to connect to the server usin... [See Man Page]'
complete -c mysqldump -s T
complete -c mysqldump -l fields-xxx --description and
complete -c mysqldump -l tables
complete -c mysqldump -l triggers
complete -c mysqldump -l 'skip-triggers.' --description 'oc o 2'
complete -c mysqldump -l tz-utc
complete -c mysqldump -l 'skip-tz-utc.' --description 'oc o 2'
complete -c mysqldump -l user
complete -c mysqldump -s u
complete -c mysqldump -l verbose
complete -c mysqldump -s v
complete -c mysqldump -l version
complete -c mysqldump -s V
complete -c mysqldump -l where
complete -c mysqldump -s w
complete -c mysqldump -s X
complete -c mysqldump -l var_name --description 'syntax: oc o 2'

