# mysql_install_db: Deroffing man parser
# Autogenerated from man pages
complete -c mysql_install_db -l user --description 'option to indicate the user name that mysqld ... [See Man Page]'
complete -c mysql_install_db -l basedir --description or
complete -c mysql_install_db -l datadir --description 'if mysql_install_db does not use the correct ... [See Man Page]'
complete -c mysql_install_db -l bootstrap --description and
complete -c mysql_install_db -l skip-grant-tables --description options
complete -c mysql_install_db -l force
complete -c mysql_install_db -l ldata
complete -c mysql_install_db -l rpm
complete -c mysql_install_db -l skip-name-resolve
complete -c mysql_install_db -l srcdir
complete -c mysql_install_db -l verbose
complete -c mysql_install_db -l windows

