# mysqladmin: Deroffing man parser
# Autogenerated from man pages
complete -c mysqladmin -l skip-grant-tables --description option
complete -c mysqladmin -l verbose --description 'option is given, the output is like that of S... [See Man Page]'
complete -c mysqladmin -l help
complete -c mysqladmin -s '?'
complete -c mysqladmin -l bind-address
complete -c mysqladmin -l character-sets-dir
complete -c mysqladmin -l compress
complete -c mysqladmin -s C
complete -c mysqladmin -l count
complete -c mysqladmin -s c
complete -c mysqladmin -l sleep --description 'option is given'
complete -c mysqladmin -l 'debug['
complete -c mysqladmin -s '#'
complete -c mysqladmin -l debug-check
complete -c mysqladmin -l debug-info
complete -c mysqladmin -l default-auth
complete -c mysqladmin -l default-character-set
complete -c mysqladmin -l force
complete -c mysqladmin -s f
complete -c mysqladmin -l host
complete -c mysqladmin -s h
complete -c mysqladmin -l no-beep
complete -c mysqladmin -s b
complete -c mysqladmin -l 'password['
complete -c mysqladmin -o 'p[password]'
complete -c mysqladmin -l password --description or
complete -c mysqladmin -s p --description 'option on the command line, mysqladmin prompt... [See Man Page]'
complete -c mysqladmin -l pipe
complete -c mysqladmin -s W
complete -c mysqladmin -l plugin-dir
complete -c mysqladmin -l port
complete -c mysqladmin -s P
complete -c mysqladmin -l protocol
complete -c mysqladmin -l relative
complete -c mysqladmin -s r
complete -c mysqladmin -l silent
complete -c mysqladmin -s s
complete -c mysqladmin -s i
complete -c mysqladmin -l socket
complete -c mysqladmin -s S
complete -c mysqladmin -l 'ssl*'
complete -c mysqladmin -l ssl --description 'specify whether to connect to the server usin... [See Man Page]'
complete -c mysqladmin -l user
complete -c mysqladmin -s u
complete -c mysqladmin -s v
complete -c mysqladmin -l version
complete -c mysqladmin -s V
complete -c mysqladmin -l vertical
complete -c mysqladmin -s E
complete -c mysqladmin -l 'wait['
complete -c mysqladmin -o 'w[count]'
complete -c mysqladmin -l var_name --description The
complete -c mysqladmin -l set-variable --description 'format is deprecated and was removed in MySQL... [See Man Page]'

