# mysqldumpslow: Deroffing man parser
# Autogenerated from man pages
complete -c mysqldumpslow -s a --description and
complete -c mysqldumpslow -s n --description 'options can be used to modify value abstracti... [See Man Page]'
complete -c mysqldumpslow -l help
complete -c mysqldumpslow -l debug
complete -c mysqldumpslow -s d
complete -c mysqldumpslow -s g
complete -c mysqldumpslow -s h
complete -c mysqldumpslow -s i
complete -c mysqldumpslow -s l
complete -c mysqldumpslow -s r
complete -c mysqldumpslow -s s
complete -c mysqldumpslow -s t
complete -c mysqldumpslow -l verbose
complete -c mysqldumpslow -s v

