# mysql: Deroffing man parser
# Autogenerated from man pages
complete -c mysql -l basedir
complete -c mysql -l datadir
complete -c mysql -l pid-file
complete -c mysql -l service-startup-timeout
complete -c mysql -l use-mysqld_safe

