# mysql_setpermission: Deroffing man parser
# Autogenerated from man pages
complete -c mysql_setpermission -l help --description 'to display the help message, or options that ... [See Man Page]'
complete -c mysql_setpermission -l host
complete -c mysql_setpermission -l password
complete -c mysql_setpermission -l port
complete -c mysql_setpermission -l socket
complete -c mysql_setpermission -l user

