# mysql_zap: Deroffing man parser
# Autogenerated from man pages
complete -c mysql_zap -o signal --description 'option is given, it specifies the name or num... [See Man Page]'
complete -c mysql_zap -l help
complete -c mysql_zap -s '?'
complete -c mysql_zap -s I
complete -c mysql_zap -s f
complete -c mysql_zap -s t

