# mysqlaccess: Deroffing man parser
# Autogenerated from man pages
complete -c mysqlaccess -l help
complete -c mysqlaccess -s '?'
complete -c mysqlaccess -l brief
complete -c mysqlaccess -s b
complete -c mysqlaccess -l commit
complete -c mysqlaccess -l copy
complete -c mysqlaccess -l db
complete -c mysqlaccess -s d
complete -c mysqlaccess -l debug
complete -c mysqlaccess -l host
complete -c mysqlaccess -s h
complete -c mysqlaccess -l howto
complete -c mysqlaccess -l old_server
complete -c mysqlaccess -l 'password['
complete -c mysqlaccess -o 'p[password]'
complete -c mysqlaccess -l password --description or
complete -c mysqlaccess -s p --description 'option on the command line, mysqlaccess promp... [See Man Page]'
complete -c mysqlaccess -l plan
complete -c mysqlaccess -l preview
complete -c mysqlaccess -l relnotes
complete -c mysqlaccess -l rhost
complete -c mysqlaccess -s H
complete -c mysqlaccess -l rollback
complete -c mysqlaccess -l 'spassword['
complete -c mysqlaccess -o 'P[password]'
complete -c mysqlaccess -l spassword --description or
complete -c mysqlaccess -l superuser
complete -c mysqlaccess -s U
complete -c mysqlaccess -l table
complete -c mysqlaccess -s t
complete -c mysqlaccess -l user
complete -c mysqlaccess -s u
complete -c mysqlaccess -l version
complete -c mysqlaccess -s v

