# nad2nad: Deroffing man parser
# Autogenerated from man pages
complete -c nad2nad -o '[i' --description 'The  -i and  -o option expect keyword argumen... [See Man Page]'
complete -c nad2nad -s t --description 'A specifies a character employed as the first... [See Man Page]'
complete -c nad2nad -s e --description 'String is an arbitrary string to be output if... [See Man Page]'
complete -c nad2nad -s r --description 'specifies which regional conversion table to ... [See Man Page]'
complete -c nad2nad -s E --description 'Input coordinates are echoed to output before... [See Man Page]'
complete -c nad2nad -s f --description 'Format is a  printf format string to control ... [See Man Page]'
complete -c nad2nad -s i --description and
complete -c nad2nad -s o --description 'option expect keyword arguments which define ... [See Man Page]'
complete -c nad2nad -o '[w' --description 'N is the number of significant fractional dig... [See Man Page]'
complete -c nad2nad -o w3 --description 'is assumed)'
complete -c nad2nad -s W --description 'is employed the fields will be constant width... [See Man Page]'

