# nc: Darwin man parser
# Autogenerated from man pages
complete -c nc -s 4 --description Forces
complete -c nc -s 6 --description Forces
complete -c nc -s b --description 'Specifies the interface to bind the socket to... [See Man Page]'
complete -c nc -s D --description 'Enable debugging on the socket'
complete -c nc -s C --description Forces
complete -c nc -s d --description 'Do not attempt to read from stdin'
complete -c nc -s h --description 'Prints out'
complete -c nc -s i --description 'Specifies a delay time interval between lines... [See Man Page]'
complete -c nc -s k --description Forces
complete -c nc -s l --description 'Used to specify that'
complete -c nc -s n --description 'Do not do any DNS or service lookups on any s... [See Man Page]'
complete -c nc -s p --description 'Specifies the source port'
complete -c nc -s r --description 'Specifies that source and/or destination port... [See Man Page]'
complete -c nc -s s --description 'Specifies the IP of the interface which is us... [See Man Page]'
complete -c nc -s t --description Causes
complete -c nc -s U --description 'Specifies to use Unix Domain Sockets'
complete -c nc -s u --description 'Use UDP instead of the default option of TCP'
complete -c nc -s v --description Have
complete -c nc -s w --description 'If a connection and stdin are idle for more t... [See Man Page]'
complete -c nc -s X --description 'Requests that'
complete -c nc -s z --description 'Specifies that'

