# ndisasm: Deroffing man parser
# Autogenerated from man pages
complete -c ndisasm -s h --description 'Causes  ndisasm to exit immediately, after gi... [See Man Page]'
complete -c ndisasm -s r --description 'Causes  ndisasm to exit immediately, after di... [See Man Page]'
complete -c ndisasm -s o --description 'Specifies the notional load address for the f... [See Man Page]'
complete -c ndisasm -s s --description 'Manually specifies a synchronisation address,... [See Man Page]'
complete -c ndisasm -s e --description 'Specifies a number of bytes to discard from t... [See Man Page]'
complete -c ndisasm -s k --description 'Specifies that  length bytes, starting from d... [See Man Page]'
complete -c ndisasm -s a -s i --description 'Enables automatic (or intelligent) sync mode,... [See Man Page]'
complete -c ndisasm -s b --description 'Specifies either 16-bit or 32-bit mode'
complete -c ndisasm -s u --description 'Specifies 32-bit mode, more compactly than us... [See Man Page]'
complete -c ndisasm -s p --description 'Prefers instructions as defined by vendor in ... [See Man Page]'

