# net-snmp-create-v3-user: Deroffing man parser
# Autogenerated from man pages
complete -c net-snmp-create-v3-user -l version --description 'displays the net-snmp version number'
complete -c net-snmp-create-v3-user -o ro --description 'create an user with read-only permissions'
complete -c net-snmp-create-v3-user -s a --description 'specify authentication password'
complete -c net-snmp-create-v3-user -s x --description 'specify encryption password'
complete -c net-snmp-create-v3-user -s X --description 'specify encryption algorithm'

