# net-snmp-config: Deroffing man parser
# Autogenerated from man pages
complete -c net-snmp-config -l version --description 'displays the net-snmp version number'
complete -c net-snmp-config -l indent-options --description 'displays the indent options from the Coding S... [See Man Page]'
complete -c net-snmp-config -l debug-tokens --description 'displays a example command line to search to ... [See Man Page]'
complete -c net-snmp-config -l create-snmpv3-user --description '[-A MD5|SHA] [username] '
complete -c net-snmp-config -l base-cflags --description 'lists additional compilation flags needed for... [See Man Page]'
complete -c net-snmp-config -l cflags --description 'lists additional compilation flags needed'
complete -c net-snmp-config -l libs --description 'lists libraries needed for building applicati... [See Man Page]'
complete -c net-snmp-config -l agent-libs --description 'lists libraries needed for building subagents'
complete -c net-snmp-config -l netsnmp-libs --description 'lists netsnmp specific libraries'
complete -c net-snmp-config -l external-libs --description 'lists libraries needed by netsnmp libs'
complete -c net-snmp-config -l netsnmp-agent-libs --description 'lists netsnmp specific agent libraries '
complete -c net-snmp-config -l compile-subagent --description '[--ldflags flags] mibmodule1'
complete -c net-snmp-config -l norm --description 'leave the generated '
complete -c net-snmp-config -l ldflags --description 'extra ld flags to use (e'
complete -c net-snmp-config -l configure-options --description 'Display original configure arguments'
complete -c net-snmp-config -l snmpd-module-list --description 'Display the modules compiled into the agent'
complete -c net-snmp-config -l external-agent-libs
complete -c net-snmp-config -l prefix --description 'Display the installation prefix'

