# nettop: Darwin man parser
# Autogenerated from man pages
complete -c nettop -s m --description 'Specify the mode'
complete -c nettop -s n --description 'Disable address to name resolution'
complete -c nettop -s c --description 'Less intensive use of the CPU - draws less of... [See Man Page]'

