# nfsstat: Darwin man parser
# Autogenerated from man pages
complete -c nfsstat -s c --description 'Show NFS client statistics'
complete -c nfsstat -s e --description 'Show NFS server exported directory statistics... [See Man Page]'
complete -c nfsstat -s m --description 'Show NFS mount information'
complete -c nfsstat -s s --description 'Show NFS server statistics'
complete -c nfsstat -s u --description 'Show NFS server active user statistics'
complete -c nfsstat -s w --description 'Display a shorter summary at'
complete -c nfsstat -s n --description 'Show network addresses as numbers, or show us... [See Man Page]'
complete -c nfsstat -s v --description 'Show additional information (if available)'

