# nl: Darwin man parser
# Autogenerated from man pages
complete -c nl -s b --description 'Specify the logical page body lines to be num... [See Man Page]'
complete -c nl -s d --description 'Specify the delimiter characters used to indi... [See Man Page]'
complete -c nl -s f --description 'Specify the same as'
complete -c nl -s h --description 'Specify the same as'
complete -c nl -s i --description 'Specify the increment value used to number lo... [See Man Page]'
complete -c nl -s l --description 'If numbering of all lines is specified for th... [See Man Page]'
complete -c nl -s n --description 'Specify the line numbering output format'
complete -c nl -s p --description 'Specify that line numbering should not be res... [See Man Page]'
complete -c nl -s s --description 'Specify the characters used in separating the... [See Man Page]'
complete -c nl -s v --description 'Specify the initial value used to number logi... [See Man Page]'
complete -c nl -s w --description 'Specify the number of characters to be occupi... [See Man Page]'

