# nmedit: Deroffing man parser
# Autogenerated from man pages
complete -c nmedit -s s --description 'Leave the symbol table entries for the global... [See Man Page]'
complete -c nmedit -s R --description 'Change the symbol table entries for the globa... [See Man Page]'
complete -c nmedit -s p --description 'Change symbols to private externs instead of ... [See Man Page]'
complete -c nmedit -s A --description 'Leave all global absolute symbols except thos... [See Man Page]'
complete -c nmedit -o arch --description 'Specifies the architecture,  arch_type, of th... [See Man Page]'
complete -c nmedit -s g --description 'option to cc (1)) for the global symbols it c... [See Man Page]'
complete -c nmedit -s o --description 'Write the result into the file output'

