# npm-config: Deroffing man parser
# Autogenerated from man pages
complete -c npm-config -o v: -l version
complete -c npm-config -s h -s '?' -l help -o H: -l usage
complete -c npm-config -s s -l silent: -l loglevel
complete -c npm-config -o d:
complete -c npm-config -o dd -l verbose:
complete -c npm-config -o ddd:
complete -c npm-config -o g: -l global
complete -c npm-config -o l: -l long
complete -c npm-config -s p -l porcelain: -l parseable
complete -c npm-config -o reg: -l registry
complete -c npm-config -o f: -l force
complete -c npm-config -o desc: -l description
complete -c npm-config -o S: -l save
complete -c npm-config -o y: -l yes
complete -c npm-config -o n:

