# npm-get: Deroffing man parser
# Autogenerated from man pages
complete -c npm-get -o v: -l version
complete -c npm-get -s h -s '?' -l help -o H: -l usage
complete -c npm-get -s s -l silent: -l loglevel
complete -c npm-get -o d:
complete -c npm-get -o dd -l verbose:
complete -c npm-get -o ddd:
complete -c npm-get -o g: -l global
complete -c npm-get -o l: -l long
complete -c npm-get -s p -l porcelain: -l parseable
complete -c npm-get -o reg: -l registry
complete -c npm-get -o f: -l force
complete -c npm-get -o desc: -l description
complete -c npm-get -o S: -l save
complete -c npm-get -o y: -l yes
complete -c npm-get -o n:

