# npm-set: Deroffing man parser
# Autogenerated from man pages
complete -c npm-set -o v: -l version
complete -c npm-set -s h -s '?' -l help -o H: -l usage
complete -c npm-set -s s -l silent: -l loglevel
complete -c npm-set -o d:
complete -c npm-set -o dd -l verbose:
complete -c npm-set -o ddd:
complete -c npm-set -o g: -l global
complete -c npm-set -o l: -l long
complete -c npm-set -s p -l porcelain: -l parseable
complete -c npm-set -o reg: -l registry
complete -c npm-set -o f: -l force
complete -c npm-set -o desc: -l description
complete -c npm-set -o S: -l save
complete -c npm-set -o y: -l yes
complete -c npm-set -o n:

