# nroff: Deroffing man parser
# Autogenerated from man pages
complete -c nroff -s T --description 'option, selecting the output encoding emitted... [See Man Page]'
complete -c nroff -s h --description and
complete -c nroff -s c --description 'options are equivalent to grotty \'s options'
complete -c nroff -s d
complete -c nroff -s C
complete -c nroff -s i
complete -c nroff -s M
complete -c nroff -s m
complete -c nroff -s n
complete -c nroff -s o --description and
complete -c nroff -s r --description 'options have the effect described in troff (1... [See Man Page]'
complete -c nroff -s e
complete -c nroff -s q --description and
complete -c nroff -s s --description '(which are not implemented in troff )'
complete -c nroff -s p --description '(pic),'
complete -c nroff -s t --description '(tbl),'
complete -c nroff -s S --description '(safer), and'
complete -c nroff -s U --description '(unsafe) are passed to groff '
complete -c nroff -s v --description 'shows the version number'

