# nsupdate: Deroffing man parser
# Autogenerated from man pages
complete -c nsupdate -s d --description 'option makes nsupdate operate in debug mode'
complete -c nsupdate -s D --description 'option makes nsupdate report additional debug... [See Man Page]'
complete -c nsupdate -o 'd.'
complete -c nsupdate -s L --description 'option with an integer argument of zero or hi... [See Man Page]'
complete -c nsupdate -s g --description flag
complete -c nsupdate -s o --description flag
complete -c nsupdate -s y --description or
complete -c nsupdate -s k --description 'option to provide the shared secret needed to... [See Man Page]'
complete -c nsupdate -s l --description flag
complete -c nsupdate -s v --description 'option makes nsupdate use a TCP connection'
complete -c nsupdate -s p --description 'sets the default port number to use for conne... [See Man Page]'
complete -c nsupdate -s t --description 'option sets the maximum time an update reques... [See Man Page]'
complete -c nsupdate -s u --description 'option sets the UDP retry interval'
complete -c nsupdate -s r --description 'option sets the number of UDP retries'
complete -c nsupdate -s R --description 'option specifies a source of randomness'
complete -c nsupdate -o 'k.' --description gsstsig

