# ntpdc: Deroffing man parser
# Autogenerated from man pages
complete -c ntpdc -s 4 -l ipv4 --description 'Force IPv4 DNS name resolution'
complete -c ntpdc -s 6 -l ipv6 --description 'Force IPv6 DNS name resolution'
complete -c ntpdc -s c -l command --description 'run a command and exit'
complete -c ntpdc -s l -l listpeers --description 'Print a list of the peers'
complete -c ntpdc -s p -l peers --description 'Print a list of the peers'
complete -c ntpdc -s s -l showpeers --description 'Show a list of the peers'
complete -c ntpdc -s i -l interactive --description 'Force ntpq to operate in interactive mode'
complete -c ntpdc -s d -l debug-level --description 'Increase output debug message level'
complete -c ntpdc -s D -l set-debug-level --description 'Set the output debug message level'
complete -c ntpdc -s n -l numeric --description 'numeric host addresses'
complete -c ntpdc -s '?' -l help --description 'Display extended usage information and exit'
complete -c ntpdc -s '!' -l more-help --description 'Extended usage information passed thru pager'
complete -c ntpdc -s '>' -l save-opts --description 'Save the option state to rcfile'
complete -c ntpdc -s '<' -l load-opts -l no-load-opts --description 'Load options from rcfile'
complete -c ntpdc -l version --description 'Output version of program and exit'

