# od: Darwin man parser
# Autogenerated from man pages
complete -c od -s A --description 'Specify the input address base'
complete -c od -s a --description 'Output named characters'
complete -c od -s B --description 'Output octal shorts'
complete -c od -s b --description 'Output octal bytes'
complete -c od -s c --description 'Output C-style escaped characters'
complete -c od -s D --description 'Output unsigned decimal ints'
complete -c od -s e --description 'Output double-precision floating point number... [See Man Page]'
complete -c od -s f --description 'Output single-precision floating point number... [See Man Page]'
complete -c od -s H --description 'Output hexadecimal ints'
complete -c od -s h --description 'Output hexadecimal shorts'
complete -c od -s I --description 'Output signed decimal longs'
complete -c od -s i --description 'Output signed decimal ints'
complete -c od -s j --description Skip
complete -c od -s N --description 'Dump at most'
complete -c od -s O --description 'Output octal ints'
complete -c od -s s --description 'Output signed decimal shorts'
complete -c od -s t --description 'Specify the output format'
complete -c od -s v --description 'Write all input data, instead of replacing li... [See Man Page]'

