# odmigrationtool: Darwin man parser
# Autogenerated from man pages
complete -c odmigrationtool -l source --description 'source volume or path to migrate from'
complete -c odmigrationtool -l target --description 'destination volume or path to mirage to'

