# open: Darwin man parser
# Autogenerated from man pages
complete -c open -l 'a\\' --description 'Specifies the application to use for opening ... [See Man Page]'
complete -c open -l 'b\\' --description 'Specifies the bundle identifier for the appli... [See Man Page]'
complete -c open -s e --description 'Causes the file to be opened with /Applicatio... [See Man Page]'
complete -c open -s t --description 'Causes the file to be opened with the default... [See Man Page]'
complete -c open -s f --description 'Reads input from standard input and opens the... [See Man Page]'
complete -c open -s F --description 'Opens the application "fresh," that is, witho... [See Man Page]'
complete -c open -s W --description Causes
complete -c open -s R --description 'Reveals the file(s) in the Finder instead of ... [See Man Page]'
complete -c open -s n --description 'Open a new instance of the application(s) eve... [See Man Page]'
complete -c open -s g --description 'Do not bring the application to the foregroun... [See Man Page]'
complete -c open -s h --description 'Searches header locations for a header whose ... [See Man Page]'
complete -c open -l args --description 'All remaining arguments are passed to the ope... [See Man Page]'

