# orbd: Deroffing man parser
# Autogenerated from man pages
complete -c orbd -o ORBInitialPort --description 'Specifies the port on which the name server s... [See Man Page]'
complete -c orbd -o port --description 'Specifies the activation port where the ORBD ... [See Man Page]'
complete -c orbd -o defaultdb --description 'Specifies the base where the ORBD persistent ... [See Man Page]'
complete -c orbd -o serverPollingTime --description 'Specifies how often the daemon thread checks ... [See Man Page]'
complete -c orbd -o serverStartupDelay --description 'Specifies how long the ServerManager waits be... [See Man Page]'
complete -c orbd -s J --description 'Pass option to the Java virtual machine, wher... [See Man Page]'
complete -c orbd -o J-Xms48m --description 'sets the startup memory to 48 megabytes'
complete -c orbd -o ORBInitialHost --description 'localhost since the name server is running on... [See Man Page]'

