# osacompile: Darwin man parser
# Autogenerated from man pages
complete -c osacompile -s l --description 'Override the language for any plain text file... [See Man Page]'
complete -c osacompile -s e --description 'Enter one line of a script'
complete -c osacompile -s o --description 'Place the output in the file '
complete -c osacompile -s x --description 'Save the resulting script as execute-only'
complete -c osacompile -s s --description 'Stay-open applet'
complete -c osacompile -s u --description 'Use startup screen'
complete -c osacompile -s a --description 'Create the applet or droplet for the specifie... [See Man Page]'
complete -c osacompile -s d --description 'Place the resulting script in the data fork o... [See Man Page]'
complete -c osacompile -s r --description 'Place the resulting script in the resource fo... [See Man Page]'
complete -c osacompile -s t --description 'Set the output file type to'
complete -c osacompile -s c --description 'Set the output file creator to'

