# osalang: Darwin man parser
# Autogenerated from man pages
complete -c osalang -s d --description 'Only print the default language'
complete -c osalang -s l --description 'List in long format'
complete -c osalang -s L --description 'Same as'

