# osascript: Darwin man parser
# Autogenerated from man pages
complete -c osascript -s e --description 'Enter one line of a script'
complete -c osascript -s l --description 'Override the language for any plain text file... [See Man Page]'
complete -c osascript -s s --description 'Modify the output style'

