# osql: Deroffing man parser
# Autogenerated from man pages
complete -c osql -s S --description 'the Data Source Name to which to connect, as ... [See Man Page]'
complete -c osql -s U --description 'database login name'
complete -c osql -s P --description 'database password'
complete -c osql -s I --description 'override odbc'

