# pack200: Deroffing man parser
# Autogenerated from man pages
complete -c pack200 -s r -l repack --description 'Produces a JAR file by packing the file myarc... [See Man Page]'
complete -c pack200 -s g -l no-gzip --description 'Produces a pack200 file'
complete -c pack200 -s G -l strip-debug --description 'Strips the attributes used for debugging, fro... [See Man Page]'
complete -c pack200 -s O -l no-keep-file-order --description 'The packer will reorder and transmit all elem... [See Man Page]'
complete -c pack200 -s S -l segment-limit --description 'The value is the estimated target size N (in ... [See Man Page]'
complete -c pack200 -s E -l effort --description 'If the value is set to a single decimal digit... [See Man Page]'
complete -c pack200 -s H -l deflate-hint --description 'Overrides the default, which preserves the in... [See Man Page]'
complete -c pack200 -s m -l modification-time --description 'The possible values are:  latest '
complete -c pack200 -s P -o pass-file --description 'Indicates that a file should be passed throug... [See Man Page]'
complete -c pack200 -s U -l unknown-attribute --description 'Overrides the default behavior, ie'
complete -c pack200 -o 'fpack.properties' -l config-file --description 'A configuration file, containing Java propert... [See Man Page]'
complete -c pack200 -s C
complete -c pack200 -l class-attribute
complete -c pack200 -s F
complete -c pack200 -l field-attribute
complete -c pack200 -s M
complete -c pack200 -l method-attribute
complete -c pack200 -s D
complete -c pack200 -l code-attribute --description 'With the above four options, the attribute la... [See Man Page]'
complete -c pack200 -s v -l verbose --description 'Outputs minimal messages, multiple specificat... [See Man Page]'
complete -c pack200 -s q -l quiet --description 'Quiet operation with no messages'
complete -c pack200 -s l -l log-file --description 'A log file to output messages'
complete -c pack200 -s J --description 'Passes option to the Java launcher  called  b... [See Man Page]'

