# pagestuff: Deroffing man parser
# Autogenerated from man pages
complete -c pagestuff -o arch --description 'Specifies the architecture,  arch_type, of th... [See Man Page]'
complete -c pagestuff -s a --description 'Displays all pages'
complete -c pagestuff -s p --description 'Print a list of the sections of the specified... [See Man Page]'

