# pal2rgb: Deroffing man parser
# Autogenerated from man pages
complete -c pal2rgb -s C --description 'This option overrides the default behavior of... [See Man Page]'
complete -c pal2rgb -s p --description 'Explicitly select the planar configuration us... [See Man Page]'
complete -c pal2rgb -s c --description 'Use the specific compression algorithm to enc... [See Man Page]'
complete -c pal2rgb -s r --description 'Explicitly specify the number of rows in each... [See Man Page]'

