# paste: Darwin man parser
# Autogenerated from man pages
complete -c paste -s d --description 'Use one or more of the provided characters to... [See Man Page]'
complete -c paste -s s --description 'Concatenate all of the lines of each separate... [See Man Page]'

