# patch: Deroffing man parser
# Autogenerated from man pages
complete -c patch -s b --description 'Make backup files'
complete -c patch -s B --description 'Prefix  pref to a file name when generating i... [See Man Page]'
complete -c patch -s c --description 'Interpret the patch file as a ordinary contex... [See Man Page]'
complete -c patch -s d --description 'Change to the directory  dir immediately, bef... [See Man Page]'
complete -c patch -s D --description 'Use the  #ifdef " '
complete -c patch -s e --description 'Interpret the patch file as an  ed script'
complete -c patch -s E --description 'Remove output files that are empty after the ... [See Man Page]'
complete -c patch -s f --description 'Assume that the user knows exactly what he or... [See Man Page]'
complete -c patch -s F --description 'Set the maximum fuzz factor'
complete -c patch -s g --description 'This option controls  patch \'s actions when a... [See Man Page]'
complete -c patch -s i --description 'Read the patch from R patchfile '
complete -c patch -s l --description 'Match patterns loosely, in case tabs or space... [See Man Page]'
complete -c patch -s n --description 'Interpret the patch file as a normal diff'
complete -c patch -s N --description 'Ignore patches that seem to be reversed or al... [See Man Page]'
complete -c patch -s o --description 'Send output to  outfile instead of patching f... [See Man Page]'
complete -c patch -o pnum --description 'Strip the smallest prefix containing  num lea... [See Man Page]'
complete -c patch -s r --description 'Put rejects into  rejectfile instead of the d... [See Man Page]'
complete -c patch -s R --description 'Assume that this patch was created with the o... [See Man Page]'
complete -c patch -s s --description 'Work silently, unless an error occurs'
complete -c patch -s t --description 'Suppress questions like  -f , but make some d... [See Man Page]'
complete -c patch -s T --description 'Set the modification and access times of patc... [See Man Page]'
complete -c patch -s u --description 'Interpret the patch file as a unified context... [See Man Page]'
complete -c patch -s v --description 'Print out  patch \'s revision header and patch... [See Man Page]'
complete -c patch -s V --description 'Use  method to determine backup file names'
complete -c patch -s x --description 'Set internal debugging flags of interest only... [See Man Page]'
complete -c patch -s Y --description 'Prefix  pref to the basename of a file name w... [See Man Page]'
complete -c patch -s z --description 'Use  suffix as the simple backup suffix'
complete -c patch -l 'option.' --description 'The names of the files to be patched are usua... [See Man Page]'
complete -c patch -l option
complete -c patch -s p --description or
complete -c patch -l 'option)' --description 'but an RCS, ClearCase, Perforce, or SCCS mast... [See Man Page]'
complete -c patch -l Make --description 'That is, when patching a file, rename or copy... [See Man Page]'
complete -c patch -l Back --description 'and if backups are not otherwise requested'
complete -c patch -l Do --description 'and if backups are not otherwise requested'
complete -c patch -l Prefix --description 'pref to a file name when generating its simpl... [See Man Page]'
complete -c patch -l Read --description 'except for standard output and /dev/tty '
complete -c patch -l Interpret
complete -c patch -l Change --description 'dir immediately, before doing anything else'
complete -c patch -l Use --description '#ifdef  '
complete -c patch -l Print
complete -c patch -l Remove --description 'Normally this option is unnecessary, since pa... [See Man Page]'
complete -c patch -l Assume --description 'ask any questions'
complete -c patch -l Set --description 'This option only applies to diffs that have c... [See Man Page]'
complete -c patch -l This --description 'patch \'s actions when a file is under RCS or ... [See Man Page]'
complete -c patch -l Match --description 'have been munged in your files'
complete -c patch -l Ignore --description 'See also'
complete -c patch -l Send --description 'outfile instead of patching files in place'
complete -c patch -l Strip --description 'num leading slashes from each file name found... [See Man Page]'
complete -c patch -o p0 --description 'gives the entire file name unmodified,'
complete -c patch -o p1 --description gives
complete -c patch -o p4 --description gives
complete -c patch -l Conform --description ' o Take the first existing file from the list... [See Man Page]'
complete -c patch -l Put --description 'rejectfile instead of the default '
complete -c patch -l Work
complete -c patch -l Suppress
complete -c patch -s Z --description or
complete -c patch -l -Y --description or
complete -c patch -l and
complete -c patch -l options --description 'If none of these options are given, then a si... [See Man Page]'
complete -c patch -l Output
complete -c patch -o Np1 --description 'is recommended'
complete -c patch -o 'p0.' --description The

