# pax: Darwin man parser
# Autogenerated from man pages
complete -c pax -s r
complete -c pax -s w
complete -c pax -l rw
complete -c pax -s 0 --description 'Use the NUL'
complete -c pax -s a --description 'Append the given'
complete -c pax -s B --description 'Limit the number of bytes written to a single... [See Man Page]'
complete -c pax -s b --description When
complete -c pax -s c --description 'Match all file or archive members'
complete -c pax -s D --description 'This option is the same as the'
complete -c pax -s d --description 'Cause files of type directory being copied or... [See Man Page]'
complete -c pax -s E --description 'Limit the number of consecutive read faults w... [See Man Page]'
complete -c pax -s f --description Specify
complete -c pax -s G --description 'Select a file based on its'
complete -c pax -s H --description 'Follow only command-line symbolic links while... [See Man Page]'
complete -c pax -s i --description 'Interactively rename files or archive members... [See Man Page]'
complete -c pax -s j --description 'Use bzip2 to compress (decompress) the archiv... [See Man Page]'
complete -c pax -s k --description 'Do not overwrite existing files'
complete -c pax -s L --description 'Follow all symbolic links to perform a logica... [See Man Page]'
complete -c pax -s l --description '(The lowercase letter'
complete -c pax -s n --description 'Select the first archive member that matches ... [See Man Page]'
complete -c pax -s O --description 'Force the archive to be one volume'
complete -c pax -s o --description 'Information to modify the algorithm for extra... [See Man Page]'
complete -c pax -s P --description 'Do not follow symbolic links, perform a physi... [See Man Page]'
complete -c pax -s p --description 'Specify one or more file characteristic optio... [See Man Page]'
complete -c pax -s s --description 'Modify the archive member names according to ... [See Man Page]'
complete -c pax -s T --description 'Allow files to be selected based on a file mo... [See Man Page]'
complete -c pax -s t --description 'Reset the access times of any file or directo... [See Man Page]'
complete -c pax -s U --description 'Select a file based on its'
complete -c pax -s u --description 'Ignore files that are older (having a less re... [See Man Page]'
complete -c pax -s v --description 'During a'
complete -c pax -s X --description 'When traversing the file hierarchy specified ... [See Man Page]'
complete -c pax -s x --description 'Specify the output archive format, with the d... [See Man Page]'
complete -c pax -s Y --description 'This option is the same as the'
complete -c pax -s Z --description 'This option is the same as the'
complete -c pax -s z --description Use
complete -c pax -l -insecure --description Normally

