# pbcopy: Deroffing man parser
# Autogenerated from man pages
complete -c pbcopy -o pboard --description 'specifies which pasteboard to copy to or past... [See Man Page]'
complete -c pbcopy -o Prefer --description 'tells pbpaste what type of data to look for i... [See Man Page]'

