# pcap-config: Deroffing man parser
# Autogenerated from man pages
complete -c pcap-config -l cflags --description 'option, pcap-config writes to the standard ou... [See Man Page]'
complete -c pcap-config -s I --description 'compiler flags required to include libpcap\'s ... [See Man Page]'
complete -c pcap-config -l libs --description 'option, pcap-config writes to the standard ou... [See Man Page]'
complete -c pcap-config -s L --description and
complete -c pcap-config -s l --description 'linker flags required to link with libpcap, i... [See Man Page]'
complete -c pcap-config -l additional-libs --description 'option, pcap-config writes to the standard ou... [See Man Page]'
complete -c pcap-config -o lpcap --description 'flag to link with libpcap itself'
complete -c pcap-config -l static --description 'flag causes it to write flags appropriate for... [See Man Page]'

