# pcastlibrary_prerequisite_check: Darwin man parser
# Autogenerated from man pages
complete -c pcastlibrary_prerequisite_check -s a --description 'Description of -a flag'
complete -c pcastlibrary_prerequisite_check -s b --description 'Description of -b flag'

