# pear: Darwin man parser
# Autogenerated from man pages
complete -c pear -s c --description 'find user configuration in'
complete -c pear -s C --description 'find system configuration in'
complete -c pear -s d --description 'set user config variable'
complete -c pear -s D --description 'set system config variable'
complete -c pear -s G --description 'start in graphical (Gtk) mode'
complete -c pear -s h --description 'display help/usage (this message)'
complete -c pear -s q --description 'be quiet, decrease verbosity level'
complete -c pear -s s --description 'store user configuration'
complete -c pear -s S --description 'store system configuration'
complete -c pear -s u --description 'unset `foo\' in the user configuration'
complete -c pear -s v --description 'increase verbosity level (default 1)'
complete -c pear -s V --description 'version information'

