# perfdiagnose: Darwin man parser
# Autogenerated from man pages
complete -c perfdiagnose -s h --description 'Print full usage'
complete -c perfdiagnose -s f --description 'Specify the directory where the results will ... [See Man Page]'
complete -c perfdiagnose -s t --description 'Enable "Thorough Mode"'

