# pg_basebackup: Deroffing man parser
# Autogenerated from man pages
complete -c pg_basebackup -s D -l pgdata --description 'Directory to write the output to'
complete -c pg_basebackup -s x -l xlog --description 'Includes the required transaction log files (... [See Man Page]'
complete -c pg_basebackup -s z -l gzip --description 'Enables gzip compression of tar file output, ... [See Man Page]'
complete -c pg_basebackup -s Z -l compress --description 'Enables gzip compression of tar file output, ... [See Man Page]'
complete -c pg_basebackup -s c -l checkpoint --description 'Sets checkpoint mode to fast or spread (defau... [See Man Page]'
complete -c pg_basebackup -s l -l label --description 'Sets the label for the backup'
complete -c pg_basebackup -s P -l progress --description 'Enables progress reporting'
complete -c pg_basebackup -s v -l verbose --description 'Enables verbose mode'
complete -c pg_basebackup -s h -l host --description 'Specifies the host name of the machine on whi... [See Man Page]'
complete -c pg_basebackup -s p -l port --description 'Specifies the TCP port or local Unix domain s... [See Man Page]'
complete -c pg_basebackup -s U -l username --description 'User name to connect as'
complete -c pg_basebackup -s w -l no-password --description 'Never issue a password prompt'
complete -c pg_basebackup -s W -l password --description 'Force pg_basebackup to prompt for a password ... [See Man Page]'
complete -c pg_basebackup -s V -l version --description 'Print the pg_basebackup version and exit'
complete -c pg_basebackup -s '?' -l help --description 'Show help about pg_basebackup command line ar... [See Man Page]'
complete -c pg_basebackup -s F -l format

