# pg_controldata: Deroffing man parser
# Autogenerated from man pages
complete -c pg_controldata -s V --description and
complete -c pg_controldata -l version --description 'pg_controldata version and exit'
complete -c pg_controldata -s '?' --description and
complete -c pg_controldata -l help --description ENVIRONMENT

