# pg_resetxlog: Deroffing man parser
# Autogenerated from man pages
complete -c pg_resetxlog -s f --description '(force) switch'
complete -c pg_resetxlog -s o
complete -c pg_resetxlog -s x
complete -c pg_resetxlog -s e
complete -c pg_resetxlog -s m
complete -c pg_resetxlog -s O
complete -c pg_resetxlog -s l --description 'switches allow the next OID, next transaction... [See Man Page]'
complete -c pg_resetxlog -s n --description '(no operation) switch instructs pg_resetxlog ... [See Man Page]'
complete -c pg_resetxlog -s V --description and
complete -c pg_resetxlog -l version --description 'options print the pg_resetxlog version and ex... [See Man Page]'
complete -c pg_resetxlog -s '?' --description and
complete -c pg_resetxlog -l help --description 'show supported arguments, and exit'

