# phar: Darwin man parser
# Autogenerated from man pages
complete -c phar -s f --description 'Specifies the phar file to work on'
complete -c phar -s c --description 'Selects the compression algorithm from the fo... [See Man Page]'
complete -c phar -s h --description 'Selects the hash algorithm from the following... [See Man Page]'
complete -c phar -s k --description 'Subscription index (a string'
complete -c phar -s a --description 'Provide an alias name for the phar file'
complete -c phar -s i --description 'Specifies a regular expression for input file... [See Man Page]'
complete -c phar -s l --description 'Number of preceeding subdirectories to strip ... [See Man Page]'
complete -c phar -s x --description 'Regular expression for input files to exclude... [See Man Page]'
complete -c phar -s e --description 'Name of entry to work on (must include PHAR i... [See Man Page]'
complete -c phar -s m --description 'Meta data to store with entry (serialized php... [See Man Page]'
complete -c phar -s b --description 'Hash-bang line to start the archive (e'
complete -c phar -s p --description 'Location of'
complete -c phar -s s --description 'Select the stub file'
complete -c phar -s y --description 'Private key for OpenSSL signing'

