# php-config: Deroffing man parser
# Autogenerated from man pages
complete -c php-config -l prefix --description 'Directory prefix where PHP is installed, e'
complete -c php-config -l includes --description 'List of -I options with all include files'
complete -c php-config -l ldflags --description 'LD Flags which PHP was compiled with'
complete -c php-config -l libs --description 'Extra libraries which PHP was compiled with'
complete -c php-config -l man-dir --description 'The directory prefix where the manpages is in... [See Man Page]'
complete -c php-config -l extension-dir --description 'Directory where extensions are searched by de... [See Man Page]'
complete -c php-config -l include-dir --description 'Directory prefix where header files are insta... [See Man Page]'
complete -c php-config -l php-binary --description 'Full path to php CLI or CGI binary'
complete -c php-config -l php-sapis --description 'Show all SAPI modules available'
complete -c php-config -l configure-options --description 'Configure options to recreate configuration o... [See Man Page]'
complete -c php-config -l version --description 'PHP version'
complete -c php-config -l vernum --description 'PHP version as integer'

