# php: Deroffing man parser
# Autogenerated from man pages
complete -c php -s a --description 'Run PHP interactively'
complete -c php -s b --description 'Bind Path for external FASTCGI Server mode (C... [See Man Page]'
complete -c php -s C --description 'Do not chdir to the script\'s directory (CGI o... [See Man Page]'
complete -c php -s q --description Quiet-mode
complete -c php -s T --description 'Measure execution time of script repeated cou... [See Man Page]'
complete -c php -s c --description 'Look for   php'
complete -c php -s n --description 'No   php'
complete -c php -s d --description 'Define INI entry  R foo  with value R bar'
complete -c php -s e --description 'Generate extended information for debugger/pr... [See Man Page]'
complete -c php -s f --description 'Parse and execute  R file'
complete -c php -s g --description 'Make variable R name global in script'
complete -c php -s h --description 'This help'
complete -c php -s H --description 'Hide script name (file) and parameters (args\\... [See Man Page]'
complete -c php -s i --description 'PHP information and configuration'
complete -c php -s l --description 'Syntax check only (lint)'
complete -c php -s m --description 'Show compiled in modules'
complete -c php -s r --description 'Run PHP  R code without using script tags  \'<... [See Man Page]'
complete -c php -s B --description 'Run PHP  R code before processing input lines'
complete -c php -s R --description 'Run PHP  R code for every input line'
complete -c php -s F --description 'Parse and execute  R file for every input lin... [See Man Page]'
complete -c php -s E --description 'Run PHP  R code after processing all input li... [See Man Page]'
complete -c php -s s --description 'Output HTML syntax highlighted source'
complete -c php -s v --description 'Version number'
complete -c php -s w --description 'Output source with stripped comments and whit... [See Man Page]'
complete -c php -s z --description 'Load Zend extension  R file'
complete -c php -l rfunction --description 'R name'
complete -c php -l rf --description 'R name Shows information about function  name'
complete -c php -l rclass --description 'R name'
complete -c php -l rc --description 'R name Shows information about class  name'
complete -c php -l rextension --description 'R name'
complete -c php -l re --description 'R name Shows information about extension  nam... [See Man Page]'
complete -c php -l rextinfo --description 'R name'
complete -c php -l ri --description 'R name Shows configuration for extension  nam... [See Man Page]'
complete -c php -l interactive
complete -c php -l bindpath
complete -c php -l no-chdir
complete -c php -l no-header
complete -c php -l timing
complete -c php -l php-ini
complete -c php -l no-php-ini
complete -c php -l define
complete -c php -l file
complete -c php -l global
complete -c php -l help
complete -c php -l hide-args
complete -c php -l info
complete -c php -l syntax-check
complete -c php -l modules
complete -c php -l run
complete -c php -l process-begin
complete -c php -l process-code
complete -c php -l process-file
complete -c php -l process-end
complete -c php -l syntax-highlight
complete -c php -l version
complete -c php -l stripped
complete -c php -l zend-extension
complete -c php -l ini --description 'Show configuration file names FILES'

