# phpize: Deroffing man parser
# Autogenerated from man pages
complete -c phpize -l clean --description 'Remove all created files'
complete -c phpize -l help --description 'Prints usage information'
complete -c phpize -s v --description 'Prints API version information'
complete -c phpize -l version

