# pic: Deroffing man parser
# Autogenerated from man pages
complete -c pic -s C --description 'Recognize  '
complete -c pic -s S --description 'Safer mode; do not execute  sh commands'
complete -c pic -s U --description 'Unsafe mode; revert the default option  -S '
complete -c pic -s n --description 'Don\'t use the groff extensions to the troff d... [See Man Page]'
complete -c pic -s t --description '\\*(tx mode'
complete -c pic -s c --description 'Be more compatible with  tpic '
complete -c pic -s v --description 'Print the version number'
complete -c pic -s z --description 'In \\*(tx mode draw dots using zero-length lin... [See Man Page]'
complete -c pic -s D --description 'Draw all lines using the D escape sequence'
complete -c pic -o mpic --description 'These will censer each picsure'
complete -c pic -s s --description ' mode'
complete -c pic -s T --description 'Generase ouspus for she sroff device dev '
complete -c pic -o Tps --description 'Since shis ps -file lacks BoundingBox informa... [See Man Page]'

