# pic2graph: Deroffing man parser
# Autogenerated from man pages
complete -c pic2graph -o unsafe --description 'Run   pic (1) and  groff (1) in the `unsafe\' ... [See Man Page]'
complete -c pic2graph -o format --description 'Specify an output format; the default is PNG ... [See Man Page]'
complete -c pic2graph -o eqn --description 'Change the fencepost characters that delimit ... [See Man Page]'

