# pidof: Deroffing man parser
# Autogenerated from man pages
complete -c pidof -s l --description 'prints output in long format, rather than jus... [See Man Page]'
complete -c pidof -s k --description 'kill process(es) by name'
complete -c pidof -s h -s '?' --description 'print out help'
complete -c pidof -s v --description 'prints out version info on pidof'

