# pkg-config: Deroffing man parser
# Autogenerated from man pages
complete -c pkg-config -l modversion --description 'Requests that the version information of the ... [See Man Page]'
complete -c pkg-config -l version --description 'Displays the version of  pkg-config and termi... [See Man Page]'
complete -c pkg-config -l help --description 'Displays a help message and terminates'
complete -c pkg-config -l print-errors --description 'If one or more of the modules on the command ... [See Man Page]'
complete -c pkg-config -l silence-errors --description 'If one or more of the modules on the command ... [See Man Page]'
complete -c pkg-config -l errors-to-stdout --description 'If printing errors, print them to stdout rath... [See Man Page]'
complete -c pkg-config -l debug --description 'Print debugging information'
complete -c pkg-config -l cflags --description 'This prints pre-processor and compile flags r... [See Man Page]'
complete -c pkg-config -l cflags-only-I --description 'This prints the -I part of "--cflags"'
complete -c pkg-config -l libs --description 'This option is identical to "--cflags", only ... [See Man Page]'
complete -c pkg-config -l libs-only-L --description 'This prints the -L/-R part of "--libs"'
complete -c pkg-config -l libs-only-l --description 'This prints the -l part of "--libs" for the l... [See Man Page]'
complete -c pkg-config -l variable --description 'This returns the value of a variable defined ... [See Man Page]'
complete -c pkg-config -l define-variable --description 'This sets a global value for a variable, over... [See Man Page]'
complete -c pkg-config -l print-variables --description 'Returns a list of all variables defined in th... [See Man Page]'
complete -c pkg-config -l uninstalled --description 'Normally if you request the package "foo" and... [See Man Page]'
complete -c pkg-config -l max-version --description 'These options test whether the package or lis... [See Man Page]'
complete -c pkg-config -l msvc-syntax --description 'This option is available only on Windows'
complete -c pkg-config -l dont-define-prefix --description 'This option is available only on Windows'
complete -c pkg-config -l prefix-variable --description 'Also this option is available only on Windows... [See Man Page]'
complete -c pkg-config -l static --description 'Output libraries suitable for static linking'
complete -c pkg-config -l list-all --description 'List all modules found in the pkg-config path... [See Man Page]'
complete -c pkg-config -s I -l print-provides --description 'List all modules the given packages provides'
complete -c pkg-config -l print-requires --description 'List all modules the given packages requires'
complete -c pkg-config -o 'rdynamic.'
complete -c pkg-config -l exists
complete -c pkg-config -l atleast-version
complete -c pkg-config -l exact-version
complete -c pkg-config -o Lx:/some/path --description 'it prints /libpath:x/some/path, and instead o... [See Man Page]'
complete -c pkg-config -l print-requires-private --description 'List all modules the given packages requires ... [See Man Page]'

