# plockstat: Deroffing man parser
# Autogenerated from man pages
complete -c plockstat -s v --description 'print a message when tracing starts'
complete -c plockstat -s A --description 'trace contention and hold events (same as -CH... [See Man Page]'
complete -c plockstat -s C --description 'trace contention events for mutexes and rwloc... [See Man Page]'
complete -c plockstat -s H --description 'trace hold events for mutexes and rwlocks'
complete -c plockstat -s V --description 'print the dtrace script to run'
complete -c plockstat -s n --description 'display only \'count\' entries for each event t... [See Man Page]'
complete -c plockstat -s s --description 'show stack trace upto \'depth\' entries'
complete -c plockstat -s e --description 'exit after specified seconds'
complete -c plockstat -s x --description 'enable a DTrace runtime option or a D compile... [See Man Page]'
complete -c plockstat -s p --description 'attach and trace the specified process id SEE... [See Man Page]'

