# plutil: Darwin man parser
# Autogenerated from man pages
complete -c plutil -l help --description 'Show the usage information for the command an... [See Man Page]'
complete -c plutil -l lint --description 'Check the named property list files for synta... [See Man Page]'
complete -c plutil -l convert --description 'Convert the named '
complete -c plutil -s s --description 'Don\'t print anything on success'
complete -c plutil -s r --description 'For JSON, add whitespace and indentation to m... [See Man Page]'
complete -c plutil -s o --description 'Specify an alternate path name for the result... [See Man Page]'
complete -c plutil -s e --description 'Specify an alternate extension for converted ... [See Man Page]'

