# pod2man: Type1
# Autogenerated from man pages
complete -c pod2man -s c -l center --description 'Sets the centered page header to string'
complete -c pod2man -s d -l date --description 'Set the left-hand footer string to this value... [See Man Page]'
complete -c pod2man -l fixed --description 'The fixed-width font to use for verbatim text... [See Man Page]'
complete -c pod2man -l fixedbold --description 'Bold version of the fixed-width font'
complete -c pod2man -l fixeditalic --description 'Italic version of the fixed-width font (actua... [See Man Page]'
complete -c pod2man -l fixedbolditalic --description 'Bold italic (probably actually oblique) versi... [See Man Page]'
complete -c pod2man -s h -l help --description 'Print out usage information'
complete -c pod2man -s l -l lax --description 'No longer used'
complete -c pod2man -s n -l name --description 'Set the name of the manual page to name'
complete -c pod2man -s o -l official --description 'Set the default header to indicate that this ... [See Man Page]'
complete -c pod2man -s q -l quotes --description 'Sets the quote marks used to surround C<> tex... [See Man Page]'
complete -c pod2man -s r -l release --description 'Set the centered footer'
complete -c pod2man -s s -l section --description 'Set the section for the \\f(CW\\*(C`'
complete -c pod2man -l stderr --description 'By default, pod2man puts any errors detected ... [See Man Page]'
complete -c pod2man -s u -l utf8 --description 'By default, pod2man produces the most conserv... [See Man Page]'

