# podcastfeed: Darwin man parser
# Autogenerated from man pages
complete -c podcastfeed -s a --description 'Description of -a flag'
complete -c podcastfeed -s b --description 'Description of -b flag'

