# postlog: Deroffing man parser
# Autogenerated from man pages
complete -c postlog -s c --description 'Read the main'
complete -c postlog -s i --description 'Include the process ID in the logging tag'
complete -c postlog -s p --description 'Specifies the logging severity: info (default... [See Man Page]'
complete -c postlog -s t --description 'Specifies the logging tag, that is, the ident... [See Man Page]'
complete -c postlog -s v --description 'Enable verbose logging for debugging purposes... [See Man Page]'

