# post-grohtml: Deroffing man parser
# Autogenerated from man pages
complete -c post-grohtml -s a --description 'Number of bits of antialiasing information to... [See Man Page]'
complete -c post-grohtml -s b --description 'Initialize the background color to white'
complete -c post-grohtml -s D --description 'Inform  grohtml to place all image files into... [See Man Page]'
complete -c post-grohtml -s F --description 'Prepend directory B dir /dev name to the sear... [See Man Page]'
complete -c post-grohtml -s g --description 'Number of bits of antialiasing information to... [See Man Page]'
complete -c post-grohtml -s h --description 'Generate section and number headings by using... [See Man Page]'
complete -c post-grohtml -s i --description 'Select the resolution for all images'
complete -c post-grohtml -s I --description 'Determine the image stem name'
complete -c post-grohtml -s j --description 'Inform  grohtml to split the html output into... [See Man Page]'
complete -c post-grohtml -s l --description 'Turn off the production of automatic section ... [See Man Page]'
complete -c post-grohtml -s n --description 'Generate simple heading anchors whenever a se... [See Man Page]'
complete -c post-grohtml -s o --description 'Specify the vertical offset of images in poin... [See Man Page]'
complete -c post-grohtml -s p --description 'Display page rendering progress to stderr'
complete -c post-grohtml -s r --description 'Turn off the automatic header and footer line... [See Man Page]'
complete -c post-grohtml -s s --description 'Set the base point size of the source file'
complete -c post-grohtml -s S --description 'When splitting html output, split at the head... [See Man Page]'
complete -c post-grohtml -o Thtml --description option
complete -c post-grohtml -s P --description option
complete -c post-grohtml -o i200 --description 'indicates 200 pixels per inch'
complete -c post-grohtml -s v --description 'Print the version number'

