# postmulti: Deroffing man parser
# Autogenerated from man pages
complete -c postmulti -s a --description 'Perform the operation on all instances'
complete -c postmulti -s g --description 'Perform the operation only for members of the... [See Man Page]'
complete -c postmulti -s i --description 'Perform the operation only for the instance w... [See Man Page]'
complete -c postmulti -s R --description 'Reverse the iteration order'
complete -c postmulti -s l --description 'List Postfix instances with their instance na... [See Man Page]'
complete -c postmulti -s p --description 'Invoke postfix(1) to execute the specified co... [See Man Page]'
complete -c postmulti -s x --description 'Execute the specified command for all Postfix... [See Man Page]'
complete -c postmulti -s v --description 'Enable verbose logging for debugging purposes... [See Man Page]'
complete -c postmulti -s I --description 'Assign the specified instance name to an exis... [See Man Page]'
complete -c postmulti -s G --description 'Assign the specified group name to an existin... [See Man Page]'
complete -c postmulti -s e --description '"Edit" managed instances'

