# postdrop: Deroffing man parser
# Autogenerated from man pages
complete -c postdrop -s c --description 'The main'
complete -c postdrop -s r --description 'Use a Postfix-internal protocol for reading t... [See Man Page]'
complete -c postdrop -s v --description 'Enable verbose logging for debugging purposes... [See Man Page]'

