# postmap: Deroffing man parser
# Autogenerated from man pages
complete -c postmap -s b --description 'Enable message body query mode'
complete -c postmap -s c --description 'Read the main'
complete -c postmap -s d --description 'Search the specified maps for key and remove ... [See Man Page]'
complete -c postmap -s f --description 'Do not fold the lookup key to lower case whil... [See Man Page]'
complete -c postmap -s h --description 'Enable message header query mode'
complete -c postmap -s i --description 'Incremental mode'
complete -c postmap -s m --description 'Enable MIME parsing with "-b" and "-h"'
complete -c postmap -s N --description 'Include the terminating null character that t... [See Man Page]'
complete -c postmap -s n --description 'Don\'t include the terminating null character ... [See Man Page]'
complete -c postmap -s o --description 'Do not release root privileges when processin... [See Man Page]'
complete -c postmap -s p --description 'Do not inherit the file access permissions fr... [See Man Page]'
complete -c postmap -s q --description 'Search the specified maps for key and write t... [See Man Page]'
complete -c postmap -s r --description 'When updating a table, do not complain about ... [See Man Page]'
complete -c postmap -s s --description 'Retrieve all database elements, and write one... [See Man Page]'
complete -c postmap -s v --description 'Enable verbose logging for debugging purposes... [See Man Page]'
complete -c postmap -s w --description 'When updating a table, do not complain about ... [See Man Page]'

