# postcat: Deroffing man parser
# Autogenerated from man pages
complete -c postcat -s b --description 'Show body content'
complete -c postcat -s c --description 'The main'
complete -c postcat -s d --description 'Print the decimal type of each record'
complete -c postcat -s e --description 'Show message envelope content'
complete -c postcat -s h --description 'Show message header content'
complete -c postcat -s o --description 'Print the queue file offset of each record'
complete -c postcat -s q --description 'Search the Postfix queue for the named files ... [See Man Page]'
complete -c postcat -s v --description 'Enable verbose logging for debugging purposes... [See Man Page]'

