# postconf: Deroffing man parser
# Autogenerated from man pages
complete -c postconf -s a --description 'List the available SASL server plug-in types'
complete -c postconf -s A --description 'List the available SASL client plug-in types'
complete -c postconf -s b --description 'Display the message text that appears at the ... [See Man Page]'
complete -c postconf -s c --description 'The main'
complete -c postconf -s d --description 'Print default parameter settings instead of a... [See Man Page]'
complete -c postconf -s e --description 'Edit the main'
complete -c postconf -s h --description 'Show parameter values only, not the "name = "... [See Man Page]'
complete -c postconf -s l --description 'List the names of all supported mailbox locki... [See Man Page]'
complete -c postconf -s m --description 'List the names of all supported lookup table ... [See Man Page]'
complete -c postconf -s n --description 'Print parameter settings that are not left at... [See Man Page]'
complete -c postconf -s t --description 'Display the templates for delivery status not... [See Man Page]'
complete -c postconf -s v --description 'Enable verbose logging for debugging purposes... [See Man Page]'
complete -c postconf -s '#' --description 'Edit the main'

