# postalias: Deroffing man parser
# Autogenerated from man pages
complete -c postalias -s c --description 'Read the main'
complete -c postalias -s d --description 'Search the specified maps for key and remove ... [See Man Page]'
complete -c postalias -s f --description 'Do not fold the lookup key to lower case whil... [See Man Page]'
complete -c postalias -s i --description 'Incremental mode'
complete -c postalias -s N --description 'Include the terminating null character that t... [See Man Page]'
complete -c postalias -s n --description 'Don\'t include the terminating null character ... [See Man Page]'
complete -c postalias -s o --description 'Do not release root privileges when processin... [See Man Page]'
complete -c postalias -s p --description 'Do not inherit the file access permissions fr... [See Man Page]'
complete -c postalias -s q --description 'Search the specified maps for key and write t... [See Man Page]'
complete -c postalias -s r --description 'When updating a table, do not complain about ... [See Man Page]'
complete -c postalias -s s --description 'Retrieve all database elements, and write one... [See Man Page]'
complete -c postalias -s v --description 'Enable verbose logging for debugging purposes... [See Man Page]'
complete -c postalias -s w --description 'When updating a table, do not complain about ... [See Man Page]'

