# postkick: Deroffing man parser
# Autogenerated from man pages
complete -c postkick -s c --description 'Read the main'
complete -c postkick -s v --description 'Enable verbose logging for debugging purposes... [See Man Page]'

