# postfix: Deroffing man parser
# Autogenerated from man pages
complete -c postfix -s c --description 'Read the main'
complete -c postfix -s D --description 'Run each Postfix daemon under control of a de... [See Man Page]'
complete -c postfix -s v --description 'Enable verbose logging for debugging purposes... [See Man Page]'

