# postlock: Deroffing man parser
# Autogenerated from man pages
complete -c postlock -s c --description 'Read the main'
complete -c postlock -s l --description 'Override the locking method specified via the... [See Man Page]'
complete -c postlock -s v --description 'Enable verbose logging for debugging purposes... [See Man Page]'

