# ppm2tiff: Deroffing man parser
# Autogenerated from man pages
complete -c ppm2tiff -s c --description 'Specify a compression scheme to use when writ... [See Man Page]'
complete -c ppm2tiff -s r --description 'Write data with a specified number of rows pe... [See Man Page]'
complete -c ppm2tiff -s R --description 'Mark the resultant image to have the specifie... [See Man Page]'

