# pr: Darwin man parser
# Autogenerated from man pages
complete -c pr -l column --description 'Produce output that is'
complete -c pr -s a --description 'Modify the effect of the'
complete -c pr -s d --description 'Produce output that is double spaced'
complete -c pr -s e
complete -c pr -s F --description 'Use a'
complete -c pr -s f --description 'Same as'
complete -c pr -s h --description 'Use the string'
complete -c pr -s i
complete -c pr -s L --description Use
complete -c pr -s l --description 'Override the 66 line default and reset the pa... [See Man Page]'
complete -c pr -s m --description 'Merge the contents of multiple files'
complete -c pr -s n
complete -c pr -s o --description 'Each line of output is preceded by'
complete -c pr -s p --description 'Pause before each page if the standard output... [See Man Page]'
complete -c pr -s r --description 'Write no diagnostic reports on failure to ope... [See Man Page]'
complete -c pr -s s --description 'Separate text columns by the single character... [See Man Page]'
complete -c pr -s t --description 'Print neither the five-line identifyingheader... [See Man Page]'
complete -c pr -s w --description 'Set the width of the line to'

