# praudit: Darwin man parser
# Autogenerated from man pages
complete -c praudit -s d --description 'Specifies the delimiter'
complete -c praudit -s l --description 'Prints the entire record on the same line'
complete -c praudit -s n --description 'Do not convert user and group IDs to their na... [See Man Page]'
complete -c praudit -s p --description 'Specify this option if input to'
complete -c praudit -s r --description 'Prints the records in their raw form'
complete -c praudit -s s --description 'Prints the records in their short form'
complete -c praudit -s x --description 'Print audit records in the XML output format'

