# procmail: Deroffing man parser
# Autogenerated from man pages
complete -c procmail -s v --description 'Procmail will print its version number, displ... [See Man Page]'
complete -c procmail -s p --description 'Preserve any old environment'
complete -c procmail -s t --description 'Make procmail fail softly, i'
complete -c procmail -s f --description 'Causes procmail to regenerate the leading `Fr... [See Man Page]'
complete -c procmail -s o --description 'Instead of allowing anyone to generate `From ... [See Man Page]'
complete -c procmail -s Y --description 'Assume traditional Berkeley mailbox format, i... [See Man Page]'
complete -c procmail -s a --description 'This will set $1 to be equal to R argument '
complete -c procmail -s d --description 'This turns on explicit delivery mode, deliver... [See Man Page]'
complete -c procmail -s m --description 'Turns procmail into a general purpose mail fi... [See Man Page]'

