# proj: Deroffing man parser
# Autogenerated from man pages
complete -c proj -s b --description 'Special option for binary coordinate data inp... [See Man Page]'
complete -c proj -s i --description 'Selects binary input only (see  -b option)'
complete -c proj -s I --description 'alternate method to specify inverse projectio... [See Man Page]'
complete -c proj -s o --description 'Selects binary output only (see  -b option)'
complete -c proj -s t --description 'A specifies a character employed as the first... [See Man Page]'
complete -c proj -s e --description 'String is an arbitrary string to be output if... [See Man Page]'
complete -c proj -s E --description 'causes the input coordinates to be copied to ... [See Man Page]'
complete -c proj -s l --description 'List projection identifiers with  -l,  -lp or... [See Man Page]'
complete -c proj -s r --description 'This options reverses the order of the expect... [See Man Page]'
complete -c proj -s s --description 'This options reverses the order of the output... [See Man Page]'
complete -c proj -s S --description 'Causes estimation of  meridinal and  parallel... [See Man Page]'
complete -c proj -s m --description 'The cartesian data may be scaled by the  mult... [See Man Page]'
complete -c proj -s f --description 'Format is a  printf format string to control ... [See Man Page]'
complete -c proj -o '[w' --description 'N is the number of significant fractional dig... [See Man Page]'
complete -c proj -s v --description 'causes a listing of cartographic control para... [See Man Page]'
complete -c proj -s V --description 'This option causes an expanded annotated list... [See Man Page]'
complete -c proj -o lp --description or
complete -c proj -o lP --description 'that can be selected with +proj'
complete -c proj -o le --description 'that can be selected with +ellps,'
complete -c proj -o lu --description 'list of cartesian to meter conversion factors... [See Man Page]'
complete -c proj -o ld --description 'list of datums that can be selected with  +da... [See Man Page]'
complete -c proj -o w3 --description 'is assumed)'
complete -c proj -s W --description 'is employed the fields will be constant width... [See Man Page]'
complete -c proj -s T --description option
complete -c proj -s w --description 'switch is not employed) and precise to 0'

