# psed: Type1
# Autogenerated from man pages
complete -c psed -s a --description 'A file specified as argument to the w edit co... [See Man Page]'
complete -c psed -s e --description 'The editing commands defined by script are ap... [See Man Page]'
complete -c psed -s f --description 'Editing commands from the specified script-fi... [See Man Page]'

