# pstopdf: Darwin man parser
# Autogenerated from man pages
complete -c pstopdf -s o --description 'The name of the output file to create'
complete -c pstopdf -s i --description 'Reads from stdin rather than a named input fi... [See Man Page]'
complete -c pstopdf -s l --description 'Specifies that any messages generated during ... [See Man Page]'
complete -c pstopdf -s p --description 'Generates a simple progress message to stdout... [See Man Page]'

