# pump: Type1
# Autogenerated from man pages
complete -c pump -l help --description 'Displays summary instructions'
complete -c pump -l startup --description 'Starts an include server, and outputs the env... [See Man Page]'

