# pwd: Darwin man parser
# Autogenerated from man pages
complete -c pwd -s L --description 'Display the logical current working directory... [See Man Page]'
complete -c pwd -s P --description 'Display the physical current working director... [See Man Page]'

