# pydoc: Darwin man parser
# Autogenerated from man pages
complete -c pydoc -s k --description 'Search for a keyword in the synopsis lines of... [See Man Page]'
complete -c pydoc -s p --description 'Start an HTTP server on the given port on the... [See Man Page]'
complete -c pydoc -s g --description 'Pop up a graphical interface for finding and ... [See Man Page]'
complete -c pydoc -s w --description 'Write out the HTML documentation for a module... [See Man Page]'
complete -c pydoc -l -help --description 'Prints out a help message'

