# quartz-wm: Darwin man parser
# Autogenerated from man pages
complete -c quartz-wm -l -prefs-domain --description 'This option can be used to override the domai... [See Man Page]'
complete -c quartz-wm -l -only-proxy --description 'This option indicates that the program should... [See Man Page]'
complete -c quartz-wm -l -no-pasteboard --description 'This option indicates that the program should... [See Man Page]'

