# quota: Darwin man parser
# Autogenerated from man pages
complete -c quota -s g --description 'Print group quotas for the group of which the... [See Man Page]'
complete -c quota -s v
complete -c quota -s q --description 'Print a more terse message,containing only in... [See Man Page]'

