# raw2tiff: Deroffing man parser
# Autogenerated from man pages
complete -c raw2tiff -s H --description 'size of input image file header in bytes (0 b... [See Man Page]'
complete -c raw2tiff -s w --description 'width of input image in pixels (can be guesse... [See Man Page]'
complete -c raw2tiff -s l --description 'length of input image in lines (can be guesse... [See Man Page]'
complete -c raw2tiff -s b --description 'number of bands in input image (1 by default)... [See Man Page]'
complete -c raw2tiff -s d --description 'type of samples in input image, where  data_t... [See Man Page]'
complete -c raw2tiff -s i --description 'type of samples interleaving in input image, ... [See Man Page]'
complete -c raw2tiff -s p --description 'photometric interpretation (color space) of t... [See Man Page]'
complete -c raw2tiff -s s --description 'swap bytes fetched from the input file'
complete -c raw2tiff -s L --description 'input data has LSB2MSB bit order (default)'
complete -c raw2tiff -s M --description 'input data has MSB2LSB bit order'
complete -c raw2tiff -s c --description 'Specify a compression scheme to use when writ... [See Man Page]'
complete -c raw2tiff -s r --description 'Write data with a specified number of rows pe... [See Man Page]'

