# rcp: Darwin man parser
# Autogenerated from man pages
complete -c rcp -s 4 --description 'Use IPv4 addresses only'
complete -c rcp -s 6 --description 'Use IPv6 addresses only'
complete -c rcp -s p --description Cause
complete -c rcp -s r --description 'If any of the source files are directories,'

