# rcsclean: Deroffing man parser
# Autogenerated from man pages
complete -c rcsclean -s k --description 'Use  subst style keyword substitution when re... [See Man Page]'
complete -c rcsclean -s n --description 'Do not actually remove any files or unlock an... [See Man Page]'
complete -c rcsclean -s q --description 'Do not log the actions taken on standard outp... [See Man Page]'
complete -c rcsclean -s r --description 'This option has no effect other than specifyi... [See Man Page]'
complete -c rcsclean -s T --description 'Preserve the modification time on the \\*r fil... [See Man Page]'
complete -c rcsclean -s u --description 'Unlock the revision if it is locked and no di... [See Man Page]'
complete -c rcsclean -s V --description 'Print \\*r\'s version number'
complete -c rcsclean -s x --description 'Use  suffixes to characterize \\*r files'
complete -c rcsclean -s z --description 'Use zone as the time zone for keyword substit... [See Man Page]'

