# rcsdiff: Deroffing man parser
# Autogenerated from man pages
complete -c rcsdiff -s q --description 'suppresses diagnostic output'
complete -c rcsdiff -s r --description 'The option'
complete -c rcsdiff -s k --description 'affects keyword substitution when extracting ... [See Man Page]'
complete -c rcsdiff -o kk -o 'r1.1' -o 'r1.2' --description 'ignores differences in keyword values when co... [See Man Page]'
complete -c rcsdiff -o kkvl --description 'is assumed if (1) at most one revision option... [See Man Page]'
complete -c rcsdiff -o kkv --description 'is the default keyword substitution, and (4) ... [See Man Page]'
complete -c rcsdiff -s T
complete -c rcsdiff -s V
complete -c rcsdiff -s x --description and
complete -c rcsdiff -s z --description 'Otherwise, all options of diff (1) that apply... [See Man Page]'

