# rdjpgcom: Deroffing man parser
# Autogenerated from man pages
complete -c rdjpgcom -o raw --description 'Normally rdjpgcom escapes non-printable chara... [See Man Page]'
complete -c rdjpgcom -o verbose --description 'Causes rdjpgcom to also display the JPEG imag... [See Man Page]'

