# rebase: Darwin man parser
# Autogenerated from man pages
complete -c rebase -l low_address --description 'Force the base address for the first image to... [See Man Page]'
complete -c rebase -l high_address --description 'Force the base address for the last image to ... [See Man Page]'
complete -c rebase -l arch --description 'Only rebase the specified architecture'
complete -c rebase -s v --description Verbose

