# redo_prebinding: Deroffing man parser
# Autogenerated from man pages
complete -c redo_prebinding -s c --description 'only check if the file needs to have it\'s pre... [See Man Page]'
complete -c redo_prebinding -s p --description 'check only for prebound files and return stat... [See Man Page]'
complete -c redo_prebinding -s d --description 'check only for dynamic shared library files a... [See Man Page]'
complete -c redo_prebinding -s i --description 'ignore non-prebound files (useful when runnin... [See Man Page]'
complete -c redo_prebinding -s z --description 'zero out the prebind check sum in the output ... [See Man Page]'
complete -c redo_prebinding -s u --description 'unprebind, rather than reprebind (-c, -p, -d,... [See Man Page]'
complete -c redo_prebinding -s e --description 'replace any dependent library\'s "@executable_... [See Man Page]'
complete -c redo_prebinding -o seg_addr_table --description 'The  -seg_addr_table option is used when the ... [See Man Page]'
complete -c redo_prebinding -o seg_addr_table_filename --description 'Use  pathname instead of the install name of ... [See Man Page]'
complete -c redo_prebinding -o seg1addr --description 'Move the input library to base address  addre... [See Man Page]'
complete -c redo_prebinding -s r --description 'prepend the  rootdir argument to all dependen... [See Man Page]'
complete -c redo_prebinding -s o --description 'write the updated file into  output_file rath... [See Man Page]'
complete -c redo_prebinding -s s --description 'write the updated file to standard output DIA... [See Man Page]'

