# reg: Darwin man parser
# Autogenerated from man pages
complete -c reg -s f
complete -c reg -l -format --description 'Specifies the format(s) to display values in'
complete -c reg -s h
complete -c reg -l -help --description 'Prints brief usage information and exits'
complete -c reg -l -verbose --description 'If used with no argument, enables verbose mod... [See Man Page]'
complete -c reg -s v
complete -c reg -l -verify-writes --description 'If used with no argument, turns on write veri... [See Man Page]'
complete -c reg -s V
complete -c reg -l -version --description 'Prints version information and exits'

