# ResMerger: Darwin man parser
# Autogenerated from man pages
complete -c ResMerger -l fileCreator --description 'Sets the HFS creator type of the output file'
complete -c ResMerger -l fileType --description 'Sets the HFS file type of the output file'
complete -c ResMerger -l '[a]ppend' --description 'Append to output file, rather than overwritin... [See Man Page]'
complete -c ResMerger -l srcIs --description 'The fork in which to look for resources in th... [See Man Page]'
complete -c ResMerger -l dstIs --description 'The fork in which to write resources in the o... [See Man Page]'
complete -c ResMerger -l skip --description 'Specifies resource type to skip during the re... [See Man Page]'
complete -c ResMerger -s o --description 'Specifies the output file'

