# resolveip: Deroffing man parser
# Autogenerated from man pages
complete -c resolveip -l help
complete -c resolveip -l info
complete -c resolveip -s '?'
complete -c resolveip -s I
complete -c resolveip -l silent
complete -c resolveip -s s
complete -c resolveip -l version
complete -c resolveip -s V

