# resolve_stack_dump: Deroffing man parser
# Autogenerated from man pages
complete -c resolve_stack_dump -l help
complete -c resolve_stack_dump -s h
complete -c resolve_stack_dump -l numeric-dump-file
complete -c resolve_stack_dump -s n
complete -c resolve_stack_dump -l symbols-file
complete -c resolve_stack_dump -s s
complete -c resolve_stack_dump -l version
complete -c resolve_stack_dump -s V

