# RezDet: Deroffing man parser
# Autogenerated from man pages
complete -c RezDet -o 'b[ig]' --description 'Reads the data for each resource into memory ... [See Man Page]'
complete -c RezDet -o useDF --description 'Reads and writes resource information from th... [See Man Page]'
complete -c RezDet -o noResolve --description 'Prevents the resolution of leaf aliases in th... [See Man Page]'
complete -c RezDet -o 'd[ump]' --description 'Generates the same information as the -s[how]... [See Man Page]'
complete -c RezDet -o 'l[ist]' --description 'Lists resource types, IDs, names, attributes,... [See Man Page]'
complete -c RezDet -o 'q[uiet]' --description 'Returns a status code instead of generating e... [See Man Page]'
complete -c RezDet -o 'r[awdump]' --description 'Generates the same information as the -d[ump]... [See Man Page]'
complete -c RezDet -o 's[how]' --description 'Writes information about individual resource ... [See Man Page]'
complete -c RezDet -s d -s r -s s
complete -c RezDet -s 1
complete -c RezDet -o 't[erse]' --description 'Suppresses all messages that do not explicitl... [See Man Page]'

