# rgb2ycbcr: Deroffing man parser
# Autogenerated from man pages
complete -c rgb2ycbcr -s c --description 'Specify a compression scheme to use when writ... [See Man Page]'
complete -c rgb2ycbcr -s h --description 'Set the horizontal sampling dimension to one ... [See Man Page]'
complete -c rgb2ycbcr -s r --description 'Write data with a specified number of rows pe... [See Man Page]'
complete -c rgb2ycbcr -s v --description options

