# rlogin: Darwin man parser
# Autogenerated from man pages
complete -c rlogin -s 4 --description 'Use IPv4 addresses only'
complete -c rlogin -s 6 --description 'Use IPv6 addresses only'
complete -c rlogin -s 8 --description 'Allow an eight-bit input data path at all tim... [See Man Page]'
complete -c rlogin -s D --description 'Set the TCP_NODELAY socket option which can i... [See Man Page]'
complete -c rlogin -s E --description 'Stop any character from being recognized as a... [See Man Page]'
complete -c rlogin -s d --description 'Turn on socket debugging (see'
complete -c rlogin -s e --description 'Allow user specification of the escape charac... [See Man Page]'
complete -c rlogin -s i --description 'Allow the caller to specify a different local... [See Man Page]'
complete -c rlogin -s l --description 'Specify a different'

