# rm: Darwin man parser
# Autogenerated from man pages
complete -c rm -s d --description 'Attempt to remove directories as well as othe... [See Man Page]'
complete -c rm -s f --description 'Attempt to remove the files without prompting... [See Man Page]'
complete -c rm -s i --description 'Request confirmation before attempting to rem... [See Man Page]'
complete -c rm -s P --description 'Overwrite regular files before deleting them'
complete -c rm -s R --description 'Attempt to remove the file hierarchy rooted i... [See Man Page]'
complete -c rm -s r --description 'Equivalent to'
complete -c rm -s v --description 'Be verbose when deleting files, showing them ... [See Man Page]'
complete -c rm -s W --description 'Attempt to undelete the named files'

