# rmic: Deroffing man parser
# Autogenerated from man pages
complete -c rmic -o bootclasspath --description 'Overrides location of bootstrap class files'
complete -c rmic -o classpath --description 'Specifies the path   rmic  uses to look up cl... [See Man Page]'
complete -c rmic -s d --description 'Specifies the root directory of the class hie... [See Man Page]'
complete -c rmic -o extdirs --description 'Overrides location of installed extensions'
complete -c rmic -s g --description 'Enables generation of all debugging informati... [See Man Page]'
complete -c rmic -o idl --description 'Causes  rmic to generate '
complete -c rmic -o always -o alwaysgenerate --description 'Forces re-generation even when existing stubs... [See Man Page]'
complete -c rmic -o factory --description 'Uses factory keyword in generated '
complete -c rmic -o iiop --description 'Causes  rmic to generate '
complete -c rmic -o nolocalstubs --description 'Does not create stubs optimized for same-proc... [See Man Page]'
complete -c rmic -o noValueMethods --description 'Must be used with the  -idl option'
complete -c rmic -o poa
complete -c rmic -s J
complete -c rmic -o keepgenerated --description 'Retains the generated '
complete -c rmic -o nowarn --description 'Turns off warnings'
complete -c rmic -o vcompat --description 'Generates stub and skeleton classes compatibl... [See Man Page]'
complete -c rmic -o verbose --description 'Causes the compiler and linker to display mes... [See Man Page]'
complete -c rmic -o 'v1.1' --description 'Creates stubs and skeletons for  JDK 1'
complete -c rmic -o idlModule --description 'Specifies IDLEntity package mapping'
complete -c rmic -o idlFile --description 'Specifies IDLEntity  file mapping'
complete -c rmic -o J-Xms48m --description 'sets the startup memory to 48 megabytes'
complete -c rmic -o 'v1.2' --description '(default) Generates stub classes for the 1'

