# rmid: Deroffing man parser
# Autogenerated from man pages
complete -c rmid -s C --description 'Specifies an option that is passed as a comma... [See Man Page]'
complete -c rmid -s J --description 'Specifies an option that is passed to the jav... [See Man Page]'
complete -c rmid -o 'J-Dsun.rmi.activation.execPolicy' --description 'Specifies the policy that  rmid employs to ch... [See Man Page]'
complete -c rmid -o log --description 'Specifies the name of the directory the activ... [See Man Page]'
complete -c rmid -o port --description 'Specifies the port  rmid \'s registry uses'
complete -c rmid -s D
complete -c rmid -o stop --description 'Stops the current invocation of rmid ,  for a... [See Man Page]'

