# rs: Darwin man parser
# Autogenerated from man pages
complete -c rs -s c --description 'Input columns are delimited by the single cha... [See Man Page]'
complete -c rs -s s --description Like
complete -c rs -s C --description 'Output columns are delimited by the single ch... [See Man Page]'
complete -c rs -s S --description Like
complete -c rs -s t --description 'Fill in the rows of the output array using th... [See Man Page]'
complete -c rs -s T --description 'Print the pure transpose of the input, ignori... [See Man Page]'
complete -c rs -s k --description 'Ignore the first'
complete -c rs -s K --description Like
complete -c rs -s g --description 'The gutter width (inter-column space), normal... [See Man Page]'
complete -c rs -s G --description 'The gutter width has'
complete -c rs -s e --description 'Consider each line of input as an array entry... [See Man Page]'
complete -c rs -s n --description 'On lines having fewer entries than the first ... [See Man Page]'
complete -c rs -s y --description 'If there are too few entries to make up the o... [See Man Page]'
complete -c rs -s h --description 'Print the shape of the input array and do not... [See Man Page]'
complete -c rs -s H --description Like
complete -c rs -s j --description 'Right adjust entries within columns'
complete -c rs -s w --description 'The width of the display, normally 80, is tak... [See Man Page]'
complete -c rs -s m --description 'Do not trim excess delimiters from the ends o... [See Man Page]'
complete -c rs -s z --description 'Adapt column widths to fit the largest entrie... [See Man Page]'

