# rsh: Darwin man parser
# Autogenerated from man pages
complete -c rsh -s 4 --description 'Use IPv4 addresses only'
complete -c rsh -s 6 --description 'Use IPv6 addresses only'
complete -c rsh -s d --description 'Turn on socket debugging (using'
complete -c rsh -s l --description 'Allow the remote'
complete -c rsh -s n --description 'Redirect input from the special device'
complete -c rsh -s t --description 'Allow a'

