# ruptime: Darwin man parser
# Autogenerated from man pages
complete -c ruptime -s a --description 'Include all users'
complete -c ruptime -s l --description 'Sort by load average'
complete -c ruptime -s r --description 'Reverse the sort order'
complete -c ruptime -s t --description 'Sort by uptime'
complete -c ruptime -s u --description 'Sort by number of users'

