# sandbox-exec: Darwin man parser
# Autogenerated from man pages
complete -c sandbox-exec -s f --description 'Read the profile from the file named'
complete -c sandbox-exec -s n --description 'Use the pre-defined profile'
complete -c sandbox-exec -s p --description 'Specify the profile to be used on the command... [See Man Page]'
complete -c sandbox-exec -s D --description 'Set the profile parameter'

