# sar: Darwin man parser
# Autogenerated from man pages
complete -c sar -s d --description 'Report disk activity'
complete -c sar -s g --description 'Report page-out activity'
complete -c sar -s p --description 'Report page-in and page fault activity'
complete -c sar -s n --description 'Report network activity with modes'
complete -c sar -s u --description 'Report CPU activity (default)'

