# sc_usage: Darwin man parser
# Autogenerated from man pages
complete -c sc_usage -s c --description 'When the'
complete -c sc_usage -s e --description 'Specifying the'
complete -c sc_usage -s l --description The
complete -c sc_usage -s s --description 'By default,'

