# scp: Darwin man parser
# Autogenerated from man pages
complete -c scp -s 1 --description Forces
complete -c scp -s 2 --description Forces
complete -c scp -s 4 --description Forces
complete -c scp -s 6 --description Forces
complete -c scp -s B --description 'Selects batch mode (prevents asking for passw... [See Man Page]'
complete -c scp -s C --description 'Compression enable'
complete -c scp -s E --description 'Preserves extended attributes, resource forks... [See Man Page]'
complete -c scp -s c --description 'Selects the cipher to use for encrypting the ... [See Man Page]'
complete -c scp -s F --description 'Specifies an alternativeper-user configuratio... [See Man Page]'
complete -c scp -s i --description 'Selects the file from which the identity (pri... [See Man Page]'
complete -c scp -s l --description 'Limits the used bandwidth, specified in Kbit/... [See Man Page]'
complete -c scp -s o --description 'Can be used to pass options to'
complete -c scp -s P --description 'Specifies the port to connect to on the remot... [See Man Page]'
complete -c scp -s p --description 'Preserves modification times, access times, a... [See Man Page]'
complete -c scp -s q --description 'Quiet mode: disables the progress meter as we... [See Man Page]'
complete -c scp -s r --description 'Recursively copy entire directories'
complete -c scp -s S --description 'Name of'
complete -c scp -s v --description 'Verbose mode'

