# screencapture: Darwin man parser
# Autogenerated from man pages
complete -c screencapture -s c --description 'Force screen capture to go to the clipboard'
complete -c screencapture -s C --description 'Capture the cursor as well as the screen'
complete -c screencapture -s i --description 'Capture screen interactively, by selection or... [See Man Page]'
complete -c screencapture -s m --description 'Only capture the main monitor, undefined if -... [See Man Page]'
complete -c screencapture -s M --description 'Open the taken picture in a new Mail message'
complete -c screencapture -s o --description 'In window capture mode, do not capture the sh... [See Man Page]'
complete -c screencapture -s P --description 'Open the taken picture in a Preview window'
complete -c screencapture -s s --description 'Only allow mouse selection mode'
complete -c screencapture -s S --description 'In window capture mode, capture the screen in... [See Man Page]'
complete -c screencapture -s t
complete -c screencapture -s T
complete -c screencapture -s w --description 'Only allow window selection mode'
complete -c screencapture -s W --description 'Start interaction in window selection mode'
complete -c screencapture -s x --description 'Do not play sounds'
complete -c screencapture -s a --description 'Do not capture attached windows'
complete -c screencapture -s r --description 'Do not add screen dpi meta data to captured f... [See Man Page]'

