# script: Darwin man parser
# Autogenerated from man pages
complete -c script -s a --description 'Append the output to'
complete -c script -s k --description 'Log keys sent to program as well as output'
complete -c script -s q --description 'Run in quiet mode, omit the start and stop st... [See Man Page]'
complete -c script -s t --description 'Specify time interval between flushing script... [See Man Page]'

