# sdp: Darwin man parser
# Autogenerated from man pages
complete -c sdp -s f --description 'Specify the output format'
complete -c sdp -s i --description 'Include the type and class definitions from t... [See Man Page]'
complete -c sdp -s o --description 'Specify where to write the output'
complete -c sdp -s V --description 'Specify the minimum system version to be comp... [See Man Page]'
complete -c sdp -l -basename --description 'Specify the'
complete -c sdp -l -hidden --description 'Output definitions even for items the scripti... [See Man Page]'

