# sed: Darwin man parser
# Autogenerated from man pages
complete -c sed -s E --description 'Interpret regular expressions as extended (mo... [See Man Page]'
complete -c sed -s a --description 'The files listed as parameters for the'
complete -c sed -s e --description 'Append the editing commands specified by the'
complete -c sed -s f --description 'Append the editing commands found in the file... [See Man Page]'
complete -c sed -s i --description 'Edit files in-place, saving backups with the ... [See Man Page]'
complete -c sed -s l --description 'Make output line buffered'
complete -c sed -s n --description 'By default, each line of input is echoed to t... [See Man Page]'

