# seq: Darwin man parser
# Autogenerated from man pages
complete -c seq -s f --description 'Use a'
complete -c seq -s s --description Use
complete -c seq -s t --description Use
complete -c seq -s w --description 'Equalize the widths of all numbers by padding... [See Man Page]'

