# serialver: Deroffing man parser
# Autogenerated from man pages
complete -c serialver -o classpath --description 'Set search path for application classes and r... [See Man Page]'
complete -c serialver -o show --description 'Displays a simple user interface'
complete -c serialver -s J --description 'Pass option to the Java virtual machine, wher... [See Man Page]'
complete -c serialver -o J-Xms48m --description 'sets the startup memory to 48 megabytes'

