# servertool: Deroffing man parser
# Autogenerated from man pages
complete -c servertool -o ORBInitialHost --description 'Specifies the host machine on which the name ... [See Man Page]'
complete -c servertool -s J --description 'Pass  option  to the Java virtual machine, wh... [See Man Page]'
complete -c servertool -o server
complete -c servertool -o classpath --description '[ '
complete -c servertool -o applicationName
complete -c servertool -o args
complete -c servertool -o vmargs --description '] Register a new server with the Object Reque... [See Man Page]'
complete -c servertool -o serverid --description '| '
complete -c servertool -o endpointType --description '] Locate the endpoints (ports) of a specific ... [See Man Page]'
complete -c servertool -o orbid --description '] Locate all the endpoints (ports) registered... [See Man Page]'

