# SetFile: Darwin man parser
# Autogenerated from man pages
complete -c SetFile -s P --description 'Acts on a symlink file instead on the file th... [See Man Page]'
complete -c SetFile -s a --description 'Sets the file attributes bits where'
complete -c SetFile -s c --description 'Specifies the file\'s creator, where'
complete -c SetFile -s d --description 'Sets the creation date, where'
complete -c SetFile -s m --description 'Sets the modification date where'
complete -c SetFile -s t --description 'Sets the file type, where '

