# sftp: Darwin man parser
# Autogenerated from man pages
complete -c sftp -s 1 --description 'Specify the use of protocol version 1'
complete -c sftp -s 2 --description 'Specify the use of protocol version 2'
complete -c sftp -s 4 --description Forces
complete -c sftp -s 6 --description Forces
complete -c sftp -s B --description 'Specify the size of the buffer that'
complete -c sftp -s b --description 'Batch mode reads a series of commands from an... [See Man Page]'
complete -c sftp -s C --description 'Enables compression (via ssh\'s'
complete -c sftp -s c --description 'Selects the cipher to use for encrypting the ... [See Man Page]'
complete -c sftp -s D --description 'Connect directly to a local sftp server(rathe... [See Man Page]'
complete -c sftp -s F --description 'Specifies an alternativeper-user configuratio... [See Man Page]'
complete -c sftp -s i --description 'Selects the file from which the identity (pri... [See Man Page]'
complete -c sftp -s o --description 'Can be used to pass options to'
complete -c sftp -s P --description 'Specifies the port to connect to on the remot... [See Man Page]'
complete -c sftp -s p --description 'Preserves modification times, access times, a... [See Man Page]'
complete -c sftp -s q --description 'Quiet mode: disables the progress meter as we... [See Man Page]'
complete -c sftp -s R --description 'Specify how many requests may be outstanding ... [See Man Page]'
complete -c sftp -s r --description 'Recursively copy entire directories when uplo... [See Man Page]'
complete -c sftp -s S --description 'Name of the'
complete -c sftp -s s --description 'Specifies the SSH2 subsystem or the path for ... [See Man Page]'
complete -c sftp -s v --description 'Raise logging level'
complete -c sftp -s a --description 'List files beginning with a dot'
complete -c sftp -s f --description 'Do not sort the listing'
complete -c sftp -s h --description 'When used with a long format option, use unit... [See Man Page]'
complete -c sftp -s l --description 'Display additional details including permissi... [See Man Page]'
complete -c sftp -s n --description 'Produce a long listing with user and group in... [See Man Page]'
complete -c sftp -s t --description 'Sort the listing by last modification time'

