# sgi2tiff: Deroffing man parser
# Autogenerated from man pages
complete -c sgi2tiff -s c --description 'Specify a compression scheme to use when writ... [See Man Page]'
complete -c sgi2tiff -s p --description 'Explicitly select the planar configuration us... [See Man Page]'
complete -c sgi2tiff -s r --description 'Write data with a specified number of rows pe... [See Man Page]'

