# sh: Deroffing man parser
# Autogenerated from man pages
complete -c sh -s c --description 'If the  -c option is present, then commands a... [See Man Page]'
complete -c sh -s i --description 'If the  -i option is present, the shell is R ... [See Man Page]'
complete -c sh -s l --description 'Make  bash act as if it had been invoked as a... [See Man Page]'
complete -c sh -s r --description 'If the  -r option is present, the shell becom... [See Man Page]'
complete -c sh -s s --description 'If the  -s option is present, or if no argume... [See Man Page]'
complete -c sh -s D --description 'A list of all double-quoted strings preceded ... [See Man Page]'
complete -c sh -l debugger --description 'Arrange for the debugger profile to be execut... [See Man Page]'
complete -c sh -l dump-po-strings --description 'Equivalent to -D, but the output is in the GN... [See Man Page]'
complete -c sh -l dump-strings --description 'Equivalent to -D'
complete -c sh -l help --description 'Display a usage message on standard output an... [See Man Page]'
complete -c sh -l rcfile
complete -c sh -l login --description 'Equivalent to -l'
complete -c sh -l noediting --description 'Do not use the GNU  readline library to read ... [See Man Page]'
complete -c sh -l noprofile --description 'Do not read either the system-wide startup fi... [See Man Page]'
complete -c sh -l norc --description 'Do not read and execute the personal initiali... [See Man Page]'
complete -c sh -l posix --description 'Change the behavior of bash where the default... [See Man Page]'
complete -c sh -l restricted --description 'The shell becomes restricted (see '
complete -c sh -l verbose --description 'Equivalent to  -v'
complete -c sh -s o --description 'set builtin below)'
complete -c sh -l init-file
complete -c sh -l version --description 'Show version information for this instance of... [See Man Page]'
complete -c sh -s a --description 'option to specify an array'
complete -c sh -s f --description 'option has been set, bash scans each word for... [See Man Page]'
complete -c sh -s F --description 'option to declare or typeset will list the fu... [See Man Page]'
complete -c sh -s b --description 'True if file exists and is a block special fi... [See Man Page]'
complete -c sh -s d --description 'True if file exists and is a directory'
complete -c sh -s e --description 'True if file exists'
complete -c sh -s g --description 'True if file exists and is set-group-id'
complete -c sh -s h --description 'True if file exists and is a symbolic link'
complete -c sh -s k --description 'True if file exists and its ``sticky\'\' bit is... [See Man Page]'
complete -c sh -s p --description 'True if file exists and is a named pipe (FIFO... [See Man Page]'
complete -c sh -s t --description 'True if file descriptor fd is open and refers... [See Man Page]'
complete -c sh -s u --description 'True if file exists and its set-user-id bit i... [See Man Page]'
complete -c sh -s w --description 'True if file exists and is writable'
complete -c sh -s x --description 'True if file exists and is executable'
complete -c sh -s O --description 'True if file exists and is owned by the effec... [See Man Page]'
complete -c sh -s G --description 'True if file exists and is owned by the effec... [See Man Page]'
complete -c sh -s L --description 'True if file exists and is a symbolic link'
complete -c sh -s S --description 'True if file exists and is a socket'
complete -c sh -s N --description 'True if file exists and has been modified sin... [See Man Page]'
complete -c sh -s z --description 'True if the length of string is zero'
complete -c sh -s n
complete -c sh -o eq
complete -c sh -o ne
complete -c sh -o lt
complete -c sh -o le
complete -c sh -o gt --description or
complete -c sh -o ge --description 'These arithmetic binary operators return true... [See Man Page]'
complete -c sh -s m --description 'Use keymap as the keymap to be affected by th... [See Man Page]'
complete -c sh -s P --description 'List current readline function names and bind... [See Man Page]'
complete -c sh -s v --description 'Display readline variable names and values in... [See Man Page]'
complete -c sh -s V --description 'List current readline variable names and valu... [See Man Page]'
complete -c sh -s q --description 'Query about which keys invoke the named funct... [See Man Page]'
complete -c sh -s A --description 'The action may be one of the following to gen... [See Man Page]'
complete -c sh -s W --description 'The wordlist is split using the characters in... [See Man Page]'
complete -c sh -s C --description 'command is executed in a subshell environment... [See Man Page]'
complete -c sh -s X --description 'filterpat is a pattern as used for filename e... [See Man Page]'
complete -c sh -s E --description 'option disables the interpretation of these e... [See Man Page]'
complete -c sh -o 'u.' --description 'readonly [-apf] [name[=word] '
complete -c sh -s B
complete -c sh -s T
complete -c sh -s H

