# sha: Type1
# Autogenerated from man pages
complete -c sha -s c --description 'print out the digest in two digit groups sepa... [See Man Page]'
complete -c sha -s d --description 'print out \\s-1BIO\\s0 debugging information'
complete -c sha -o hex --description 'digest is to be output as a hex dump'
complete -c sha -o binary --description 'output the digest or signature in binary form... [See Man Page]'
complete -c sha -o out --description 'filename to output to, or standard output by ... [See Man Page]'
complete -c sha -o sign --description 'digitally sign the digest using the private k... [See Man Page]'
complete -c sha -o passin --description 'the private key password source'
complete -c sha -o verify --description 'verify the signature using the the public key... [See Man Page]'
complete -c sha -o prverify --description 'verify the signature using the  the private k... [See Man Page]'
complete -c sha -o signature --description 'the actual signature to verify'
complete -c sha -o hmac --description 'create a hashed \\s-1MAC\\s0 using \\*(L"key\\*(R... [See Man Page]'
complete -c sha -o rand --description 'a file or files containing random data used t... [See Man Page]'

