# size: Deroffing man parser
# Autogenerated from man pages
complete -c size -s m --description 'Print the sizes of the Mach-O segments and se... [See Man Page]'
complete -c size -s l --description 'When used with the  -m option, also print the... [See Man Page]'
complete -c size -s x --description 'When used with the  -m option, print the valu... [See Man Page]'
complete -c size -o arch --description 'Specifies the architecture, arch_type, of the... [See Man Page]'

