# smbutil: Darwin man parser
# Autogenerated from man pages
complete -c smbutil -s h --description 'Print a short help message'
complete -c smbutil -s v --description 'Verbose output'
complete -c smbutil -s A --description 'authorize only'
complete -c smbutil -s N --description 'don\'t prompt for a password'
complete -c smbutil -s G --description 'allow guest access'
complete -c smbutil -s g --description 'authorize with guest only'
complete -c smbutil -s a --description 'authorize with anonymous only'
complete -c smbutil -s f --description 'don\'t share session'

