# snmptranslate: Deroffing man parser
# Autogenerated from man pages
complete -c snmptranslate -o 'D[TOKEN[' --description 'Turn on debugging output for the given R "TOK... [See Man Page]'
complete -c snmptranslate -s h --description 'Display a brief usage message and then exit'
complete -c snmptranslate -s m --description 'Specifies a colon separated list of MIB modul... [See Man Page]'
complete -c snmptranslate -s M --description 'Specifies a colon separated list of directori... [See Man Page]'
complete -c snmptranslate -s T --description 'Provides control over the translation of the ... [See Man Page]'
complete -c snmptranslate -o Td --description 'Print full details of the specified OID'
complete -c snmptranslate -o Tp --description 'Print a graphical tree, rooted at the specifi... [See Man Page]'
complete -c snmptranslate -o Ta --description 'Dump the loaded MIB in a trivial form'
complete -c snmptranslate -o Tl --description 'Dump a labeled form of all objects'
complete -c snmptranslate -o To --description 'Dump a numeric form of all objects'
complete -c snmptranslate -o Ts --description 'Dump a symbolic form of all objects'
complete -c snmptranslate -o Tt --description 'Dump a tree form of the loaded MIBs (mostly u... [See Man Page]'
complete -c snmptranslate -o Tz --description 'Dump a numeric and labeled form of all object... [See Man Page]'
complete -c snmptranslate -s V --description 'Display version information for the applicati... [See Man Page]'
complete -c snmptranslate -s w --description 'Specifies the width of'

