# snmpbulkget: Deroffing man parser
# Autogenerated from man pages
complete -c snmpbulkget -o Cn --description 'Set the  non-repeaters field in the GETBULK P... [See Man Page]'
complete -c snmpbulkget -o Cr --description 'Set the max-repetitions field in the GETBULK ... [See Man Page]'

