# snmptable: Deroffing man parser
# Autogenerated from man pages
complete -c snmptable -o Cb --description 'Display only a brief heading'
complete -c snmptable -o CB --description 'Do not use GETBULK requests to retrieve data,... [See Man Page]'
complete -c snmptable -o Cc --description 'Print table in columns of  CHARS characters w... [See Man Page]'
complete -c snmptable -o Cf --description 'The string  STRING is used to separate table ... [See Man Page]'
complete -c snmptable -o Ch --description 'Display  only the column headings'
complete -c snmptable -o CH --description 'Do not display the column headings'
complete -c snmptable -o Ci --description 'This option prepends the index of the entry t... [See Man Page]'
complete -c snmptable -o Cl --description 'Left justify the data in each column'
complete -c snmptable -o Cr --description 'For GETBULK requests,   REPEATERS specifies t... [See Man Page]'
complete -c snmptable -o Cw --description 'Specifies the width of the lines when the tab... [See Man Page]'

