# snmpbulkwalk: Deroffing man parser
# Autogenerated from man pages
complete -c snmpbulkwalk -o Cc --description 'Do not check whether the returned OIDs are in... [See Man Page]'
complete -c snmpbulkwalk -o Ci --description 'Include the given OID in the search range'
complete -c snmpbulkwalk -o Cn --description 'Set the  non-repeaters field in the GETBULK P... [See Man Page]'
complete -c snmpbulkwalk -o Cp --description 'Upon completion of the walk, print the number... [See Man Page]'
complete -c snmpbulkwalk -o Cr --description 'Set the max-repetitions field in the GETBULK ... [See Man Page]'

