# snmpconf: Deroffing man parser
# Autogenerated from man pages
complete -c snmpconf -s g --description 'switch, which walks a user through a specific... [See Man Page]'
complete -c snmpconf -s f --description 'Force overwriting existing files in the curre... [See Man Page]'
complete -c snmpconf -s i --description 'When finished, install the files into the loc... [See Man Page]'
complete -c snmpconf -s p --description 'When finished, install the files into the use... [See Man Page]'
complete -c snmpconf -s I --description 'When finished, install the files into the dir... [See Man Page]'
complete -c snmpconf -s a --description 'Don\'t ask any questions'
complete -c snmpconf -s r --description 'Read in either all or none of the found confi... [See Man Page]'
complete -c snmpconf -s R --description 'Read in a specific list of configuration file... [See Man Page]'
complete -c snmpconf -s G --description 'List all the known groups'
complete -c snmpconf -s c --description 'snmpconf uses a directory of configuration in... [See Man Page]'
complete -c snmpconf -s q --description 'Run slightly more quietly'
complete -c snmpconf -s d --description 'Turn on  lots of debugging output'
complete -c snmpconf -s D --description 'Add  even more debugging output in the form o... [See Man Page]'

