# snmpdelta: Deroffing man parser
# Autogenerated from man pages
complete -c snmpdelta -o Cf --description 'Don\'t fix errors and retry the request'
complete -c snmpdelta -o Ct --description 'Flag will determine time interval from the mo... [See Man Page]'
complete -c snmpdelta -o Cs --description 'Flag will display a timestamp'
complete -c snmpdelta -o CS --description 'Generates a "sum count" in addition to the in... [See Man Page]'
complete -c snmpdelta -o Cm --description 'Prints the max value ever attained'
complete -c snmpdelta -o CF --description 'Tells  snmpdelta to read it\'s configuration f... [See Man Page]'
complete -c snmpdelta -o Cl --description 'Tells  snmpdelta to write it\'s configuration ... [See Man Page]'
complete -c snmpdelta -o Cp --description 'Specifies the number of seconds between polli... [See Man Page]'
complete -c snmpdelta -o CP --description 'Specifies the reporting period in number of p... [See Man Page]'
complete -c snmpdelta -o Ck --description 'When the polling period (-Cp) is an increment... [See Man Page]'
complete -c snmpdelta -o CT --description 'Makes   snmpdelta print its output in tabular... [See Man Page]'
complete -c snmpdelta -o Cv --description 'Specifies the maximum number of oids allowed ... [See Man Page]'

