# snmpnetstat: Deroffing man parser
# Autogenerated from man pages
complete -c snmpnetstat -o Ca --description 'With the default display, show the state of a... [See Man Page]'
complete -c snmpnetstat -o Ci --description 'Show the state of all of the network interfac... [See Man Page]'
complete -c snmpnetstat -o Co --description 'Show an abbreviated interface status, giving ... [See Man Page]'
complete -c snmpnetstat -o CI --description 'Show information only about this interface; u... [See Man Page]'
complete -c snmpnetstat -o Cn --description 'Show network addresses as numbers (normally  ... [See Man Page]'
complete -c snmpnetstat -o Cp --description 'Show statistics about  protocol, which is eit... [See Man Page]'
complete -c snmpnetstat -o Cs --description 'Show per-protocol statistics'
complete -c snmpnetstat -o Cr --description 'option, show routing statistics instead'
complete -c snmpnetstat -o CR --description 'For GETBULK requests, repeaters specifies the... [See Man Page]'

