# snmpwalk: Deroffing man parser
# Autogenerated from man pages
complete -c snmpwalk -o Cc --description 'Do not check whether the returned OIDs are in... [See Man Page]'
complete -c snmpwalk -o CE --description 'End the walk at the specified OID, rather tha... [See Man Page]'
complete -c snmpwalk -o Ci --description 'Include the given OID in the search range'
complete -c snmpwalk -o CI --description 'In fact, the given OID will be retrieved auto... [See Man Page]'
complete -c snmpwalk -o Cp --description 'Upon completion of the walk, print the number... [See Man Page]'
complete -c snmpwalk -o Ct --description 'Upon completion of the walk, print the total ... [See Man Page]'

