# snmpusm: Deroffing man parser
# Autogenerated from man pages
complete -c snmpusm -o CE --description 'Set usmUserEngineID to be used as part of the... [See Man Page]'
complete -c snmpusm -o Cp --description 'Set the usmUserPublic value of the (new) user... [See Man Page]'
complete -c snmpusm -o Ca --description 'Change the authentication key'
complete -c snmpusm -o Cx --description 'Change the privacy key'
complete -c snmpusm -o Ck --description 'Allows to use localized key (must start with ... [See Man Page]'

