# split: Darwin man parser
# Autogenerated from man pages
complete -c split -s a --description Use
complete -c split -s b --description 'Create smaller files'
complete -c split -s l --description 'Create smaller files'
complete -c split -s p --description 'The file is split whenever an input line matc... [See Man Page]'

