# ssh-add: Darwin man parser
# Autogenerated from man pages
complete -c ssh-add -s c --description 'Indicates that added identities should be sub... [See Man Page]'
complete -c ssh-add -s D --description 'Deletes all identities from the agent'
complete -c ssh-add -s d --description 'Instead of adding identities, removes identit... [See Man Page]'
complete -c ssh-add -s e --description 'Remove keys provided by the PKCS#11 shared li... [See Man Page]'
complete -c ssh-add -s L --description 'Lists public key parameters of all identities... [See Man Page]'
complete -c ssh-add -s l --description 'Lists fingerprints of all identities currentl... [See Man Page]'
complete -c ssh-add -s s --description 'Add keys provided by the PKCS#11 shared libra... [See Man Page]'
complete -c ssh-add -s t --description 'Set a maximum lifetime when adding identities... [See Man Page]'
complete -c ssh-add -s X --description 'Unlock the agent'
complete -c ssh-add -s x --description 'Lock the agent with a password'
complete -c ssh-add -s K --description 'When adding identities, each passphrase will ... [See Man Page]'
complete -c ssh-add -s k --description 'Add identities to the agent using any passphr... [See Man Page]'

