# ssh-keyscan: Darwin man parser
# Autogenerated from man pages
complete -c ssh-keyscan -s 4 --description Forces
complete -c ssh-keyscan -s 6 --description Forces
complete -c ssh-keyscan -s f --description 'Read hosts or'
complete -c ssh-keyscan -s H --description 'Hash all hostnames and addresses in the outpu... [See Man Page]'
complete -c ssh-keyscan -s p --description 'Port to connect to on the remote host'
complete -c ssh-keyscan -s T --description 'Set the timeout for connection attempts'
complete -c ssh-keyscan -s t --description 'Specifies the type of the key to fetch from t... [See Man Page]'
complete -c ssh-keyscan -s v --description 'Verbose mode'

