# ssh-agent: Darwin man parser
# Autogenerated from man pages
complete -c ssh-agent -s a --description 'Bind the agent to the'
complete -c ssh-agent -s c --description 'Generate C-shell commands on'
complete -c ssh-agent -s d --description 'Debug mode'
complete -c ssh-agent -s k --description 'Kill the current agent (given by the'
complete -c ssh-agent -s s --description 'Generate Bourne shell commands on'
complete -c ssh-agent -s t --description 'Set a default value for the maximum lifetime ... [See Man Page]'

