# ssh: Darwin man parser
# Autogenerated from man pages
complete -c ssh -s 1 --description Forces
complete -c ssh -s 2 --description Forces
complete -c ssh -s 4 --description Forces
complete -c ssh -s 6 --description Forces
complete -c ssh -s A --description 'Enables forwarding of the authentication agen... [See Man Page]'
complete -c ssh -s a --description 'Disables forwarding of the authentication age... [See Man Page]'
complete -c ssh -s b --description Use
complete -c ssh -s C --description 'Requests compression of all data (including s... [See Man Page]'
complete -c ssh -s c --description 'Selects the cipher specification for encrypti... [See Man Page]'
complete -c ssh -s D
complete -c ssh -s e --description 'Sets the escape character for sessions with a... [See Man Page]'
complete -c ssh -s F --description 'Specifies an alternative per-user configurati... [See Man Page]'
complete -c ssh -s f --description Requests
complete -c ssh -s g --description 'Allows remote hosts to connect to local forwa... [See Man Page]'
complete -c ssh -s I --description 'Specify the PKCS#11 shared library'
complete -c ssh -s i --description 'Selects a file from which the identity (priva... [See Man Page]'
complete -c ssh -s K --description 'Enables GSSAPI-based authentication and forwa... [See Man Page]'
complete -c ssh -s k --description 'Disables forwarding (delegation) of GSSAPI cr... [See Man Page]'
complete -c ssh -s L
complete -c ssh -s l --description 'Specifies the user to log in as on the remote... [See Man Page]'
complete -c ssh -s M --description 'Places the'
complete -c ssh -s m --description 'Additionally, for protocol version 2 a comma-... [See Man Page]'
complete -c ssh -s N --description 'Do not execute a remote command'
complete -c ssh -s n --description 'Redirects stdin from'
complete -c ssh -s O --description 'Control an active connection multiplexing mas... [See Man Page]'
complete -c ssh -s o --description 'Can be used to give options in the format use... [See Man Page]'
complete -c ssh -s p --description 'Port to connect to on the remote host'
complete -c ssh -s q --description 'Quiet mode'
complete -c ssh -s R
complete -c ssh -s S --description 'Specifies the location of a control socket fo... [See Man Page]'
complete -c ssh -s s --description 'May be used to request invocation of a subsys... [See Man Page]'
complete -c ssh -s T --description 'Disable pseudo-tty allocation'
complete -c ssh -s t --description 'Force pseudo-tty allocation'
complete -c ssh -s V --description 'Display the version number and exit'
complete -c ssh -s v --description 'Verbose mode'
complete -c ssh -s W --description 'Requests that standard input and output on th... [See Man Page]'
complete -c ssh -s w
complete -c ssh -s X --description 'Enables X11 forwarding'
complete -c ssh -s x --description 'Disables X11 forwarding'
complete -c ssh -s Y --description 'Enables trusted X11 forwarding'
complete -c ssh -s y --description 'Send log information using the'

