# stackshot: Darwin man parser
# Autogenerated from man pages
complete -c stackshot -s D --description 'Turn on debugging'
complete -c stackshot -s i --description 'Do an immediate snapshot, and exit'
complete -c stackshot -s f --description 'Output the log information to the specified p... [See Man Page]'
complete -c stackshot -s n --description 'Limit the number of snapshots taken; the defa... [See Man Page]'
complete -c stackshot -s p --description 'Log the stack information for the specified p... [See Man Page]'
complete -c stackshot -s B --description 'Specify the size of the trace buffer; the def... [See Man Page]'
complete -c stackshot -s t --description 'Attempt to invoke'
complete -c stackshot -s u --description 'Attempt symbolication'

