# stat: Darwin man parser
# Autogenerated from man pages
complete -c stat -s F --description 'As in'
complete -c stat -s f --description 'Display information using the specified forma... [See Man Page]'
complete -c stat -s L --description Use
complete -c stat -s l --description 'Display output in'
complete -c stat -s n --description 'Do not force a newline to appear at the end o... [See Man Page]'
complete -c stat -s q --description 'Suppress failure messages if calls to'
complete -c stat -s r --description 'Display raw information'
complete -c stat -s s --description 'Display information in'
complete -c stat -s t --description 'Display timestamps using the specified format... [See Man Page]'
complete -c stat -s x --description 'Display information in a more verbose way as ... [See Man Page]'

