# states: Deroffing man parser
# Autogenerated from man pages
complete -c states -s D -l define --description 'Define variable \\f2var to have string value \\... [See Man Page]'
complete -c states -s f -l file --description 'Read state definitions from file \\f2file'
complete -c states -s h -l help --description 'Print short help message and exit'
complete -c states -s o -l output --description 'Save output to file \\f2file instead of printi... [See Man Page]'
complete -c states -s p -l path --description 'Set the load path to \\f2path'
complete -c states -s s -l state --description 'Start execution from state \\f3state'
complete -c states -s v -l verbose --description 'Increase the program verbosity'
complete -c states -s V -l version --description 'Print \\f3states version and exit'
complete -c states -s W -l warning --description 'Set the warning level to \\f2level'
complete -c states -s 1 --description 'string str1 is less than str2'

