# stringdups: Darwin man parser
# Autogenerated from man pages
complete -c stringdups -l minimumCount --description 'Only print information for object description... [See Man Page]'
complete -c stringdups -l stringsOnly --description 'Only print information for objects that have ... [See Man Page]'
complete -c stringdups -l nostacks --description 'Do not print stack backtraces or call trees e... [See Man Page]'
complete -c stringdups -l callTrees --description 'If stack bactraces are available, then by def... [See Man Page]'
complete -c stringdups -l invertCallTrees --description 'Same as'

