# strings: Deroffing man parser
# Autogenerated from man pages
complete -c strings -s a --description 'This option causes  strings to look for strin... [See Man Page]'
complete -c strings -s o --description 'Preceded each string by its offset in the fil... [See Man Page]'
complete -c strings -s t --description 'Write each string preceded by its byte offset... [See Man Page]'
complete -c strings -s n --description 'Specify the minimum string length, where the ... [See Man Page]'
complete -c strings -o arch --description 'Specifies the architecture, arch_type, of the... [See Man Page]'

