# stty: Darwin man parser
# Autogenerated from man pages
complete -c stty -s a --description 'Display all the current settings for the term... [See Man Page]'
complete -c stty -s e --description 'Display all the current settings for the term... [See Man Page]'
complete -c stty -s f --description 'Open and use the terminal named by'
complete -c stty -s g --description 'Display all the current settings for the term... [See Man Page]'
complete -c stty -l evenp --description 'Same as'
complete -c stty -l oddp --description 'Same as'
complete -c stty -l parity --description Disable

