# su: Darwin man parser
# Autogenerated from man pages
complete -c su -s f --description 'If the invoked shell is'
complete -c su -s l --description 'Simulate a full login'
complete -c su -l Fl --description '(no letter) The same as'
complete -c su -s m --description 'Leave the environment unmodified'

