# sw_vers: Darwin man parser
# Autogenerated from man pages
complete -c sw_vers -l productName --description 'Print just the value of the ProductName prope... [See Man Page]'
complete -c sw_vers -l productVersion --description 'Print just the value of the ProductVersion pr... [See Man Page]'
complete -c sw_vers -l buildVersion --description 'Print just the value of the BuildVersion prop... [See Man Page]'

