# sysdiagnose: Darwin man parser
# Autogenerated from man pages
complete -c sysdiagnose -s h --description 'Print full usage'
complete -c sysdiagnose -s f --description 'Specify the directory where the results will ... [See Man Page]'
complete -c sysdiagnose -s t --description 'Enable "Thorough Mode"'

