# tab2space: Deroffing man parser
# Autogenerated from man pages
complete -c tab2space -o help -s h --description 'display this help message'
complete -c tab2space -o dos -o crlf --description 'set line ends to CRLF (PC-DOS/Windows - defau... [See Man Page]'
complete -c tab2space -o mac -o cr --description 'set line ends to CR (classic Mac OS)'
complete -c tab2space -o unix -o lf --description 'set line ends to LF (Unix / Mac OS X)'
complete -c tab2space -o tabs --description 'preserve tabs, e'
complete -c tab2space -o 't<n>' --description 'set tabs to <n> (default is 4) spaces SEE ALS... [See Man Page]'

