# tabs: Darwin man parser
# Autogenerated from man pages
complete -c tabs -s n --description 'Set a tab stop every'
complete -c tabs -s a --description 'Assembler format (columns 1, 10, 16, 36, 72)'
complete -c tabs -l a2 --description 'Assembler format (columns 1, 10, 16, 40, 72)'
complete -c tabs -s c
complete -c tabs -l c2
complete -c tabs -l c3
complete -c tabs -s f
complete -c tabs -s p
complete -c tabs -s s
complete -c tabs -s u --description 'Assembler format (columns 1, 12, 20, 44)'
complete -c tabs -s T --description 'Output escape sequence for the terminal type'

