# tail: Darwin man parser
# Autogenerated from man pages
complete -c tail -s b --description 'The location is'
complete -c tail -s c --description 'The location is'
complete -c tail -s f --description The
complete -c tail -s F --description The
complete -c tail -s n --description 'The location is'
complete -c tail -s q --description 'Suppresses printing of headers when multiple ... [See Man Page]'
complete -c tail -s r --description The

