# tbl: Deroffing man parser
# Autogenerated from man pages
complete -c tbl -s C --description 'Enable compatibility mode to recognize  '
complete -c tbl -s t --description 'option of groff'
complete -c tbl -s v --description 'Print the version number'

