# tcbmttest: Deroffing man parser
# Autogenerated from man pages
complete -c tcbmttest -o tl
complete -c tcbmttest -o td
complete -c tcbmttest -o tb
complete -c tcbmttest -o tt
complete -c tcbmttest -o tx
complete -c tcbmttest -o xm
complete -c tcbmttest -o df
complete -c tcbmttest -o nl
complete -c tcbmttest -o nb
complete -c tcbmttest -o rnd
complete -c tcbmttest -o wb
complete -c tcbmttest -o nc
complete -c tcbmttest -o rr --description 'This command returns 0 on success, another on... [See Man Page]'

