# tcbtest: Deroffing man parser
# Autogenerated from man pages
complete -c tcbtest -o mt
complete -c tcbtest -o cd
complete -c tcbtest -o ci
complete -c tcbtest -o cj
complete -c tcbtest -o tl
complete -c tcbtest -o td
complete -c tcbtest -o tb
complete -c tcbtest -o tt
complete -c tcbtest -o tx
complete -c tcbtest -o lc
complete -c tcbtest -o nc
complete -c tcbtest -o xm
complete -c tcbtest -o df
complete -c tcbtest -o ls
complete -c tcbtest -o ca
complete -c tcbtest -o nl
complete -c tcbtest -o nb
complete -c tcbtest -o rnd
complete -c tcbtest -o wb
complete -c tcbtest -o pn
complete -c tcbtest -o dai
complete -c tcbtest -o dad
complete -c tcbtest -o rl
complete -c tcbtest -o ru --description 'This command returns 0 on success, another on... [See Man Page]'

