# tcfmgr: Deroffing man parser
# Autogenerated from man pages
complete -c tcfmgr -o nl
complete -c tcfmgr -o nb
complete -c tcfmgr -o sx
complete -c tcfmgr -o dk
complete -c tcfmgr -o dc
complete -c tcfmgr -o dai
complete -c tcfmgr -o dad
complete -c tcfmgr -o px
complete -c tcfmgr -o pz
complete -c tcfmgr -s m
complete -c tcfmgr -o pv
complete -c tcfmgr -o rb
complete -c tcfmgr -o ri
complete -c tcfmgr -o sc --description 'This command returns 0 on success, another on... [See Man Page]'

