# tcfmttest: Deroffing man parser
# Autogenerated from man pages
complete -c tcfmttest -o nl
complete -c tcfmttest -o nb
complete -c tcfmttest -o rnd
complete -c tcfmttest -o wb
complete -c tcfmttest -o nc
complete -c tcfmttest -o rr --description 'This command returns 0 on success, another on... [See Man Page]'

