# tcftest: Deroffing man parser
# Autogenerated from man pages
complete -c tcftest -o mt
complete -c tcftest -o nl
complete -c tcftest -o nb
complete -c tcftest -o rnd
complete -c tcftest -o wb
complete -c tcftest -o pn
complete -c tcftest -o dai
complete -c tcftest -o dad
complete -c tcftest -o rl --description 'This command returns 0 on success, another on... [See Man Page]'

