# tchmgr: Deroffing man parser
# Autogenerated from man pages
complete -c tchmgr -o tl
complete -c tchmgr -o td
complete -c tchmgr -o tb
complete -c tchmgr -o tt
complete -c tchmgr -o tx
complete -c tchmgr -o nl
complete -c tchmgr -o nb
complete -c tchmgr -o sx
complete -c tchmgr -o dk
complete -c tchmgr -o dc
complete -c tchmgr -o dai
complete -c tchmgr -o dad
complete -c tchmgr -o px
complete -c tchmgr -o pz
complete -c tchmgr -s m
complete -c tchmgr -o pv
complete -c tchmgr -o fm
complete -c tchmgr -o tz
complete -c tchmgr -o df
complete -c tchmgr -o sc --description 'This command returns 0 on success, another on... [See Man Page]'

