# tchmttest: Deroffing man parser
# Autogenerated from man pages
complete -c tchmttest -o tl
complete -c tchmttest -o td
complete -c tchmttest -o tb
complete -c tchmttest -o tt
complete -c tchmttest -o tx
complete -c tchmttest -o rc
complete -c tchmttest -o xm
complete -c tchmttest -o df
complete -c tchmttest -o nl
complete -c tchmttest -o nb
complete -c tchmttest -o as
complete -c tchmttest -o rnd
complete -c tchmttest -o wb
complete -c tchmttest -o nc
complete -c tchmttest -o rr --description 'This command returns 0 on success, another on... [See Man Page]'

