# tctmttest: Deroffing man parser
# Autogenerated from man pages
complete -c tctmttest -o tl
complete -c tctmttest -o td
complete -c tctmttest -o tb
complete -c tctmttest -o tt
complete -c tctmttest -o tx
complete -c tctmttest -o rc
complete -c tctmttest -o lc
complete -c tctmttest -o nc
complete -c tctmttest -o xm
complete -c tctmttest -o df
complete -c tctmttest -o ip
complete -c tctmttest -o is
complete -c tctmttest -o in
complete -c tctmttest -o it
complete -c tctmttest -o if
complete -c tctmttest -o ix
complete -c tctmttest -o nl
complete -c tctmttest -o nb
complete -c tctmttest -o rnd
complete -c tctmttest -o rr --description 'This command returns 0 on success, another on... [See Man Page]'

