# tcttest: Deroffing man parser
# Autogenerated from man pages
complete -c tcttest -o mt
complete -c tcttest -o tl
complete -c tcttest -o td
complete -c tcttest -o tb
complete -c tcttest -o tt
complete -c tcttest -o tx
complete -c tcttest -o rc
complete -c tcttest -o lc
complete -c tcttest -o nc
complete -c tcttest -o xm
complete -c tcttest -o df
complete -c tcttest -o ip
complete -c tcttest -o is
complete -c tcttest -o in
complete -c tcttest -o it
complete -c tcttest -o if
complete -c tcttest -o ix
complete -c tcttest -o nl
complete -c tcttest -o nb
complete -c tcttest -o rnd
complete -c tcttest -o pn
complete -c tcttest -o dai
complete -c tcttest -o dad
complete -c tcttest -o rl
complete -c tcttest -o ru --description 'This command returns 0 on success, another on... [See Man Page]'

