# tcumttest: Deroffing man parser
# Autogenerated from man pages
complete -c tcumttest -o rnd
complete -c tcumttest -o nc
complete -c tcumttest -o rr --description 'This command returns 0 on success, another on... [See Man Page]'

