# tcutest: Deroffing man parser
# Autogenerated from man pages
complete -c tcutest -o rd
complete -c tcutest -o tr
complete -c tcutest -o rnd
complete -c tcutest -o dk
complete -c tcutest -o dc
complete -c tcutest -o dai
complete -c tcutest -o dad
complete -c tcutest -o dpr --description 'This command returns 0 on success, another on... [See Man Page]'

