# tee: Darwin man parser
# Autogenerated from man pages
complete -c tee -s a --description 'Append the output to the files rather thanove... [See Man Page]'
complete -c tee -s i --description 'Ignore the'

