# telnet: Darwin man parser
# Autogenerated from man pages
complete -c telnet -s 4 --description Forces
complete -c telnet -s 6 --description Forces
complete -c telnet -s 8 --description 'Specifies an 8-bit data path'
complete -c telnet -s E --description 'Stops any character from being recognized as ... [See Man Page]'
complete -c telnet -s F --description 'If Kerberos V5 authentication is being used, ... [See Man Page]'
complete -c telnet -s K --description 'Specifies no automatic login to the remote sy... [See Man Page]'
complete -c telnet -s L --description 'Specifies an 8-bit data path on output'
complete -c telnet -s N --description 'Prevents IP address to name lookup when desti... [See Man Page]'
complete -c telnet -s S --description 'Sets the IP type-of-service (TOS) option for ... [See Man Page]'
complete -c telnet -s X --description 'Disables the'
complete -c telnet -s a --description 'Attempt automatic login'
complete -c telnet -s c --description 'Disables the reading of the user\'s'
complete -c telnet -s d --description 'Sets the initial value of the'
complete -c telnet -s e --description 'Sets the initial'
complete -c telnet -s f --description 'If Kerberos V5 authentication is being used, ... [See Man Page]'
complete -c telnet -s k --description 'If Kerberos authentication is being used, the... [See Man Page]'
complete -c telnet -s l --description 'When connecting to the remote system, if the ... [See Man Page]'
complete -c telnet -s n --description Opens
complete -c telnet -s r --description 'Specifies a user interface similar to'
complete -c telnet -s s --description 'Set the source IP address for the'
complete -c telnet -s u --description Forces
complete -c telnet -s x --description 'Turns on encryption of the data stream if pos... [See Man Page]'
complete -c telnet -s y --description 'Suppresses encryption of the data stream'

