# texindex: Deroffing man parser
# Autogenerated from man pages
complete -c texindex -s h -l help --description 'display this help and exit'
complete -c texindex -s k -l keep --description 'keep temporary files around after processing'
complete -c texindex -l no-keep --description 'do not keep temporary files around after proc... [See Man Page]'
complete -c texindex -s o -l output --description 'send output to FILE'
complete -c texindex -l version --description 'display version information and exit REPORTIN... [See Man Page]'

