# tfmtodit: Deroffing man parser
# Autogenerated from man pages
complete -c tfmtodit -s v --description 'Print the version number'
complete -c tfmtodit -s s --description 'The font is special'
complete -c tfmtodit -s k --description 'The skewchar of this font is at position R n ... [See Man Page]'
complete -c tfmtodit -s g --description option

