# thumbnail: Deroffing man parser
# Autogenerated from man pages
complete -c thumbnail -s w --description 'Specify the width of thumbnail images in pixe... [See Man Page]'
complete -c thumbnail -s h --description 'Specify the height of thumbnail images in pix... [See Man Page]'
complete -c thumbnail -s c --description 'Specify a contrast curve to apply in generati... [See Man Page]'

