# tic: Deroffing man parser
# Autogenerated from man pages
complete -c tic -s 1 --description 'restricts the output to a single column'
complete -c tic -s a --description 'tells tic to retain commented-out capabilitie... [See Man Page]'
complete -c tic -s C --description 'Force source translation to termcap format'
complete -c tic -s c --description 'tells tic to only check file for errors, incl... [See Man Page]'
complete -c tic -s e --description 'Limit writes and translations to the followin... [See Man Page]'
complete -c tic -s f --description 'Display complex terminfo strings which contai... [See Man Page]'
complete -c tic -s G --description 'Display constant literals in decimal form rat... [See Man Page]'
complete -c tic -s g --description 'Display constant character literals in quoted... [See Man Page]'
complete -c tic -s I --description 'Force source translation to terminfo format'
complete -c tic -s L --description 'Force source translation to terminfo format u... [See Man Page]'
complete -c tic -s N --description 'Disable smart defaults'
complete -c tic -o odir --description 'Write compiled entries to given directory'
complete -c tic -o Rsubset --description 'Restrict output to a given subset'
complete -c tic -s r --description 'Force entry resolution (so there are no remai... [See Man Page]'
complete -c tic -s s --description 'Summarize the compile by showing the director... [See Man Page]'
complete -c tic -s T --description 'eliminates size-restrictions on the generated... [See Man Page]'
complete -c tic -s t --description 'tells tic to discard commented-out capabiliti... [See Man Page]'
complete -c tic -s V --description 'reports the version of ncurses which was used... [See Man Page]'
complete -c tic -o vn --description 'specifies that (verbose) output be written to... [See Man Page]'
complete -c tic -o wn --description 'specifies the width of the output'
complete -c tic -s x --description 'Treat unknown capabilities as user-defined'
complete -c tic -s U --description 'tells tic to not post-process the data after ... [See Man Page]'
complete -c tic -s R
complete -c tic -s o

