# tiffgt: Deroffing man parser
# Autogenerated from man pages
complete -c tiffgt -s c --description 'Force image display in a colormap window'
complete -c tiffgt -s d --description 'Specify an image to display by directory numb... [See Man Page]'
complete -c tiffgt -s e --description 'Enable reporting of error messages from the  ... [See Man Page]'
complete -c tiffgt -s f --description 'Force   tiffgt to run as a foreground process... [See Man Page]'
complete -c tiffgt -s l --description 'Force the presumed bit ordering to be '
complete -c tiffgt -s m --description 'Force the presumed bit ordering to be '
complete -c tiffgt -s o --description 'Specify an image to display by directory offs... [See Man Page]'
complete -c tiffgt -s p --description 'Override the value of the  PhotometricInterpr... [See Man Page]'
complete -c tiffgt -s r --description 'Force image display in a full color window'
complete -c tiffgt -s s --description 'Stop on the first read error'
complete -c tiffgt -s w --description 'Enable reporting of warning messages from the... [See Man Page]'
complete -c tiffgt -o lgutil
complete -c tiffgt -s v --description 'Place information in the title bar describing... [See Man Page]'

