# tiffsv: Deroffing man parser
# Autogenerated from man pages
complete -c tiffsv -s b --description 'Save the image as a greyscale image as if it ... [See Man Page]'
complete -c tiffsv -s c --description 'Specify the compression to use for data writt... [See Man Page]'
complete -c tiffsv -s p --description 'Specify the planar configuration to use in wr... [See Man Page]'
complete -c tiffsv -s r --description 'Specify the number of rows (scanlines) in eac... [See Man Page]'

