# tiffdump: Deroffing man parser
# Autogenerated from man pages
complete -c tiffdump -s h --description 'Force numeric data to be printed in hexadecim... [See Man Page]'
complete -c tiffdump -s m --description 'Change the number of indirect data items that... [See Man Page]'
complete -c tiffdump -s o --description 'Dump the contents of the '

