# tiff2rgba: Deroffing man parser
# Autogenerated from man pages
complete -c tiff2rgba -s c --description 'Specify a compression scheme to use when writ... [See Man Page]'
complete -c tiff2rgba -s r --description 'Write data with a specified number of rows pe... [See Man Page]'
complete -c tiff2rgba -s b --description 'Process the image one block (strip/tile) at a... [See Man Page]'
complete -c tiff2rgba -s n --description 'flag is used, three samples per pixel (red, g... [See Man Page]'

