# tiffmedian: Deroffing man parser
# Autogenerated from man pages
complete -c tiffmedian -s c --description 'Specify the compression to use for data writt... [See Man Page]'
complete -c tiffmedian -s C --description 'Specify the number of entries to use in the g... [See Man Page]'
complete -c tiffmedian -s f --description 'Apply Floyd-Steinberg dithering before select... [See Man Page]'
complete -c tiffmedian -s r --description 'Specify the number of rows (scanlines) in eac... [See Man Page]'

