# tiffinfo: Deroffing man parser
# Autogenerated from man pages
complete -c tiffinfo -s c --description 'Display the colormap and color/gray response ... [See Man Page]'
complete -c tiffinfo -s D --description 'In addition to displaying the directory tags,... [See Man Page]'
complete -c tiffinfo -s d --description 'In addition to displaying the directory tags,... [See Man Page]'
complete -c tiffinfo -s j --description 'Display any \\s-2JPEG\\s0-related tags that are... [See Man Page]'
complete -c tiffinfo -s o --description 'Set the initial '
complete -c tiffinfo -s s --description 'Display the offsets and byte counts for each ... [See Man Page]'
complete -c tiffinfo -s z --description 'Enable strip chopping when reading image data... [See Man Page]'
complete -c tiffinfo -s '#' --description 'Set the initial'

