# tiffset: Deroffing man parser
# Autogenerated from man pages
complete -c tiffset -s s --description 'Set the value of the named tag to the value o... [See Man Page]'
complete -c tiffset -o sf --description 'Set the value of the tag to the contents of f... [See Man Page]'

