# tiff2bw: Deroffing man parser
# Autogenerated from man pages
complete -c tiff2bw -s c --description 'Specify a compression scheme to use when writ... [See Man Page]'
complete -c tiff2bw -s r --description 'Write data with a specified number of rows pe... [See Man Page]'
complete -c tiff2bw -s R --description 'Specify the percentage of the red channel to ... [See Man Page]'
complete -c tiff2bw -s G --description 'Specify the percentage of the green channel t... [See Man Page]'
complete -c tiff2bw -s B --description 'options may be used'

