# tiffcmp: Deroffing man parser
# Autogenerated from man pages
complete -c tiffcmp -s l --description 'List each byte of image data that differs bet... [See Man Page]'
complete -c tiffcmp -s z --description 'List specified number of image data bytes tha... [See Man Page]'
complete -c tiffcmp -s t --description 'Ignore any differences in directory tags'

