# tiffdither: Deroffing man parser
# Autogenerated from man pages
complete -c tiffdither -s c --description 'Specify the compression to use for data writt... [See Man Page]'
complete -c tiffdither -s f --description 'Specify the bit fill order to use in writing ... [See Man Page]'
complete -c tiffdither -s t --description 'Set the threshold value for dithering'

