# tiffcp: Deroffing man parser
# Autogenerated from man pages
complete -c tiffcp -s b --description 'subtract the following monochrome image from ... [See Man Page]'
complete -c tiffcp -s B --description 'Force output to be written with Big-Endian by... [See Man Page]'
complete -c tiffcp -s C --description 'Suppress the use of ``strip chopping\'\' when r... [See Man Page]'
complete -c tiffcp -s c --description 'Specify the compression to use for data writt... [See Man Page]'
complete -c tiffcp -s f --description 'Specify the bit fill order to use in writing ... [See Man Page]'
complete -c tiffcp -s i --description 'Ignore non-fatal read errors and continue pro... [See Man Page]'
complete -c tiffcp -s l --description 'Specify the length of a tile (in pixels)'
complete -c tiffcp -s L --description 'Force output to be written with Little-Endian... [See Man Page]'
complete -c tiffcp -s M --description 'Suppress the use of memory-mapped files when ... [See Man Page]'
complete -c tiffcp -s p --description 'Specify the planar configuration to use in wr... [See Man Page]'
complete -c tiffcp -s r --description 'Specify the number of rows (scanlines) in eac... [See Man Page]'
complete -c tiffcp -s s --description 'Force the output file to be written with data... [See Man Page]'
complete -c tiffcp -s t --description 'Force the output file to be written with data... [See Man Page]'
complete -c tiffcp -s w --description 'Specify the width of a tile (in pixels)'
complete -c tiffcp -s x --description 'Force the output file to be written with PAGE... [See Man Page]'
complete -c tiffcp -s 1 --description 'it will results in infinite number of the row... [See Man Page]'

