# tig: Deroffing man parser
# Autogenerated from man pages
complete -c tig -s v -l version --description 'Show version and exit'
complete -c tig -s h -l help --description 'Show help message and exit'

