# tkcon: Deroffing man parser
# Autogenerated from man pages
complete -c tkcon -o argv -l ')' --description 'Causes TkCon to stop evaluating arguments and... [See Man Page]'
complete -c tkcon -o 'color-<color>' --description 'Sets the requested color type to the specifie... [See Man Page]'
complete -c tkcon -o eval -o main -o 'e)' --description 'A Tcl script to eval in each main interpreter... [See Man Page]'
complete -c tkcon -o exec --description 'Sets the named slave that tkcon operates in'
complete -c tkcon -o font --description 'Sets the font that tkcon uses for its text wi... [See Man Page]'
complete -c tkcon -o nontcl --description 'Sets ::tkcon::OPT(nontcl) to TCL_BOOLEAN (see... [See Man Page]'
complete -c tkcon -o package -o 'load)' --description 'Packages to automatically load into the slave... [See Man Page]'
complete -c tkcon -o rcfile --description 'Specify an alternate tkcon resource file name... [See Man Page]'
complete -c tkcon -o root --description 'Makes the named widget the root name of all c... [See Man Page]'
complete -c tkcon -o slave --description 'A Tcl script to eval in each slave interprete... [See Man Page]'

