# tmux: Darwin man parser
# Autogenerated from man pages
complete -c tmux -s 2 --description Force
complete -c tmux -s 8 --description Like
complete -c tmux -s c --description Execute
complete -c tmux -s f --description 'Specify an alternative configuration file'
complete -c tmux -s L
complete -c tmux -s l --description 'Behave as a login shell'
complete -c tmux -s q --description 'Set the'
complete -c tmux -s S --description 'Specify a full alternative path to the server... [See Man Page]'
complete -c tmux -s u
complete -c tmux -s v --description 'Request verbose logging'
complete -c tmux -s V --description 'Report the'

