# toe: Deroffing man parser
# Autogenerated from man pages
complete -c toe -s a --description 'report on all of the terminal databases which... [See Man Page]'
complete -c toe -s u --description 'says to write a report to the standard output... [See Man Page]'
complete -c toe -s U --description 'says to write a report to the standard output... [See Man Page]'
complete -c toe -o vn --description 'specifies that (verbose) output be written to... [See Man Page]'
complete -c toe -s V --description 'reports the version of ncurses which was used... [See Man Page]'

