# topsyscall: Deroffing man parser
# Autogenerated from man pages
complete -c topsyscall -s C --description 'don\'t clear the screen'
complete -c topsyscall -s s --description 'print per second values'

