# topsysproc: Deroffing man parser
# Autogenerated from man pages
complete -c topsysproc -s C --description 'don\'t clear the screen'
complete -c topsysproc -s s --description 'print per second values'

