# tops: Deroffing man parser
# Autogenerated from man pages
complete -c tops -o help --description 'Displays the tops syntax line'
complete -c tops -o verbose --description 'Prints out the source code lines that are bei... [See Man Page]'
complete -c tops -o nocontext --description 'Instead of printing the whole source code lin... [See Man Page]'
complete -c tops -o nofileinfo --description 'Does not print the file name and line number ... [See Man Page]'
complete -c tops -o semiverbose --description 'Shows how much of the file has been processed... [See Man Page]'
complete -c tops -o dont --description 'Shows what changes would be made to the sourc... [See Man Page]'
complete -c tops -o scriptfile --description 'Specifies the script file containing the rule... [See Man Page]'
complete -c tops -o classfile --description 'Specifies a file that describes the class hie... [See Man Page]'

