# touch: Darwin man parser
# Autogenerated from man pages
complete -c touch -s A --description 'Adjust the access and modification time stamp... [See Man Page]'
complete -c touch -s a --description 'Change the access time of the file'
complete -c touch -s c --description 'Do not create the file if it does not exist'
complete -c touch -s f --description 'Attempt to force the update, even if the file... [See Man Page]'
complete -c touch -s h --description 'If the file is a symbolic link, change the ti... [See Man Page]'
complete -c touch -s m --description 'Change the modification time of the file'
complete -c touch -s r --description 'Use the access and modifications times from t... [See Man Page]'
complete -c touch -s t --description 'Change the access and modification times to t... [See Man Page]'

