# tput: Deroffing man parser
# Autogenerated from man pages
complete -c tput -o Ttype --description 'indicates the type of terminal'
complete -c tput -s S --description 'allows more than one capability per invocatio... [See Man Page]'
complete -c tput -s V --description 'reports the version of ncurses which was used... [See Man Page]'

