# tr: Darwin man parser
# Autogenerated from man pages
complete -c tr -s C --description 'Complement the set of characters in'
complete -c tr -s c --description 'Same as'
complete -c tr -s d --description 'Delete characters in'
complete -c tr -s s --description 'Squeeze multiple occurrences of the character... [See Man Page]'
complete -c tr -s u --description 'Guarantee that any output is unbuffered'

