# troff: Deroffing man parser
# Autogenerated from man pages
complete -c troff -s b --description 'Print a backtrace with each warning or error ... [See Man Page]'
complete -c troff -s c --description 'Disable color output (always disabled in comp... [See Man Page]'
complete -c troff -s C --description 'Enable compatibility mode'
complete -c troff -s d
complete -c troff -s E --description 'Inhibit all error messages of  troff '
complete -c troff -s f --description 'Use  fam as the default font family'
complete -c troff -s F --description 'Search in directory (or directory path)  dir ... [See Man Page]'
complete -c troff -s i --description 'Read the standard input after all the named i... [See Man Page]'
complete -c troff -s I --description 'This option may be used to specify a director... [See Man Page]'
complete -c troff -s m --description 'Read in the file B name '
complete -c troff -s M --description 'Search directory (or directory path)  dir for... [See Man Page]'
complete -c troff -s n --description 'Number the first page R num '
complete -c troff -s o --description 'Output only pages in R list , which is a comm... [See Man Page]'
complete -c troff -s r
complete -c troff -s R --description 'Don\'t load  troffrc and  troffrc-end '
complete -c troff -s T --description 'Prepare output for device R name , rather tha... [See Man Page]'
complete -c troff -s U --description 'Unsafe mode'
complete -c troff -s v --description 'Print the version number'
complete -c troff -s w --description 'Enable warning R  name '
complete -c troff -s W --description 'Inhibit warning R name '
complete -c troff -s a --description 'Generate an'
complete -c troff -s z --description 'Suppress formatted output'

