# tset: Deroffing man parser
# Autogenerated from man pages
complete -c tset -s I --description 'Do not send the terminal or tab initializatio... [See Man Page]'
complete -c tset -s i --description 'Set the interrupt character to ch'
complete -c tset -s k --description 'Set the line kill character to ch'
complete -c tset -s m --description 'Specify a mapping from a port type to a termi... [See Man Page]'
complete -c tset -s Q --description 'Do not display any values for the erase, inte... [See Man Page]'
complete -c tset -s q --description 'The terminal type is displayed to the standar... [See Man Page]'
complete -c tset -s r --description 'Print the terminal type to the standard error... [See Man Page]'
complete -c tset -s s --description 'Print the sequence of shell commands to initi... [See Man Page]'
complete -c tset -s V --description 'reports the version of ncurses which was used... [See Man Page]'
complete -c tset -s c --description 'Set control characters and modes'
complete -c tset -s e --description 'Set the erase character to ch'
complete -c tset -s w --description 'Resize the window to match the size deduced v... [See Man Page]'
complete -c tset -s n -o adnp --description 'omitted from the usage summary above'

