# tsort: Darwin man parser
# Autogenerated from man pages
complete -c tsort -s l --description 'Search for and display the longest cycle'
complete -c tsort -s q --description 'Do not display informational messages about c... [See Man Page]'

