# tsql: Deroffing man parser
# Autogenerated from man pages
complete -c tsql -s S --description 'the Database Server to which to connect'
complete -c tsql -s I --description 'a freetds'
complete -c tsql -s H --description 'the DNS hostname of the server'
complete -c tsql -s p --description 'the port at which SQL Server is listening'
complete -c tsql -s U --description 'database login name'
complete -c tsql -s P --description 'database password'
complete -c tsql -s C --description 'prints some of the compile-time configuration... [See Man Page]'
complete -c tsql -s o --description 'apply the options specified to every command'
complete -c tsql -s L -o 'H)'

