# ul: Darwin man parser
# Autogenerated from man pages
complete -c ul -s i --description 'Underlining is indicated by a separate line c... [See Man Page]'
complete -c ul -s t --description 'Overrides the terminal type specified in the ... [See Man Page]'

