# unifdef: Darwin man parser
# Autogenerated from man pages
complete -c unifdef -s D --description 'Specify that a symbol is defined to a given v... [See Man Page]'
complete -c unifdef -s U --description 'Specify that a symbol is undefined'
complete -c unifdef -s b --description 'Replace removed lines with blank linesinstead... [See Man Page]'
complete -c unifdef -s B --description 'Compress blank lines around a deleted section... [See Man Page]'
complete -c unifdef -s c --description 'If the'
complete -c unifdef -s d --description 'Turn on printing of debugging messages'
complete -c unifdef -s e --description Because
complete -c unifdef -s K --description 'Always treat the result of'
complete -c unifdef -s k --description Process
complete -c unifdef -s n --description Add
complete -c unifdef -s o --description 'Write output to the file'
complete -c unifdef -s s --description 'Instead of processing the input file as usual... [See Man Page]'
complete -c unifdef -s S --description 'Like the'
complete -c unifdef -s t --description 'Disables parsing for C commentsand line conti... [See Man Page]'
complete -c unifdef -l iD
complete -c unifdef -l iU --description Ignore
complete -c unifdef -s I --description 'Specifies to'
complete -c unifdef -s V --description 'Print version details'

