# unifdefall: Darwin man parser
# Autogenerated from man pages
complete -c unifdefall -s D --description 'Specify that a symbol is defined to a given v... [See Man Page]'
complete -c unifdefall -s U --description 'Specify that a symbol is undefined'
complete -c unifdefall -s b --description 'Replace removed lines with blank linesinstead... [See Man Page]'
complete -c unifdefall -s B --description 'Compress blank lines around a deleted section... [See Man Page]'
complete -c unifdefall -s c --description 'If the'
complete -c unifdefall -s d --description 'Turn on printing of debugging messages'
complete -c unifdefall -s e --description Because
complete -c unifdefall -s K --description 'Always treat the result of'
complete -c unifdefall -s k --description Process
complete -c unifdefall -s n --description Add
complete -c unifdefall -s o --description 'Write output to the file'
complete -c unifdefall -s s --description 'Instead of processing the input file as usual... [See Man Page]'
complete -c unifdefall -s S --description 'Like the'
complete -c unifdefall -s t --description 'Disables parsing for C commentsand line conti... [See Man Page]'
complete -c unifdefall -l iD
complete -c unifdefall -l iU --description Ignore
complete -c unifdefall -s I --description 'Specifies to'
complete -c unifdefall -s V --description 'Print version details'

