# uniq: Darwin man parser
# Autogenerated from man pages
complete -c uniq -s c --description 'Precede each output line with the count of th... [See Man Page]'
complete -c uniq -s d --description 'Only output lines that are repeated in the in... [See Man Page]'
complete -c uniq -s f --description 'Ignore the first'
complete -c uniq -s s --description 'Ignore the first'
complete -c uniq -s u --description 'Only output lines that are not repeated in th... [See Man Page]'
complete -c uniq -s i --description 'Case insensitive comparison of lines'

