# UnRezWack: Darwin man parser
# Autogenerated from man pages
complete -c UnRezWack -s o --description 'Base path of the output files'
complete -c UnRezWack -s f --description 'Force overwriting of output files'

