# update_dyld_shared_cache: Darwin man parser
# Autogenerated from man pages
complete -c update_dyld_shared_cache -l root --description 'This option specifies the root of an OS insta... [See Man Page]'
complete -c update_dyld_shared_cache -l overlay --description 'This option specifies the root of a sparse di... [See Man Page]'
complete -c update_dyld_shared_cache -l arch --description 'By default '
complete -c update_dyld_shared_cache -l force --description 'This option will cause '
complete -c update_dyld_shared_cache -l debug --description 'This option prints out additional information... [See Man Page]'
complete -c update_dyld_shared_cache -l sort_by_name --description 'By default'
complete -c update_dyld_shared_cache -l universal_boot --description 'This option can only be used running on an ma... [See Man Page]'
complete -c update_dyld_shared_cache -l dylib_list --description 'Instead of scanning /var/db/dyld/shared_regio... [See Man Page]'
complete -c update_dyld_shared_cache -l verify --description 'Will regenerate a shared cache in-memory that... [See Man Page]'
complete -c update_dyld_shared_cache -l iPhone --description 'indicates that cache is not for the current M... [See Man Page]'
complete -c update_dyld_shared_cache -l cache_dir --description 'This option specifies the directory in which ... [See Man Page]'

