# uuencode: Darwin man parser
# Autogenerated from man pages
complete -c uuencode -s m --description 'Use the Base64 method of encoding, rather tha... [See Man Page]'
complete -c uuencode -s o --description 'Output to'
complete -c uuencode -s c --description 'Decode more than one uuencode\'d file from'
complete -c uuencode -s i --description 'Do not overwrite files'
complete -c uuencode -s p --description Decode
complete -c uuencode -s s --description 'Do not strip output pathname to base filename... [See Man Page]'

