# uuid: Type1
# Autogenerated from man pages
complete -c uuid -s v --description 'Sets the version of the generated \\s-1DCE\\s0 ... [See Man Page]'
complete -c uuid -s m --description 'Forces the use of a random multi-cast \\s-1MAC... [See Man Page]'
complete -c uuid -s n --description 'Generate count UUIDs instead of just a single... [See Man Page]'
complete -c uuid -s 1 --description 'If option -n is used with a count greater tha... [See Man Page]'
complete -c uuid -s F --description 'Representation format for importing or export... [See Man Page]'
complete -c uuid -s o --description 'Write output to filename instead of to stdout... [See Man Page]'

