# uulog: Deroffing man parser
# Autogenerated from man pages
complete -c uulog -s '#' -s n -l lines --description 'Here \'#\' is a number; e'
complete -c uulog -s s -l system --description 'Display only log entries pertaining to the sp... [See Man Page]'
complete -c uulog -s u -l user --description 'Display only log entries pertaining to the sp... [See Man Page]'
complete -c uulog -s D -l debuglog --description 'Display the debugging log file'
complete -c uulog -s S -l statslog --description 'Display the statistics log file'
complete -c uulog -s F -l follow --description 'Keep displaying the log file forever, printin... [See Man Page]'
complete -c uulog -s f --description 'Keep displaying the log file forever, display... [See Man Page]'
complete -c uulog -s X -l debug --description 'Turn on particular debugging types'
complete -c uulog -s I -l config --description 'Set configuration file to use'
complete -c uulog -s v -l version --description 'Report version information and exit'
complete -c uulog -l help --description 'Print a help message and exit'

