# uuname: Deroffing man parser
# Autogenerated from man pages
complete -c uuname -s a -l aliases --description 'List all aliases for remote systems, as well ... [See Man Page]'
complete -c uuname -s l -l local --description 'Print the UUCP name of the local system, rath... [See Man Page]'
complete -c uuname -s x -l debug --description 'Turn on particular debugging types'
complete -c uuname -s I -l config --description 'Set configuration file to use'
complete -c uuname -s v -l version --description 'Report version information and exit'
complete -c uuname -l help --description 'Print a help message and exit'

