# uupick: Deroffing man parser
# Autogenerated from man pages
complete -c uupick -s s -l system --description 'Used to restrict `uupick\' to only present fil... [See Man Page]'
complete -c uupick -s x -l debug --description 'Turn on particular debugging types'
complete -c uupick -s I -l config --description 'Set configuration file to use'
complete -c uupick -s v -l version --description 'Report version information and exit'
complete -c uupick -l help --description 'Print a help message and exit'

