# vers_string: Deroffing man parser
# Autogenerated from man pages
complete -c vers_string -s c --description 'option is used, the output is formed as a C d... [See Man Page]'
complete -c vers_string -s l --description 'option is used, the output is formed like the... [See Man Page]'
complete -c vers_string -s f --description 'option is used, the output is simply the prog... [See Man Page]'

