# vfontedpr: Darwin man parser
# Autogenerated from man pages
complete -c vfontedpr -s d --description 'specifies an alternative language definitions... [See Man Page]'
complete -c vfontedpr -s f --description 'forces filter mode'
complete -c vfontedpr -s h --description 'specifies a particular header to put on every... [See Man Page]'
complete -c vfontedpr -s l --description 'specifies the language to use'
complete -c vfontedpr -s n --description 'forces no keyword bolding'
complete -c vfontedpr -s s --description 'specifies a point size to use on output (exac... [See Man Page]'
complete -c vfontedpr -s t --description 'similar to the same option in'
complete -c vfontedpr -s W --description 'forces output to the (wide) Versatec printer ... [See Man Page]'
complete -c vfontedpr -s x --description 'outputs the index file in a ``pretty\'\' format... [See Man Page]'

