# vis: Darwin man parser
# Autogenerated from man pages
complete -c vis -s b --description 'Turns off prepending of backslash before up-a... [See Man Page]'
complete -c vis -s c --description 'Request a format which displays a small subse... [See Man Page]'
complete -c vis -s F --description Causes
complete -c vis -s f --description 'Same as'
complete -c vis -s l --description 'Mark newlines with the visible sequence'
complete -c vis -s n --description 'Turns off any encoding, except for the fact t... [See Man Page]'
complete -c vis -s o --description 'Request a format which displays non-printable... [See Man Page]'
complete -c vis -s s --description 'Only characters considered unsafe to send to ... [See Man Page]'
complete -c vis -s t --description 'Tabs are also encoded'
complete -c vis -s w --description 'White space (space-tab-newline) is also encod... [See Man Page]'

