# vmmap: Darwin man parser
# Autogenerated from man pages
complete -c vmmap -s d --description 'Take two snapshots of the vm regions of the p... [See Man Page]'
complete -c vmmap -l w --description 'Print wide output'
complete -c vmmap -l resident --description 'Show both the virtual and resident sizes for ... [See Man Page]'
complete -c vmmap -l pages --description 'Print region sizes in page counts rather than... [See Man Page]'
complete -c vmmap -l interleaved --description 'Print all regions in ascending order of start... [See Man Page]'
complete -c vmmap -l submap --description 'Print information about VM submaps'
complete -c vmmap -l allSplitLibs --description 'Print information about all shared system spl... [See Man Page]'
complete -c vmmap -l noCoalesce --description 'Do not coalesce adjacent identical regions'
complete -c vmmap -l v --description 'Equivalent to '

