# wc: Darwin man parser
# Autogenerated from man pages
complete -c wc -s c --description 'The number of bytes in each input fileis writ... [See Man Page]'
complete -c wc -s l --description 'The number of lines in each input fileis writ... [See Man Page]'
complete -c wc -s m --description 'The number of characters in each input file i... [See Man Page]'
complete -c wc -s w --description 'The number of words in each input fileis writ... [See Man Page]'

