# which: Darwin man parser
# Autogenerated from man pages
complete -c which -s a --description 'List all instances of executables found (inst... [See Man Page]'
complete -c which -s s --description 'No output, just return 0 if any of the execut... [See Man Page]'

