# who: Darwin man parser
# Autogenerated from man pages
complete -c who -s a --description 'Same as'
complete -c who -s b --description 'Time of last system boot'
complete -c who -s d --description 'Print dead processes'
complete -c who -s H --description 'Write column headings above the regular outpu... [See Man Page]'
complete -c who -s l --description 'Print system login processes (unsupported)'
complete -c who -s m --description 'Only print information about the current term... [See Man Page]'
complete -c who -s p --description 'Print active processes spawned by'
complete -c who -s q
complete -c who -s r --description 'Print the current runlevel'
complete -c who -s s --description 'List only the name, line and time fields'
complete -c who -s T --description 'Print a character after the user name indicat... [See Man Page]'
complete -c who -s t --description 'Print last system clock change (unsupported)'
complete -c who -s u --description 'Print the idle time for each user, and the as... [See Man Page]'

