# whois: Darwin man parser
# Autogenerated from man pages
complete -c whois -s 6 --description 'Use the IPv6 Resource Center'
complete -c whois -s A --description 'Use the Asia/Pacific Network Information Cent... [See Man Page]'
complete -c whois -s a --description 'Use the American Registry for Internet Number... [See Man Page]'
complete -c whois -s b --description 'Use the Network Abuse Clearinghouse database'
complete -c whois -s c --description 'This is the equivalent of using the'
complete -c whois -s d --description 'Use the US Department of Defensedatabase'
complete -c whois -s g --description 'Use the US non-military federal government da... [See Man Page]'
complete -c whois -s h --description 'Use the specified host instead of the default... [See Man Page]'
complete -c whois -s I --description 'Use the Internet Assigned Numbers Authority'
complete -c whois -s i --description 'Use the Network Solutions Registry for Intern... [See Man Page]'
complete -c whois -s l --description 'Use the Latin American and Caribbean IP addre... [See Man Page]'
complete -c whois -s m --description 'Use the Route Arbiter Database'
complete -c whois -s p --description 'Connect to the whois server on'
complete -c whois -s Q --description 'Do a quick lookup'
complete -c whois -s R --description 'Use the Russia Network Information Center'
complete -c whois -s r --description 'Use the R\\(aaeseaux IP Europ\\(aaeens'

