# wish: Deroffing man parser
# Autogenerated from man pages
complete -c wish -o encoding
complete -c wish -o colormap --description 'Specifies that the window should have a new p... [See Man Page]'
complete -c wish -o display --description 'Display (and screen) on which to display wind... [See Man Page]'
complete -c wish -o geometry --description 'Initial geometry to use for window'
complete -c wish -o name --description 'Use name as the title to be displayed in the ... [See Man Page]'
complete -c wish -o sync --description 'Execute all X server commands synchronously, ... [See Man Page]'
complete -c wish -o use --description 'Specifies that the main window for the applic... [See Man Page]'
complete -c wish -o visual --description 'Specifies the visual to use for the window'
complete -c wish -o container

