# wrjpgcom: Deroffing man parser
# Autogenerated from man pages
complete -c wrjpgcom -o replace --description 'Delete any existing COM blocks from the file'
complete -c wrjpgcom -o comment --description 'Supply text for new COM block on command line... [See Man Page]'
complete -c wrjpgcom -o cfile --description 'Read text for new COM block from named file'

