# wsimport: Deroffing man parser
# Autogenerated from man pages
complete -c wsimport -s d --description 'Specify where to place generated output files... [See Man Page]'
complete -c wsimport -s b --description 'Specify external JAX-WS or JAXB binding files... [See Man Page]'
complete -c wsimport -o catalog --description 'Specify catalog file to resolve external enti... [See Man Page]'
complete -c wsimport -o extension --description 'Allow vendor extensions (functionality not sp... [See Man Page]'
complete -c wsimport -o help --description 'Display help'
complete -c wsimport -o httpproxy: --description 'Specify an HTTP proxy server (port defaults t... [See Man Page]'
complete -c wsimport -o keep --description 'Keep generated files'
complete -c wsimport -s p --description 'Specifying a target package via this command-... [See Man Page]'
complete -c wsimport -s s --description 'Specify where to place generated source files... [See Man Page]'
complete -c wsimport -o verbose --description 'Output messages about what the compiler is do... [See Man Page]'
complete -c wsimport -o version --description 'Print version information'
complete -c wsimport -o wsdllocation --description @WebService

