# xargs: Darwin man parser
# Autogenerated from man pages
complete -c xargs -s 0 --description Change
complete -c xargs -s E --description Use
complete -c xargs -s I --description Execute
complete -c xargs -s J --description 'If this option is specified,'
complete -c xargs -s L --description Call
complete -c xargs -s n --description 'Set the maximum number of arguments taken fro... [See Man Page]'
complete -c xargs -s o --description 'Reopen stdin as'
complete -c xargs -s P --description 'Parallel mode: run at most'
complete -c xargs -s p --description 'Echo each command to be executed and ask the ... [See Man Page]'
complete -c xargs -s R --description 'Specify the maximum number of arguments that'
complete -c xargs -s s --description 'Set the maximum number of bytes for the comma... [See Man Page]'
complete -c xargs -s t --description 'Echo the command to be executed to standard e... [See Man Page]'
complete -c xargs -s x --description Force

