# xattr: Darwin man parser
# Autogenerated from man pages
complete -c xattr -s l --description 'By default, the first two command forms eithe... [See Man Page]'
complete -c xattr -s r --description 'If a file argument is a directory, act as if ... [See Man Page]'
complete -c xattr -s s --description 'If a file argument is a symbolic link, act on... [See Man Page]'
complete -c xattr -s v --description 'Force the the file name to be displayed, even... [See Man Page]'
complete -c xattr -s x --description 'Force the attribute value to be displayed in ... [See Man Page]'

