# xcodebuild: Darwin man parser
# Autogenerated from man pages
complete -c xcodebuild -l project --description 'Build the project specified by '
complete -c xcodebuild -l target --description 'Build the target specified by '
complete -c xcodebuild -l alltargets --description 'Build all the targets in the specified projec... [See Man Page]'
complete -c xcodebuild -l workspace --description 'Build the workspace specified by'
complete -c xcodebuild -l scheme --description 'Build the scheme specified by'
complete -c xcodebuild -l configuration --description 'Use the build configuration specified by '
complete -c xcodebuild -l arch --description 'Use the architecture specified by '
complete -c xcodebuild -l sdk --description 'Build an Xcode project or workspace against t... [See Man Page]'
complete -c xcodebuild -l showsdks --description 'Lists all available SDKs that Xcode knows abo... [See Man Page]'
complete -c xcodebuild -l list --description 'Lists the targets and configurations in a pro... [See Man Page]'
complete -c xcodebuild -l xcconfig --description 'Load the build settings defined in '
complete -c xcodebuild -l version --description 'Display version information for this install ... [See Man Page]'
complete -c xcodebuild -l usage --description 'Displays usage information for '

