# xcrun: Darwin man parser
# Autogenerated from man pages
complete -c xcrun -l verbose --description 'Display information about how the redirected ... [See Man Page]'
complete -c xcrun -l no-cache --description 'Don\'t consult the cache when looking up value... [See Man Page]'
complete -c xcrun -l kill-cache --description 'Removes the cache'
complete -c xcrun -l sdk --description 'Specifies which SDK to use'
complete -c xcrun -l log --description 'Print the full command line that is invoked'
complete -c xcrun -l find --description 'Print the full path to the tool'

