# xjc: Deroffing man parser
# Autogenerated from man pages
complete -c xjc -o nv --description 'By default, the XJC binding compiler performs... [See Man Page]'
complete -c xjc -o extension --description 'By default, the XJC binding compiler strictly... [See Man Page]'
complete -c xjc -s b --description 'Specify one or more external binding files to... [See Man Page]'
complete -c xjc -s d --description 'By default, the XJC binding compiler will gen... [See Man Page]'
complete -c xjc -s p --description 'Specifying a target package via this command-... [See Man Page]'
complete -c xjc -o httpproxy --description 'Specify the HTTP/HTTPS proxy'
complete -c xjc -o httpproxyfile
complete -c xjc -o classpath --description 'Specify where to find client application clas... [See Man Page]'
complete -c xjc -o catalog --description 'Specify catalog files to resolve external ent... [See Man Page]'
complete -c xjc -o readOnly --description 'By default, the XJC binding compiler does not... [See Man Page]'
complete -c xjc -o npa --description 'Supress the generation of package level annot... [See Man Page]'
complete -c xjc -o xmlschema --description 'Treat input schemas as W3C XML Schema (defaul... [See Man Page]'
complete -c xjc -o relaxng --description 'Treat input schemas as RELAX NG (experimental... [See Man Page]'
complete -c xjc -o relaxng-compact --description 'Treat input schemas as RELAX NG compact synta... [See Man Page]'
complete -c xjc -o dtd --description 'Treat input schemas as XML DTD (experimental,... [See Man Page]'
complete -c xjc -o wsdl --description 'Treat input as WSDL and compile schemas insid... [See Man Page]'
complete -c xjc -o quiet --description 'Suppress compiler output, such as progress in... [See Man Page]'
complete -c xjc -o verbose --description 'Be extra verbose, such as printing informatio... [See Man Page]'
complete -c xjc -o help --description 'Display a brief summary of the compiler switc... [See Man Page]'
complete -c xjc -o version --description 'Display the compiler version information'
complete -c xjc -o host -o port --description 'These options have been deprecated and replac... [See Man Page]'
complete -c xjc -o use-runtime --description 'Since the JAXB 2'
complete -c xjc -o source --description 'The -source compatibility switch was introduc... [See Man Page]'
complete -c xjc -o Xlocator -o Xsync-methods --description 'These switches have been disabled for now'
complete -c xjc -s '>' --description 4

