# xml2-config: Deroffing man parser
# Autogenerated from man pages
complete -c xml2-config -l version --description 'Print the currently installed version of GNOM... [See Man Page]'
complete -c xml2-config -l libs --description 'Print the linker flags that are necessary to ... [See Man Page]'
complete -c xml2-config -l cflags --description 'Print the compiler flags that are necessary t... [See Man Page]'
complete -c xml2-config -l prefix --description 'If specified, use PREFIX instead of the insta... [See Man Page]'

