# xmlcatalog: Type1
# Autogenerated from man pages
complete -c xmlcatalog -l add --description 'Add an entry to CATALOGFILE'
complete -c xmlcatalog -l create --description 'Create a new XML catalog'
complete -c xmlcatalog -l del --description 'Remove entries from CATALOGFILE matching VALU... [See Man Page]'
complete -c xmlcatalog -l noout --description 'Save output to the named file rather than out... [See Man Page]'
complete -c xmlcatalog -l no-super-update --description 'Do not update the SGML super catalog'
complete -c xmlcatalog -l shell --description 'Run a shell allowing interactive queries on c... [See Man Page]'
complete -c xmlcatalog -l sgml --description 'Uses SGML super catalogs for --add and --del ... [See Man Page]'

