# xmlwf: Type1
# Autogenerated from man pages
complete -c xmlwf -s c --description 'If the input file is well-formed and xmlwf do... [See Man Page]'
complete -c xmlwf -s d --description 'Specifies a directory to contain transformed ... [See Man Page]'
complete -c xmlwf -s e --description 'Specifies the character encoding for the docu... [See Man Page]'
complete -c xmlwf -s m --description 'Outputs some strange sort of XML file that co... [See Man Page]'
complete -c xmlwf -s n --description 'Turns on namespace processing'
complete -c xmlwf -s p --description 'Tells xmlwf to process external DTDs and para... [See Man Page]'
complete -c xmlwf -s r --description 'Normally xmlwf memory-maps the XML file befor... [See Man Page]'
complete -c xmlwf -s s --description 'Prints an error if the document is not standa... [See Man Page]'
complete -c xmlwf -s t --description 'Turns on timings'
complete -c xmlwf -s v --description 'Prints the version of the Expat library being... [See Man Page]'
complete -c xmlwf -s w --description 'Enables support for Windows code pages'
complete -c xmlwf -s x --description 'Turns on parsing external entities'

