# xsubpp: Type1
# Autogenerated from man pages
complete -c xsubpp -o hiertype --description 'Retains \'::\' in type names so that \\*(C+ hier... [See Man Page]'
complete -c xsubpp -o except --description 'Adds exception handling stubs to the C code'
complete -c xsubpp -o typemap --description 'Indicates that a user-supplied typemap should... [See Man Page]'
complete -c xsubpp -o output --description 'Specifies the name of the output file to gene... [See Man Page]'
complete -c xsubpp -s v --description 'Prints the xsubpp version number to standard ... [See Man Page]'
complete -c xsubpp -o prototypes --description 'By default xsubpp will not automatically gene... [See Man Page]'
complete -c xsubpp -o noversioncheck --description 'Disables the run time test that determines if... [See Man Page]'
complete -c xsubpp -o nolinenumbers --description 'Prevents the inclusion of `#line\' directives ... [See Man Page]'
complete -c xsubpp -o nooptimize --description 'Disables certain optimizations'
complete -c xsubpp -o noinout --description 'Disable recognition of \\f(CW\\*(C`IN\\*(C\', \\f(... [See Man Page]'
complete -c xsubpp -o noargtypes --description 'Disable recognition of ANSI-like descriptions... [See Man Page]'

