# ypmatch: Darwin man parser
# Autogenerated from man pages
complete -c ypmatch -s d --description 'Specify a domain other than the default domai... [See Man Page]'
complete -c ypmatch -s k --description 'Display map keys'
complete -c ypmatch -s t --description 'Inhibit translation of map nicknamesto their ... [See Man Page]'
complete -c ypmatch -s x --description 'Display the map nickname table'

