# ypwhich: Darwin man parser
# Autogenerated from man pages
complete -c ypwhich -s d --description 'Specify a domain other than the default domai... [See Man Page]'
complete -c ypwhich -s t --description 'Inhibit translation of map nicknamesto their ... [See Man Page]'
complete -c ypwhich -s m --description 'Find the master'
complete -c ypwhich -s x --description 'Display the map nickname table'

