# zipcloak: Deroffing man parser
# Autogenerated from man pages
complete -c zipcloak -s b
complete -c zipcloak -l temp-path --description 'Use the directory given by path for the tempo... [See Man Page]'
complete -c zipcloak -s d
complete -c zipcloak -l decrypt --description 'Decrypt encrypted entries (copy if given wron... [See Man Page]'
complete -c zipcloak -s h
complete -c zipcloak -l help --description 'Show a short help'
complete -c zipcloak -s L
complete -c zipcloak -l license --description 'Show software license'
complete -c zipcloak -s O
complete -c zipcloak -l output-file --description 'Write output to new archive zipfile, leaving ... [See Man Page]'
complete -c zipcloak -s q
complete -c zipcloak -l quiet --description 'Quiet operation'
complete -c zipcloak -s v
complete -c zipcloak -l version --description 'Show version information'

