# zipinfo: Deroffing man parser
# Autogenerated from man pages
complete -c zipinfo -s 1 --description 'list filenames only, one per line'
complete -c zipinfo -s 2 --description 'list filenames only, one per line, but allow ... [See Man Page]'
complete -c zipinfo -s s --description 'list zipfile info in short Unix ``\\fCls -l\'\' ... [See Man Page]'
complete -c zipinfo -s m --description 'list zipfile info in medium Unix ``\\fCls -l\'\'... [See Man Page]'
complete -c zipinfo -s l --description 'list zipfile info in long Unix ``\\fCls -l\'\' f... [See Man Page]'
complete -c zipinfo -s v --description 'list zipfile information in verbose, multi-pa... [See Man Page]'
complete -c zipinfo -s h --description 'list header line'
complete -c zipinfo -s M --description 'pipe all output through an internal pager sim... [See Man Page]'
complete -c zipinfo -s t --description 'list totals for files listed or for all files... [See Man Page]'
complete -c zipinfo -s T --description 'print the file dates and times in a sortable ... [See Man Page]'
complete -c zipinfo -s z --description 'include the archive comment (if any) in the l... [See Man Page]'

