# znew: Deroffing man parser
# Autogenerated from man pages
complete -c znew -s f --description 'Force recompression from '
complete -c znew -s t --description 'Tests the new files before deleting originals... [See Man Page]'
complete -c znew -s v --description Verbose
complete -c znew -s 9 --description 'Use the slowest compression method (optimal c... [See Man Page]'
complete -c znew -s P --description 'Use pipes for the conversion to reduce disk s... [See Man Page]'
complete -c znew -s K --description 'Keep a '

