# zprint: Deroffing man parser
# Autogenerated from man pages
complete -c zprint -s c --description '(Default) zprint prints zone info in columns'
complete -c zprint -s h --description '(Default) Shows headings for the columns prin... [See Man Page]'
complete -c zprint -s s --description 'zprint sorts the zones, showing the zone wast... [See Man Page]'
complete -c zprint -s w --description 'For each zone, zprint calculates how much spa... [See Man Page]'
complete -c zprint -s t --description 'For each zone, zprint calculates the total si... [See Man Page]'
complete -c zprint -s d --description 'Display deltas over time, showing any zones t... [See Man Page]'
complete -c zprint -s p --description 'Display zone usage related to the specified p... [See Man Page]'

